docs/index.md

Removed old benchmark data from docs

Remove Old Benchmark Data

---

docs/index.md
mkdocs.yml

Fixed broken links on the docs home page in the "Model Support" section and the sidebar menu. 
- Fixed all of the links in the Home page Model Support section
- Fixed YOLOv7, YOLOv8 and YOLOACT segmentation links in the sidebar

Fixed broken links

---

.github/workflows/docker.jetson.4.5.0.yml
.github/workflows/docker.jetson.4.6.1.yml
.github/workflows/docker.jetson.5.1.1.yml
README.md
docker/dockerfiles/Dockerfile.onnx.jetson.4.5.0
docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1
docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1
docker/publish/jetson_trt_4.4.1_http.sh
docker/publish/jetson_trt_http.sh
docker/publish/jetson_trt_http_5.1.1.sh
docs/quickstart/docker.md
docs/quickstart/http_inference.md
examples/inference-client/README.md
inference/core/version.py

Updated jetson dockers, removed `trt` from image names, removed TensorRTExecution provider as default

Update Jetson Dockers

---

docs/quickstart/http_inference.md

Corrects http interface docs with Roboflow project terminology.

Fix/ Http docs uses consistent naming

---

docs/index.md
docs/quickstart/docker.md
docs/quickstart/http_inference.md
mkdocs.yml

This PR copies the contents of the README into the docs homepage and fixes an errant `git clone` in the manual Docker build instructions.
Docs change.
N/A
N/A

Ensure parity between docs homepage and README, fix git clone

---

docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1

Added an env var to jetson 5.1.1 image which avoids a bug during server startup

Jetson 5.1.1 Startup Bug

---

inference/core/env.py
inference/core/interfaces/camera/camera.py
inference/core/interfaces/udp/udp_stream.py
inference/core/managers/base.py
inference/core/managers/pingback.py
inference/core/models/roboflow.py
inference/core/registries/roboflow.py
inference/core/usage.py
inference/core/version.py

Added ability to disable inference cache. Also made default logging a lot less verbose, especially for pingback.

Optionally Disable Inference Caching

---

docs/index.md

This PR replaces the plain text link to the Inference demo to a HTML tag that embeds the video.

Update inference video on docs

---

README.md
docs/add_a_model.md
docs/changelog.md
docs/contributing.md
examples/README.md
examples/clip-search-engine/README.md
examples/clip-search-engine/app.py
examples/clip-search-engine/requirements.txt
examples/clip-search-engine/templates/index.html
examples/sam-client/app.py
examples/sam-client/requirements.txt
mkdocs.yml

This PR adds:
- An example showing how to use CLIP and SAM with Inference;
- A changelog to the main docs, and;
- More content to the Add a Model guide that shows how to add a model to Roboflow Inference.
Documentation change.
The examples are being tested manually.
N/A

Add CLIP and SAM examples, add new docs

---

requirements/requirements.cpu.txt

Updated onnxruntime to <=1.15.1 in cpu requirements to allow Python 3.11 for CPU installs

Upgrade Onnxruntime in CPU Requirements

---

inference/core/models/object_detection_base.py
inference/core/models/roboflow.py
inference/core/utils/image_utils.py

Fixed a bug in padding logic causing a minimum of 32 pixels of padding to be applied when the minimum padding should be 0 (in the case that the image dimensions are already a multiple of 32)
Tested locally

Padding Logic Bug Fix

---

inference/core/models/roboflow.py
inference/models/vit/vit_classification.py

Check lambda env var in addition to AWS key vars when choosing where to retrieve artifacts from.
GH actions

Check Lambda Env Var for Artifact Retrieval 

---

inference/enterprise/device_manager/container_service.py
inference/enterprise/device_manager/metrics_service.py

- Adding the actual version of the container image to the pingback (currently it's using the same version as the device-manager)
- Tested that the pingback sends the correct version on the image tag in the pingback logs

Add actual container version

---

.release/pypi/inference.core.setup.py

Just a tooling update to correctly read a list of requirements when creating wheels. No deploy needed.

Fix/ Core inference package updated to read list of requirements

---

custom_theme/404.html
mkdocs.yml

This PR adds a 404 page so that broken URLs don't return a page that looks like this:

Add 404 page

---

mkdocs.yml

This PR changes the `inference` site URL parameter in `mkdocs` to `inference.roboflow.com`.

Change documentation site URL

---

docs/library/docker_configuration_options.md
mkdocs.yml

Add docker configuration options to Library Reference section. This was removed from docs.roboflow.com and updated to be accurate with current options.

Docs/ Add docker configuration options page

---

inference/core/interfaces/camera/camera.py
inference/core/interfaces/stream/stream.py
inference/core/interfaces/udp/udp_stream.py

* do not convert each frame to PIL Image on the capture thread.
* when enforce_fps is 'skip':
- continue to grab frames rather than sleeping for the amount of time. VideoCapture requires streams to be continuously grabbed even if not used.
- do not `retrieve()` frames we are skipping. This gives a big performance improvement on the nano.
Tested locally with RTSP stream, mp4, and webcam, and on nano with RTSP stream.

improve performance of video capture for streams

---

requirements/requirements.doctr.txt

For some envs, tf2onnx needs to be installed manually for DocTR.

Fix doctr deps for jetson

---

Makefile
inference/core/interfaces/camera/camera.py
inference/core/interfaces/stream/stream.py

This makes the `enforce_fps='skip'` behavior the default.
Additionally, we now will by default grab file streams at their native FPS (`file_mode`), skipping frames until we are ready to infer in the same manner as we would when streaming. `enforce_fps` will additionally ensure that each frame of the file is inferred upon by the model.
We detect whether we are working with a file or a stream based on how many frames are available via `CAP_PROP_FRAME_COUNT` at start of the stream. In my testing, this was reliable for streams vs webcams vs static files on mac as well as on the nano with FFMPEG backend. If we are not working with a file, we do not allow `enforce_fps` as we know it will cause problems when the `VideoCapture` process gets too far behind in the stream.
-   [x] New feature …

Skip to latest frame of camera stream by default

---

Makefile

Reverts [this change](https://github.com/roboflow/inference/pull/120/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R7-R8) I made in #120 which was not needed as part of the PR.

revert accidental change to makefile

---

inference/core/logger.py
inference/core/models/classification_base.py
inference/core/models/instance_segmentation_base.py
inference/core/models/object_detection_base.py
inference/core/models/roboflow.py
inference/core/utils/validate.py
tests/inference/unit_tests/core/utils/test_validate.py

Added validation of the model through a test inference and by confirming the model output shape matches the expected number of classes.
Tested locally and with GH actions

Model Validation On Load

---

README.md

Edited the examples in the README to clarify the fact that `inference.Stream` only supports object detection at this time.
- Getting started example updated

Noted that inference stream only supports object detection

---

docs/javascript/init_kapa_widget.js

This PR fixes a typo in the URL of the image used in our new docs bot, Kapa.
This change was tested by running `mkdocs serve`, opening `localhost:8000`, and checking that the "Ask AI" bot in the bottom right corner has the correct image.
N/A
N/A

Fix URL in docs image

---

inference/core/managers/pingback.py
inference/core/roboflow_api.py
inference/core/utils/image_utils.py
inference/core/utils/requests.py
inference/enterprise/device_manager/metrics_service.py
tests/inference/unit_tests/core/utils/test_requests.py

In this PR, we deduce API keys previously displayed in open-text at the logging level.
Basically all occurrences of this behaviour were connected to the fact that API key is given in the `param` of REST request - and hence may be visible in error messages and access logs. Solution applied - each occurrence of code producing error logs for Roboflow backend calls is now wrapped with `api_key_safe_raise_for_status(...)` that deducts `api-key` param from URLs reported in logs.
Covered with tests and checked in docker.
We have now:
```
ERROR:inference:HTTP error encountered …
```

Deduce API keys from logs

---

inference/core/interfaces/stream/stream.py
inference/core/interfaces/udp/udp_stream.py

Double `BGR->RGB` and `RGB->BGR` conversion happen in streaming interfaces as `preprocess` for yolo models does the thing again. This is quick-fix. As some models may not do `BGR->RGB` conversion - we shall think of providing explicit information about colour mode into the model.
YOUR_ANSWER

Fix problem with BGR->RGB and RGB->BGR conversions

---

inference/models/utils.py

`ROBOFLOW_API_KEY` is used by default when `get_roboflow_model` is being called.

Update default API key parameter for get_roboflow_model function

---

docs/quickstart/http_inference.md
docs/quickstart/run_a_model.md
mkdocs.yml

This PR restructures the HTTP interface documentation to make it more user friendly and fixes some code snippets in those docs.
This change was tested by running `mkdocs serve` and opening http://localhost:8000/quickstart/http_inference/ to ensure the page rendered properly.
N/A
N/A

Update HTTP inference docs

---

inference/core/utils/image_utils.py
tests/inference/unit_tests/core/utils/test_image_utils.py

Removed a numpy validation check that turned out to be very costly for large images. Not worth the loss in performance here.
Tested locally and with auto regression tests

Speed Regression Fix - Remove Numpy Range Validation

---

inference/core/active_learning/configuration.py
inference/core/active_learning/samplers/close_to_threshold.py
inference/core/active_learning/samplers/contains_classes.py
inference/core/active_learning/samplers/number_of_detections.py
inference/core/active_learning/samplers/random.py
inference/core/active_learning/sampling.py
inference/core/constants.py
inference/core/exceptions.py
inference/core/roboflow_api.py
tests/inference/unit_tests/core/active_learning/samplers/test_close_to_threshold.py
tests/inference/unit_tests/core/active_learning/samplers/test_contains_classes.py
tests/inference/unit_tests/core/active_learning/samplers/test_number_of_detections.py
tests/inference/unit_tests/core/active_learning/samplers/test_random.py
tests/inference/unit_tests/core/active_learning/test_configuration.py

On top of previously added Active Learning capabilities, we are adding 3 new sampling strategies for Active Learning:
Sampling method to be used when one wants to sample datapoints causing certain predictions confidences for certain classes. Works for both detection and classification models - although the behaviour slightly differ.
**Degrees of freedom in configuration**
* `selected_class_names` - class names to be taken into consideration while sampling - optional (if not given - all classes can be sampled)
* `threshold` and `epsilon` - represent centre and radius for confidence range that can trigger sampling - for instance - if one is interested to get datapoints that classifier is highly confident (0.8, 1.0) -> `threshold=0.9, epsilon=0.1` - this is however limited to the outcomes of …

Introduce additional active learning sampling strategies

---

inference/core/__init__.py
inference/core/interfaces/camera/camera.py

* This will allow customization of camera resolutions via .env file for `inference.Stream` and UDP streaming.
* also fixed an upgrade message telling the user to upgrade the wrong pip package.
Do we have documentation of all the ENV variables that can be customized?

Allow setting cv2 camera capture props from .env file

---

inference/core/managers/pingback.py

- Wrapping the metrics_url so that it goes through the proxy server if enabled
- Smoke tested inference server (checked if running, made an inference)

Wrap pingback url

---

LICENSE
inference/enterprise/LICENSE.txt

Clarifies that the `inference/enterprise` directory is governed by the Roboflow Enterprise License (pursuant to a Roboflow enterprise contract).

Clarify Enterprise License

---

docker/dockerfiles/Dockerfile.onnx.jetson.4.5.0
docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1

Lowered rasterio dep in jetson dockers to accomodate lower GDAL version in Jetson JP4 images.

Lower Rasterio for JP4

---

mkdocs.yml

This PR adds a button that enables users to copy code snippets from the `inference` documentation.
Documentation.
This was tested by opening a code snippet and checking for the presence of the copy button in the top right corner of the code box.
N/A
N/A

Add copyable code snippet

---

inference/core/models/roboflow.py

Added try/except around onnx session creation. An exception will now cause the model artifacts to be cleared from the cache so that a corrupt model file doesn't continue to cause problems.
This is to mitigate an error we see in production some times where, on model init, we see 
`INVALID_PROTOBUF : Load model from /tmp/cache/<dataset>/<version>/weights.onnx failed:Protobuf parsing failed.`
To test this, I manually deleted a few lines from a valid weights file. This simulates a corruption on download and induces the same protobuf parsing error. With the change in this PR, sending a single request to a model with a corrupted weights file clears the model cache and returns 500. A subsequent request causes the artifacts to be redownloaded, and the request succeeds. 
Please delete options that …

Error Handling for Onnx Session Creation

---

docs/quickstart/docker.md
inference/enterprise/parallel/run.sh
inference/models/doctr/doctr_model.py
inference/models/gaze/gaze.py

Removed all references to legacy cache path `/cache` and replaced with `/tmp/cache`. Also removed hard coded instances of `/tmp/cache` and replaced with env var `MODEL_CACHE_DIR`.

Remove Legacy Cache Path

---

docs/quickstart/http_inference.md
inference/core/utils/image_utils.py
tests/inference/unit_tests/conftest.py
tests/inference/unit_tests/core/utils/test_image_utils.py

This PR allows `numpy` image entries to be sent as numpy arrays which have been pickled, and then the byte sequence encoded as base64. The previous numpy images only worked when the image was sent as the full body of the HTTP request, and thus could be processed as a byte stream.
Tested locally using a script and unit tests.
n/a
-   [x] Docs updated?

Accept numpy image in batch as base64 encoded string

---

docs/enterprise/active-learning/close_to_threshold_sampling.md
inference/core/active_learning/README.md
inference/core/active_learning/samplers/close_to_threshold.py
tests/inference/unit_tests/core/active_learning/samplers/test_close_to_threshold.py

As discussed with @robiscoding - default for close-to-threshold strategy should be `only_top_classes=True` for classification tasks.
YOUR_ANSWER

Change the default value for 'only_top_classes' option of close-to-threshold sampling strategy of AL

---

docs/foundation/gaze.md
examples/gaze-detection/README.md
examples/gaze-detection/gaze.py

I updated the gaze_detection example such that the API_KEY is named as ROBOFLOW_API_KEY as this is what the examples in the docs (https://inference.roboflow.com/foundation/gaze/#how-to-use-l2cs-net and https://github.com/roboflow/inference/tree/main/examples/gaze-detection) name the environment variable for the Roboflow API key
-   [ X ] Bug fix (non-breaking change which fixes an issue)
Yes, I've tried this change locally.
None
This change makes the gaze_detection example work with the docs as-is.

updated API_KEY to ROBOFLOW_API_KEY for clarity

---

development/stream_interface/inference_pipeline_demo.py
docs/enterprise/active-learning/active_learning.md
inference/core/active_learning/cache_operations.py
inference/core/active_learning/configuration.py
inference/core/active_learning/core.py
inference/core/active_learning/middlewares.py
inference/core/cache/redis.py
inference/core/env.py
inference/core/interfaces/stream/inference_pipeline.py
inference/core/interfaces/stream/sinks.py
inference/core/interfaces/stream/stream.py
inference/core/interfaces/udp/udp_stream.py
inference/enterprise/stream_management/api/entities.py
inference/enterprise/stream_management/manager/inference_pipeline_manager.py
tests/inference/unit_tests/conftest.py
tests/inference/unit_tests/core/active_learning/test_configuration.py
tests/inference/unit_tests/core/active_learning/test_core.py
tests/inference/unit_tests/core/interfaces/camera/test_video_source.py
tests/inference/unit_tests/core/interfaces/stream/test_interface_pipeline.py
tests/inference/unit_tests/core/interfaces/stream/test_sinks.py
tests/inference/unit_tests/core/interfaces/stream/test_watchdog.py
tests/inference/unit_tests/core/models/utils/test_batching.py
tests/inference/unit_tests/core/models/utils/test_keypoints.py
tests/inference/unit_tests/core/test_roboflow_api.py
tests/inference/unit_tests/enterprise/stream_management/api/test_app.py
tests/inference/unit_tests/enterprise/stream_management/manager/test_inference_pipeline_manager.py

* added config cache such that lambda inference can be faster
* added AL to new InferencePipeline() interface and to Stream Management API as parameter of pipeline init
* added dropping mechanism for queuing of AL collection requests on stream processing (as when config makes AL to collect to much - then backend is to slow for on-line registration, so we must drop datapoints not to impair performance)
YOUR_ANSWER

Add changes that eliminate mistakes spotted while initial e2e tests

---

docs/foundation/clip.md
docs/foundation/cogvlm.md
docs/foundation/doctr.md
docs/foundation/gaze.md
docs/inference_sdk/http_client.md
inference/models/clip/clip_model.py
inference/models/cogvlm/cogvlm.py
inference/models/doctr/doctr_model.py
inference/models/gaze/gaze.py
inference/models/sam/segment_anything.py
inference_sdk/http/client.py
inference_sdk/http/errors.py
inference_sdk/http/utils/requests.py
tests/inference_sdk/unit_tests/http/test_client.py
tests/inference_sdk/unit_tests/http/test_entities.py
tests/inference_sdk/unit_tests/http/utils/test_encoding.py
tests/inference_sdk/unit_tests/http/utils/test_loaders.py
tests/inference_sdk/unit_tests/http/utils/test_postprocessing.py
tests/inference_sdk/unit_tests/http/utils/test_preprocessing.py
tests/inference_sdk/unit_tests/http/utils/test_requests.py

New client methods making it possible to call core models (apart from SAM)
New API:
```python
from inference_sdk import InferenceHTTPClient
LOCALHOST_CLIENT = InferenceHTTPClient(
api_url="http://127.0.0.1:9001",
api_key=API_KEYS["MY_WORKSPACE_API_KEY"],
)
LOCALHOST_CLIENT.ocr_image("https://jeroen.github.io/images/testocr.png")
LOCALHOST_CLIENT.ocr_image(["https://jeroen.github.io/images/testocr.png"]*2)
LOCALHOST_CLIENT.detect_gazes(
"https://t3.ftcdn.net/jpg/02/43/12/34/360_F_243123463_zTooub557xEWABDLk0jJklDyLSGl2jrr.jpg"
)
LOCALHOST_CLIENT.detect_gazes(
["https://t3.ftcdn.net/jpg/02/43/12/34/360_F_243123463_zTooub557xEWABDLk0jJklDyLSGl2jrr.jpg"] * 3
)
LOCALHOST_CLIENT.get_clip_image_embeddings(
inference_input="https://t3.ftcdn.net/jpg/02/43/12/34/360_F_243123463_zTooub557xEWABDLk0jJk …
```

Extend inference SDK with client for (almost all) core models

---

inference/core/interfaces/stream/inference_pipeline.py
inference/core/interfaces/stream/stream.py
inference/core/models/roboflow.py
inference/core/registries/roboflow.py
inference/core/roboflow_api.py
inference/models/utils.py
tests/inference/unit_tests/core/registries/test_roboflow.py
tests/inference/unit_tests/core/test_roboflow_api.py

Updated api logic so that an api key is not required by `inference` methods. Instead, when an api key is required by a Roboflow API but not provided, an exception will be raised. This accommodates the new public coco models that do not require an api key.
Local dev scripts and automated GH actions

API Key Not Required by Methods

---

inference/__init__.py
inference/core/interfaces/stream/inference_pipeline.py
inference/core/managers/active_learning.py
inference/enterprise/stream_management/api/entities.py
inference/enterprise/stream_management/manager/inference_pipeline_manager.py
inference_sdk/http/client.py
tests/inference/unit_tests/enterprise/stream_management/api/test_app.py
tests/inference/unit_tests/enterprise/stream_management/api/test_stream_manager_client.py
tests/inference/unit_tests/enterprise/stream_management/manager/test_inference_pipeline_manager.py
tests/inference_sdk/unit_tests/http/test_client.py

* Disable active learning each time api key is not used
* Fix malformed payload in clip compare
* Fix double invocation of AL registration in AL middleware
YOUR_ANSWER

Fix problem with keyless access and Active Learning

---

inference/core/interfaces/http/http_api.py
inference/core/models/keypoints_detection_base.py
inference/core/nms.py

Initially I misunderstood the outputs from pose model. For example, in case of YOLOv8:
* model outputs `[bs, [bbox x 4, cls_confidence x num_classes, (kp_x, kp_y, visibility) * keypoints_number], 8400 (defined at export level]` - visibility is only defined if data.yml defines it, but **we assume it's always the case**
* we change that into `[bs, 8400, [bbox x 4, max_class_confidence, cls_confidence x num_classes, (kp_x, kp_y, visibility) * keypoints_number]]`
* then, while NMS, we do `[bs, qualified_boxes, [bbox x 4, max_class_confidence, max_class_confidence, winning_class_id, (kp_x, kp_y, visibility) * keypoints_number]]`
* effectively, in the post-processing we have
* bbox coordinates at `predictions[batch][detection][0:4]`
* bbox confidence at `predictions[batch][detection][4] or …

Apply fix for post-processing of keypoints

---

docs/inference_sdk/http_client.md
inference/core/entities/requests/inference.py
inference/core/interfaces/http/http_api.py
inference/core/managers/active_learning.py
inference_sdk/http/entities.py
tests/inference_sdk/unit_tests/http/test_client.py
tests/inference_sdk/unit_tests/http/test_entities.py

New feature letting us define `disable_active_learning` flag for a single request.
YOUR_ANSWER

Add API parameter preventing AL feature to capture data for single request

---

inference/core/models/roboflow.py
inference/core/version.py
tests/inference/models_predictions_tests/test_vit.py
tests/inference/models_predictions_tests/test_yolov8.py
tests/inference/unit_tests/core/models/test_roboflow.py

I introduced bug with parsing class names if only `environment.json` file is available and no classes in API response.
Previously - sorting keys was applied - but keys are strings, so that lead in: `["1", "10", "2", "3"]` being the sort order 🤦 
YOUR_ANSWER

Fix problem with class names sorting

---

.gitignore
docs/index.md
docs/styles.css

Removed TOC from homepage and added a couple buttons to help drive users to the top nav links / content.

Remove TOC from Docs Homepage

---

docs/quickstart/explore_models.md
docs/quickstart/run_a_model.md
docs/quickstart/what_is_inference.md
docs/using_inference/native_python_api.md

Every URL of this type "https://storage.googleapis.com/com-roboflow-marketing/inference/people-walking.jpg" has been updated to a shorter URL that is also faster as the image is cached: https://media.roboflow.com/inference/people-walking.jpg
-   [ X ] This change requires a documentation update
Yes, https://media.roboflow.com/inference/people-walking.jpg loads
Yes, four markdowns with the prior link were updated.

updated links to cached URL

---

README.md
docs/quickstart/create_a_custom_inference_pipeline_sink.md
docs/quickstart/explore_models.md
docs/quickstart/run_a_model.md
docs/using_inference/http_api.md
docs/using_inference/native_python_api.md

This PR replaces `from_roboflow` with `from_inference` in our docs.
Open up any of the changed pages to ensure `from_inference` is used as the data loader in a guide instead of `from_roboflow`.
N/A
N/A

Use `from_inference` data loader in docs

---

inference/core/roboflow_api.py

Added trailing slash to the base api call to get workspace which is required when using the license server.

Trailing `/` for Base API Call

---

development/stream_interface/inference_pipeline_on_camera.py
inference/core/interfaces/stream/entities.py
inference/core/interfaces/stream/inference_pipeline.py
inference/core/interfaces/stream/sinks.py
tests/inference/unit_tests/core/interfaces/stream/test_interface_pipeline.py
tests/inference/unit_tests/core/interfaces/stream/test_sinks.py

In this PR we make it possible for `InferencePipeline` to work with stubs (`model/0`) and with Roboflow models other than object-detection ones. We adjusted sinks to work with other type of output.
YOUR_ANSWER
-   [x] Docs updated? Partially (at the docstring level) - @capjamesg if u could post something in high-level docs that would be great.

Add support for stubs in InferencePipeline

---

mkdocs.yml

Instant nav is make docs SPA and cookbook side doesn't use that side yet so turning off is make sure page load properly

fix: 🐞 turn off instant page for load to cookbook page properly

---

docs/using_inference/http_api.md

Update visualize results documentation, using `https://detect.roboflow.com`, `sv.ImageSink`, and fixing `from_inference` error

modify visualize results example

---

docs/foundation/grounding_dino.md
docs/foundation/yolo_world.md
mkdocs.yml

This PR adds instructions on how to use YOLO-World to the Inference documentation.
You can test this project by navigating to the Models tab, click "YOLO World", and ensure the page opens properly.
N/A
N/A

Add YOLO-World model documentation

---

README.md
docs/quickstart/configure_api_key.md
docs/quickstart/explore_models.md
docs/quickstart/run_a_model.md
docs/quickstart/what_is_inference.md
docs/using_inference/native_python_api.md
examples/notebooks/quickstart.ipynb
inference/__init__.py
inference/core/interfaces/stream/inference_pipeline.py
inference/core/interfaces/stream/stream.py
inference/core/interfaces/udp/udp_stream.py
inference/core/utils/function.py
inference/landing/src/app/components/Examples.tsx
inference/models/utils.py
inference_cli/lib/benchmark/python_package_speed.py

Changed name of `get_roboflow_model` to `get_model` and added deprecation warning.

Deprecate `get_roboflow_model`

---

docs/inference_helpers/inference_sdk.md
inference/enterprise/workflows/complier/steps_executors/models.py
inference_sdk/http/entities.py
tests/inference_sdk/unit_tests/http/test_client.py
tests/inference_sdk/unit_tests/http/test_entities.py

adds source and source_info parameters to `InferenceConfiguration` and pass `workflow-execution` as source on inference requests made by the workflow execution engine so the requests can be id'd as being part of workflow execution
This enables model monitoring to filtr / group by which inference request were made via workflow execution
NOT YET!

set source on workflow execution inference requests

---

docker/dockerfiles/Dockerfile.onnx.gpu.slim

Was getting missing package for inference_sdk for  some reason
Locally
Makes it less slim! Should probably test if inference_cli deps are necessary

Add in requirements for sdk

---

inference/core/managers/base.py
inference/core/managers/decorators/fixed_size_cache.py
inference/core/version.py

We had a problem with the model manager loading dozens of model and lambda environments were running out of memory after a while. This change fixes issue with memory management. What was happening - old version of function for reference:
```python
def add_model(
self, model_id: str, api_key: str, model_id_alias: Optional[str] = None
):
"""Adds a model to the manager and evicts the least recently used if the cache is full.
Args:
model_id (str): The identifier of the model.
model (Model): The model instance.
"""
queue_id = self._resolve_queue_id(
model_id=model_id, model_id_alias=model_id_alias
)
if model_id in self:
self._key_queue.remove(queue_id)
self._key_queue.append(queue_id)
return
should_pop = len(self) == self.max_size
if should_pop:
to_remove_model_id = self._key_queue.popleft() …
```

Resolve memory management issue causing ti many models being loaded in lambda

---

inference/core/version.py
inference/enterprise/workflows/README.md
inference/enterprise/workflows/complier/steps_executors/auxiliary.py
inference/enterprise/workflows/complier/steps_executors/models.py
inference/enterprise/workflows/entities/steps.py
tests/inference/unit_tests/enterprise/workflows/compiler/steps_executors/test_auxiliary.py
tests/inference/unit_tests/enterprise/workflows/compiler/steps_executors/test_models.py

Legacy inference endpoint does not support filtering by class names - fixed.
Also - added possibility to filter detections by pre- / post- fix and substring in `DetectionFilter` and make the same for string fields in `Condition` step (as a requested feature)
YOUR_ANSWER

Fix inconsistency in class filtering for workflows

---

requirements/requirements.cli.txt

Issue: #299 
Added `aiohttp` and `backoff` to the `requirements.cli.txt` file. This ensures that these dependencies are installed alongside `inference_cli`, addressing the root cause of the startup failures.
- `aiohttp` and `backoff` are direct dependencies of the `inference_sdk` used by our CLI tool for handling HTTP requests and implementing retry logic, respectively.
- The absence of these packages in the `requirements.cli.txt` file led to an incomplete environment setup for users, resulting in runtime errors.
- By explicitly listing these dependencies, i ensure that the necessary packages are present in the environment, thereby preventing `ModuleNotFoundError` issues during runtime.

Updated Requirements.cli.txt

---

.github/workflows/publish.pypi.yml

We've unfortunate symlink creation command in GHA to build and push wheels - as there is one generic setup.py to resolve dev dependencies in repo root. Script for creating wheels, up to my knowledge, should not require that.
YOUR_ANSWER
* Automated tests running in GHA CI
* manual verification of command `make create_wheels` without `setup.py` being linked prior to execution
N/A
-   [ ] Docs updated? What were the changes: (N/A)

Fix wheels creation CI

---

inference/core/version.py
inference/enterprise/workflows/complier/steps_executors/models.py

Tupling with @PawelPeczek-Roboflow, we realized that #293 needed a few additional changes to make the source parameter be used correctly for hosted inference in addition to local inference.
Now it works and the correct source shows up in core api logs
Tested on staging by running a curl command to the hosted workflow

track source for remote execution flows

---

docs/fine-tuned/yolonas.md
docs/fine-tuned/yolov5.md
docs/fine-tuned/yolov7.md
docs/fine-tuned/yolov8.md
docs/fine-tuned/yolov9.md
docs/index.md
docs/quickstart/explore_models.md

This PR adds deep links to our interactive deployment widget (i.e. https://roboflow.github.io/deploy-setup-widget/results.html#Fine-Tuned/Object%20Detection) to fine-tuned model pages and fixes several broken links.
- Documentation update
This change can be tested by running the documentation with `mkdocs serve` and checking that the changed links work.
N/A
N/A

Add deep links to deployment widget, fix broken links

---

inference/core/active_learning/core.py
inference/core/active_learning/middlewares.py
inference/core/managers/active_learning.py
inference/core/roboflow_api.py
tests/inference/unit_tests/core/active_learning/test_core.py
tests/inference/unit_tests/core/active_learning/test_middlewares.py

In order to display inference images in the model monitoring dashboard, we need to add the inference id to the images created from inference requests via the AL workflow
Relates to: https://github.com/roboflow/roboflow/pull/3080
- Test case for staging: inference_ids are sent as part of batch request (e2e test case will be tested once https://github.com/roboflow/roboflow/pull/3080 is merged)

Add inference_id to batches created by AL

---

inference/core/version.py
inference_sdk/http/utils/loaders.py

Inference_sdk will forcibly encode image as jpeg (and then convert to base64 string) before sending request to inference server, this is not necessary and not expected.
We have the requirement from Duolingo that they want to keep the original image quality, but jpeg encoding will degrade image quality and affect the inference results.

Skip encode image as jpeg if no-resize is specified

---

inference/core/managers/base.py
inference/core/managers/decorators/base.py
inference/core/managers/pingback.py

The model monitoring feature only works if a global API key is provided when the server is started.  This change modifies the model manager to set a fallback api for the pingback when it sees a API key used for inference requests so we can send model monitoring data by default without requiring a separate / global api key to be set
locally running cpu docker container, observing debug logs and sending inference requests via postman
n/a
n/a

add api key fallback for model monitoring

---

requirements/requirements.cogvlm.txt
requirements/requirements.groundingdino.txt

As reported in one of our issues (https://github.com/roboflow/inference/issues/355) and as suggested in discussions in `transformers` issues - we shall restrict versions of `transformers` we use to avoid faulty release. The problem is solved in one of newer versions, but defensively I propose to just downgrade max version of transformers a bit.
* run of CogVLM on new build yo ensure model works e2e

Downgrade transformers to avoid faulty release of that package

---

inference_cli/main.py

Taking a shot at https://github.com/roboflow/inference/issues/338. It's a little tricky to test locally, since there's nothing I could find that tracks the version locally. Therefore, looking for package metadata can cause issues. When I tested the `version()` function with the latest release it returned the version correctly, so I opted to just catch the exception and let the user know it's a local install.
Try running `inference --version`. I also tested the `version()` function on an actual release and it …

Add --version option to CLI

---

inference/core/managers/decorators/base.py
tests/inference/unit_tests/core/managers/test_pingback_num_errors.py

There was a problem with init pingback on a model manager decorator because pingback was not being set on the outer wrapper any more.
This fixes the metrics middleware attr error (num_errors set on wrong model manager).
Unit tests
No

Fix metrics middleware attr error (num_errors set on wrong model manager)

---

docs/fine-tuned/yolonas.md
docs/fine-tuned/yolov5.md
docs/fine-tuned/yolov7.md
docs/fine-tuned/yolov8.md
docs/fine-tuned/yolov9.md
docs/foundation/yolo_world.md
docs/index.md
docs/models/from_local_weights.md
docs/quickstart/aliases.md
docs/quickstart/explore_models.md
docs/quickstart/inference_101.md
docs/quickstart/licensing.md
docs/quickstart/load_from_universe.md
docs/quickstart/roboflow_ecosystem.md
docs/quickstart/run_a_model.md
docs/quickstart/run_model_over_udp.md
docs/using_inference/native_python_api.md
mkdocs.yml

Pages on the left now have a basic section.
The goal is to answer questions:
* What is inference in the context of Roboflow (+ what other tools are available)
* What kind of models can I run?
* How can I get model_ids?
* I have weights already - what do I do?
`mkdocs serve`
1. Docs need to be deployed.
2. It assumes the aliases for keypoint detection are available.
-   [x] Docs updated.

Inference Docs Overhaul

---

docs/quickstart/run_model_on_rtsp_webcam.md
inference/core/interfaces/camera/entities.py

The `source_id` element of `VideoFrame` is not documented and is a useful property when inferring on multiple streams with `SinkMode.SEQUENTIAL`.
w/ @nathan-marraccini
Documentation only
Documentation will need to be deployed
-   [x] Docs updated? What were the changes: docs only

Document source_id parameter of VideoFrame

---

docs/inference_helpers/inference_sdk.md
inference_sdk/http/client.py

- update workflow specification URL to non-broken one
- add clarification in example on run_workflow params
- make invalid model id error more descriptive
Just docs and error message text.
Can go out with next release, not urgent.

Fix workflows specification URL and other docs updates

---

examples/paligemma/paligemma_client.py
inference/models/__init__.py
inference/models/paligemma/__init__.py
inference/models/paligemma/paligemma.py

Fix IMAGE_PATH in client
local
no

Bugfix paligemma-client

---

README.md

This PR adds a link to the Roboflow licensing page, which documents how Inference is licensed.
Documentation update.
N/A
N/A
N/A

Add link to Roboflow licensing

---

docker/dockerfiles/Dockerfile.onnx.jetson.4.5.0
docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1

Build for Jetson Jetpack 4.5 was broken - see details [here](https://github.com/roboflow/inference/actions/runs/9079290720)
Fixing build, but I have no way to verify integration tests.
Discussion about sunset of that build: https://github.com/roboflow/inference/issues/394
* test build succeeds 
* no way to verify integration tests

Fix/release 0.10.0 Jetson 4.5 build

---

inference/core/version.py
inference/core/workflows/core_steps/flow_control/condition.py
inference/core/workflows/core_steps/models/foundation/clip_comparison.py
inference/core/workflows/core_steps/models/foundation/lmm.py
inference/core/workflows/core_steps/models/foundation/lmm_classifier.py
inference/core/workflows/core_steps/models/foundation/ocr.py
inference/core/workflows/core_steps/models/foundation/yolo_world.py
inference/core/workflows/core_steps/models/roboflow/instance_segmentation.py
inference/core/workflows/core_steps/models/roboflow/keypoint_detection.py
inference/core/workflows/core_steps/models/roboflow/multi_class_classification.py
inference/core/workflows/core_steps/models/roboflow/multi_label_classification.py
inference/core/workflows/core_steps/models/roboflow/object_detection.py
inference/core/workflows/core_steps/models/third_party/barcode_detection.py
inference/core/workflows/core_steps/models/third_party/qr_code_detection.py
inference/core/workflows/core_steps/sinks/active_learning/data_collector.py
inference/core/workflows/core_steps/transformations/absolute_static_crop.py
inference/core/workflows/core_steps/transformations/crop.py
inference/core/workflows/core_steps/transformations/relative_static_crop.py
inference/core/workflows/execution_engine/executor/core.py
inference/core/workflows/execution_engine/executor/output_constructor.py
requirements/_requirements.txt
tests/workflows/unit_tests/execution_engine/executor/test_output_constructor.py

This fixes a bug where if you add one of the input parameters as an output the default value doesn't make its way through. This is useful when wanting to display input values (like a hard-codes string) in your rendering code.
We implemented this to use in @josephofiowa's demo last week & have now tested it several times end to end with new workflows (installing `inference` from this branch).
On top of that, we want to create `0.11.1` release, so:
* checked that CI still 🟢 
* Conducted tests on target platforms:
* JETSON 4.5: image builds
* JETSON 4.6.1 tests 🟢  https://github.com/roboflow/inference/actions/runs/9203845879
* JETSON 5.1.1 - local build 🟢 
* NVIDIA GPU tests 🟢 …

Pass Inputs to Outputs when Wired

---

docs/foundation/paligemma.md
docs/quickstart/licensing.md
mkdocs.yml

This PR:
1. Adds PaliGemma reference documentation
2. Re-orders the Table of Contents so that foundation models are more prominent
3. Updates the licensing page to link to the canonical Roboflow licensing page
Documentation updates
You can test this PR by opening the documentation locally and browsing the new PaliGemma page and ensuring the table of contents appears correctly.
N/A
N/A

Add PaliGemma documentation, update table of contents

---

inference/core/interfaces/http/http_api.py

Add http get support for legacy model inference, so users can request: 
https://detect.roboflow.com/model_name/version_id?api_key=1xxx&confidence=40&overlap=30&format=image&labels=on&stroke=2&image=xxx
Tested locally

Add http get support for legacy model inference

---

inference/core/models/roboflow.py
inference/core/utils/postprocess.py
inference/models/yolov10/yolov10_object_detection.py

1. NMS is not needed for YOLOv10. This PR removes NMS for the postprocessing in YOLOv10
2. The `color` used in LetterBox is `(114,114,114)` in ultralytics. This PR change the `color` to `(114,114,114)` to make LetterBox consistent with it.
3. The onnx models of YOLOv10 in Roboflow inference may be incorrectly exported. This PR hopes replace the onnx models of YOLOv10 with the follows: [yolov10n.onnx](https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10n.onnx), [yolov10s.onnx](https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10s.onnx), [yolov10m.onnx](https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10m.onnx), [yolov10b.onnx](https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10b.onnx), …

fix letterbox and postprocess for YOLOv10

---

docs/workflows/create_and_run.md
inference/core/workflows/core_steps/models/foundation/yolo_world.py

The "Supported Blocks" link https://inference.roboflow.com/workflows/supported_blocks/ in page https://inference.roboflow.com/workflows/create_and_run/#next-steps is dead.
This PR changes it to https://inference.roboflow.com/workflows/blocks/

Fix dead supported blocks link

---

docs/quickstart/run_keypoint_detection.md
inference/core/workflows/core_steps/models/foundation/yolo_world.py

Removed the banner suggesting to install `supervision==0.21.0.rc3` release candidate, as `0.21.0` is being released right now.
⚠️ I failed to serve the docs, with `mkdocs` requiring `mkdocstrings`, which wasn't found even when installed.
Removed 1 banner.

Docs: Remove banner saying Sv Keypoint annotators are experimental

---

inference/core/interfaces/camera/video_source.py
inference/core/interfaces/stream/sinks.py
inference/core/interfaces/stream/stream.py
inference/core/interfaces/stream/watchdog.py
inference/core/interfaces/udp/udp_stream.py

When running inference pipeline log is spammed with deprecation warnings:
```
SupervisionWarnings: __call__ is deprecated: `FPSMonitor.__call__` is deprecated and will be removed in `supervision-0.22.0`. Use `FPSMonitor.fps` instead.
```
This is quality of life change.
```python3
from inference import InferencePipeline
from inference.core.interfaces.stream.sinks import render_boxes
pipeline = InferencePipeline.init(
model_id="yolov8n-640",
video_reference=0,
on_prediction=render_boxes,
)
pipeline.start()
pipeline.join()
```
N/A
N/A

Remove sv.FPSMonitor deprecation warnings

---

requirements/_requirements.txt

Bump the max boto3 version to avoid pip trying to install many versions before finding one that works.
It is reasonably safe, boto3 is very stable.
🟢 CI pass 🟢

Loose boto3 requirements

---

docker/dockerfiles/Dockerfile.paligemma

There was some weird bug (at least on my machine) where multiple subsequent calls to paligemma would degrade performance, I tracked it down to mismatch between the pytorch installed cudnn and the system one. Pytorch says "oh don't even bother having yoru own cudnn", but we need it for onnx stuff. So we uninstall the pytorch installed cudnn.
I think the error came in the flash attention implementation or some improperly intialized tensor or something
Locally
Depends on system cuda maybe

Fix weird paligemma generation

---

inference/core/models/stubs.py
inference/core/utils/image_utils.py
inference/core/utils/visualisation.py

Use cv2.imencode to convert image into buffer, avoid converting between BGR/RGB manually.
```python
import cv2 as cv
from inference.core.utils.image_utils import load_image_from_encoded_bytes, np_image_to_base64
x = cv.imread("/path/to/my/image.jpg")
y = np_image_to_base64(x)  # should convert to RGB first - cv2.cvtColor(x, cv2.COLOR_RGB2BGR)
z = load_image_from_encoded_bytes(y)
cv.imshow("original image", x)
cv.waitKey(0)
cv.imshow("loaded", z)  # colors inverted
cv.waitKey(0)
cv.destroyAllWindows()
```
Also tested through SDK:
```python
import base64
import cv2 as cv
import numpy as np
from inference.core.utils.image_utils import load_image_from_encoded_bytes, np_image_to_base64
from …
```

replace usage of np_image_to_base64 with encode_image_to_jpeg_bytes

---

docs/quickstart/compatability_matrix.md
docs/quickstart/devices.md
inference/core/version.py
requirements/requirements.sdk.http.txt
requirements/requirements.test.integration.txt

Fix broken link to `quickstart/docker`
N/A
N/A

fix Docker Getting Started link in docs returns 404

---

docs/inference_helpers/inference_sdk.md
inference/core/interfaces/http/http_api.py
inference_sdk/http/client.py
tests/inference_sdk/unit_tests/http/test_client.py

Adds new format option for v0 http request, `image_and_json`. This will create the image visualization, and return it with the predictions json. Also updates inference_sdk to output the image in the desired format (pillow, numpy, etc).
Adding this as a separate initiative to the ongoing workflows feature improvements because it is relatively small update.
Tested locally w/ inference_sdk, and on staging hosted API.
- hosted API

Add support for image_and_json format

---

docs/quickstart/docker_configuration_options.md
inference/core/env.py

I'm working on making the core app be able to connect to and communicate with self-hosted inference servers. We have CORS off by default which means you can't communicate with the server from a web browser.
This seems like a bad default because it prevents you from hitting it from any web service you're building. We have it on already for our Hosted API via the lambda config.
With a self-hosted server locally & via ngrok connecting with my web dev environment.
No

Allow CORS by default

---

inference/enterprise/device_manager/command_handler.py

There was an issue when installing [inference](https://github.com/roboflow/inference) on python version 3.9. Since, python 3.9 doesn't support match statement
https://github.com/roboflow/inference/blob/d6cb89de97438187940bc18440109b78a55960bd/inference/enterprise/device_manager/command_handler.py#L41
> inference package requires Python>=3.8,<=3.11. 
**Specifications**:
```sh
Python 3.9.19
```
**Reproduce**:
```bash
pip install inference
```
The installation may have completed successfully, but you will encounter errors when package compiled:
- Do we need to validate the Python version?
```py
def validate_python_version(cls, values: Dict) -> Dict:
"""Validate valid python version."""
if sys.version_info < (3, 8):
raise ValueError( …
```

fix: replace match statement with if-else for Python 3.9 compatibility

---

inference/core/active_learning/configuration.py

Currently, when you start InferencePipeline offline, if `active_learning_enabled` is not set to false, there is a pretty ugly error and the application doesn't start:
---------
With this change, you get a nice warning letting you know what's going on, and the application still starts:
n/a
-   not needed

InferencePipeline: Gracefully handle connection failure when fetching Active Learning config

---

inference_cli/lib/cloud_adapter.py

The `sky` package is very slow to import and is required only in some cases.
You can paste these traces [here](http://www.softwareishard.com/har/viewer/) to check the results. It is almost 30% of the import time.
[trace-before.txt](https://github.com/user-attachments/files/16026809/trace-before.txt)
[trace-after.txt](https://github.com/user-attachments/files/16026808/trace-after.txt)

Import `sky` only when required because it is slow

---

inference/core/workflows/core_steps/models/foundation/lmm.py
inference_cli/lib/cloud_adapter.py
tests/workflows/unit_tests/core_steps/models/foundation/test_lmm.py

Changing default LLM for gpt-4 into gpt-4o, as `gpt-4-vision-preview` is no longer operational.
tested e2e at local instance of inference

Change GPT-4 default model into GPT-4o

---

inference/core/models/object_detection_base.py
inference/core/utils/postprocess.py
inference/core/version.py

Fix - infer_shape was passed as (height, width), and used both as (height, width) and (width, height) in `undo_image_padding_for_predicted_boxes`. Add correction where it was used as (width, height).
Model had training images shape width: 1000 and height: 1333
Image had width: 720, height: 1280
Bug was not observable after adding fix.
```python3
from typing import List
import cv2 as cv
import supervision as sv
from inference import get_model
from inference.core.entities.responses.inference import ObjectDetectionInferenceResponse
model = get_model(model_id="<custom model ID that had training widthxheight as 1000x1333>")
img_path = "/path/to/image/width_720_height_1280.jpg"
results: …
```

Fix undo image padding for predicted boxes

---

inference/core/entities/requests/inference.py

- There's an issue with the inference_id changing for the same request between when the inference is resulted and when the ActiveLearning middleware runs and creates the batch. This is resulting in images created by AL having an inferenceId that doesn't map to an inference in our model monitoring database. This changes ensures that we reuse the same id if it exists
- Need to check whether this interferes with the parallel request processing
---
- To see …

Reuse existing ids

---

examples/run_perspective_correction.py
inference/core/workflows/core_steps/transformations/perspective_correction.py

Extend perspective correction block to allow user to also warp the image into new perspective
VSCode run config:
```json
{  /* perspective correction */
"name": "perspective correction",
"type": "debugpy",
"request": "launch",
"program": "${workspaceFolder}/examples/run_perspective_correction.py",
"console": "integratedTerminal",
"args": [
"--source-path",
"/path/to/image.src",
"--model-id",
"chess-pieces-and-chess-board-instance-segmentation/6",
"--zones-from-class-name", "board",
"--extend-perspective-polygon-by-detections-anchor", "",
"--warp-image"
],
"env": {
"ROBOFLOW_API_KEY": "<secret>",
"LOG_LEVEL": "DEBUG",
"DISABLE_VERSION_CHECK": "True"
},
"justMyCode": false,
},
``` …

Extend perspective correction to warp image

---

inference/models/__init__.py

Do not try to import disabled models. It improve import time a lot. Trying to reduce cold start time.
I'm not considering paligemma and florence2 core models here, they're always imported (but in most cases we don't install them).
CI pass

Follow config to import core models

---

inference/core/workflows/core_steps/formatters/property_definition.py
inference/core/workflows/core_steps/fusion/detections_classes_replacement.py
inference/core/workflows/core_steps/loader.py
tests/workflows/integration_tests/execution/test_workflows_with_property_extraction.py
tests/workflows/unit_tests/core_steps/formatters/test_property_extraction.py

Renames `PropertyExtraction` block to `PropertyDefinition`, leaving `PropertyExtraction` as alias
new block rename 
n/a 
n/a

rename PropertyExtraction -> PropertyDefinition

---

.github/workflows/docker.cpu.parallel.yml
.github/workflows/docker.cpu.slim.yml
.github/workflows/docker.cpu.yml
.github/workflows/docker.device_manager.yml
.github/workflows/docker.gpu.parallel.yml
.github/workflows/docker.gpu.slim.yml
.github/workflows/docker.gpu.udp.yml
.github/workflows/docker.gpu.yml
.github/workflows/docker.jetson.4.5.0.yml
.github/workflows/docker.jetson.4.6.1.yml
.github/workflows/docker.jetson.5.1.1.yml
.github/workflows/docker.stream_management_api.yml
.github/workflows/docker.stream_manager.cpu.yml
.github/workflows/docker.stream_manager.gpu.yml
.github/workflows/docker.stream_manager.jetson.5.1.1.yml
.github/workflows/docker.trt.yml

All docker builds on merge to main (`push` event) were failing on `build_and_push` step with error:
```
Input does not meet YAML 1.2 "Core Schema" specification: push Support boolean input list: `true \| True \| TRUE \| false \| False \| FALSE`
```
that was due to:
```
name: Build and Push
uses: docker/build-push-action@v4
with:
push: ${{ github.event_name == 'release' || github.event.inputs.force_push }}
^^^ this gets substituted with empty str and we have false || '' -> '' which is string, not bool as expected
```
Fixed that by checking the value with `==`. What is important - tested against literal `true` in my private repo and it does not work, in GHA, when taking bool input we must assume string - hence `== 'true'`. 
-   [x] Bug fix …

Fix broken type coercion in Github Actions

---

inference/core/interfaces/stream/sinks.py
inference_cli/lib/infer_adapter.py
pytest.ini
tests/workflows/integration_tests/execution/stub_plugins/dimensionality_manipulation_plugin/tile_detections_batch.py
tests/workflows/integration_tests/execution/stub_plugins/dimensionality_manipulation_plugin/tile_detections_non_batch.py

Make pytest fail with supervision warnings to be able to fix them faster.
Tests are broken because of supervision release, #526 have many fixes to support it properly.
CI pass

Fail tests on supervision warnings

---

inference/core/nms.py
inference/models/yolo_world/yolo_world.py
tests/inference/models_predictions_tests/test_yolo_world.py
tests/inference/models_predictions_tests/test_yolonas.py
tests/inference/models_predictions_tests/test_yolov10.py

Bug report: https://github.com/roboflow/inference/issues/529
There was a bug in NMS function causing very strange errors:
Old:
```
np_conf_mask = (np_image_pred[:, 4] >= conf_thresh).squeeze()
```
when np_image_pred was of size (1, n) - which represents one box for image - `squeeze()` were pushing `np.array([True]) -> True` and leaving `(k, n)` -> lists of k-elements booleans.
Now, let's take a look what happens if we run this:
```
np.array([1, 2, 3])[True]
>>> array([[1, 2, 3]])  # dimension expand!
```
so `np_conf_mask` used in `np_image_pred = np_image_pred[np_conf_mask]` were causing dim expansion, instead of 
selecting one or none elements.
Then - expanded `np_conf_mask` had size `(1, 1, n)` in problematic case - and line `cls_confs = np_image_pred[:, 5 : num_classes + 5]` selecting …

Fix broken NMS function

---

inference/core/workflows/core_steps/visualizations/base.py
inference/core/workflows/core_steps/visualizations/base_colorable.py
inference/core/workflows/core_steps/visualizations/blur.py
inference/core/workflows/core_steps/visualizations/bounding_box.py
inference/core/workflows/core_steps/visualizations/circle.py
inference/core/workflows/core_steps/visualizations/color.py
inference/core/workflows/core_steps/visualizations/corner.py
inference/core/workflows/core_steps/visualizations/crop.py
inference/core/workflows/core_steps/visualizations/dot.py
inference/core/workflows/core_steps/visualizations/ellipse.py
inference/core/workflows/core_steps/visualizations/halo.py
inference/core/workflows/core_steps/visualizations/label.py
inference/core/workflows/core_steps/visualizations/mask.py
inference/core/workflows/core_steps/visualizations/pixelate.py
inference/core/workflows/core_steps/visualizations/polygon.py
inference/core/workflows/core_steps/visualizations/triangle.py

Refactors the inheritance of the blocks introduced in #533 so that blocks that don't accept color palettes can benefit from the standardization of the other visualizer inputs (image, predictions, copy).
-   [x] Refactor - does not change user-facing functionality
Tests still pass; validated visually that the outputs remain as expected with my Visualizer Kitchen Sink workflow.
No
- No user-facing changes, just code structure cleanup

Refactor Visualization Workflow Block Inheritance

---

inference/usage_tracking/collector.py

When usage cannot be sent the payload is enqueued back, there is no need to display warning message when this happens.
CI tests are passing
N/A
N/A

Do not log warning when usage payload is put back into the queue

---

inference/usage_tracking/collector.py

Some environments do not have async event loop initialized, ensure usage_collector does not fail when creating _async_lock due to problems when obtaining async loop
CI tests
N/A
N/A

Initialize usage_collector._async_lock only if async look can be obtained

---

inference/core/roboflow_api.py
inference/core/utils/file_system.py
tests/inference/unit_tests/core/test_roboflow_api.py

Caches workflow specification for offline use. If a ConnectionError occurs when fetching the specification, then return the cached response.
Tested locally and with unit tests.
normal release.
-   n/a

Cache workflow specification for offline use

---

CODEOWNERS

This PR adds myself as a codeowner to the `docs` directory per the instructions on https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners. This will grant permission for me to merge PRs that change exclusively the `docs` directory.
The syntax follows the official GitHub documentation linked above.
N/A
N/A

Add @capjamesg to CODEOWNERS

---

inference/core/workflows/core_steps/sinks/roboflow/custom_metadata/v1.py
tests/workflows/unit_tests/core_steps/sinks/roboflow/test_roboflow_custom_metadata.py

Fixed a regression in the Custom Metadata block where only the first character of the expected `field_value` was being written as metadata.
Tested locally using a custom Docker image. Passed all unit and integration tests. Confirmed that the change in the PR fixes the issue.
N/A
N/A

Fixed a Regression in the Custom Metadata Block

---

inference/core/version.py
inference/core/workflows/core_steps/common/utils.py
inference/core/workflows/execution_engine/v1/executor/utils.py
inference_sdk/http/utils/executors.py
tests/inference_sdk/unit_tests/http/utils/test_executors.py

There was a bug due to the fact that submission into ThreadPoolExecutor does not maintain features order.
* checked manually
* e2e tests on the platform

Fix bug with execution order in workflows

---

inference/core/interfaces/camera/entities.py
inference/core/interfaces/camera/video_source.py
inference/core/interfaces/stream/inference_pipeline.py
inference/core/interfaces/stream/model_handlers/workflows.py
inference/core/workflows/execution_engine/entities/base.py
inference/core/workflows/execution_engine/entities/types.py
inference/core/workflows/execution_engine/v1/core.py
inference/core/workflows/execution_engine/v1/executor/runtime_input_assembler.py
tests/inference/hosted_platform_tests/test_workflows.py
tests/inference/integration_tests/test_workflow_endpoints.py
tests/inference/unit_tests/core/interfaces/camera/test_video_source.py
tests/workflows/integration_tests/execution/stub_plugins/plugin_handling_video_metadata/__init__.py
tests/workflows/integration_tests/execution/test_workflow_with_video_metadata_processing.py
tests/workflows/unit_tests/core_steps/transformations/test_perspective_correction.py
tests/workflows/unit_tests/execution_engine/executor/test_runtime_input_assembler.py

In this PR I try to add video metadata to `workflows` to make it possible for stateful stream- / video- processing blocks to operate.
We have two options basically:
- add optional fields for `WorkflowImage` input
- create additional type of batch-oriented input with metadata
The latter is more elegant imo, does not break bckw compatibility and is also a proof that adding new types of inputs (batch of text data to process by LMM model) will be easily possible. 
YOUR_ANSWER
-   [ ] Docs updated? …

Video metadata in `workflows`

---

inference/core/models/classification_base.py
inference/core/version.py

- The `inference_id` is missing in responses in requests made to classification projects, adding it in this change
- Made several requests against local running inference container and confirmed that the inference_id was in the results. Repeated for other project types: instance-seg, single/multi classification
- Normal hosted inference deploy

Add inference_id for classification

---

inference/core/interfaces/http/http_api.py

1. more exclusions: `/workflows/blocks/describe`, `/workflows/definition/schema`, `/_next/*`
2. add expiration to cached api_key and project_url
3. skip parsing json parameters when request body is empty

More exclusions for dedicated deployment authorizer

---

CODEOWNERS
docs/using_inference/inference_pipeline.md
inference/core/interfaces/stream/inference_pipeline.py
inference/usage_tracking/collector.py

There was a bug in `InferencePipeline` with workflows which do not use the parameter to specify video metadata causing always runtime error - fixed.
* E2E tests

Fix bug with `InferencePipeline` introduced with `VideoMetadata`

---

inference/core/workflows/core_steps/fusion/detections_consensus/v1.py
inference/core/workflows/core_steps/transformations/dynamic_crop/v1.py
tests/inference/models_predictions_tests/conftest.py
tests/inference/models_predictions_tests/test_sam2.py
tests/inference/unit_tests/core/interfaces/stream/test_interface_pipeline.py
tests/inference/unit_tests/usage_tracking/test_collector.py
tests/workflows/integration_tests/execution/test_workflow_detection_plus_classification.py
tests/workflows/unit_tests/core_steps/fusion/test_detections_consensus.py
tests/workflows/unit_tests/core_steps/transformations/test_crop.py

There is a bug in dynamic crop which was iterating through detections like that:
```python
for (x_min, y_min, x_max, y_max), detection_id in zip(
detections.xyxy.round().astype(dtype=int), detections[detection_id_key]
```
assuming `detection_id` key in data. This is not always the case, as a side effect of some blocks - for instance Detections consensus or detections Stitch - which use `sv.Detections.merge(...)` which on no predictions simply returns `sv.Detections.empty()` removing whole `data` dict.
We have two options:
* fix the problem in each source of detcetions
* fix the problem in each place where we process detections
The former seems to be laborious and fragile - especially with blocks from community. The latter seems to be more "defensive" which I prefer attempting to ensure …

Fix issues with dynamic crop and lint tests

---

inference/models/sam2/segment_anything2.py
tests/inference/models_predictions_tests/test_sam2.py

Sam2 cache wasnt properly clearing because different ids were used on the cache and cache keys
Adds test and fix
Pytest
for inference-internal

Bugfix sam2 logits cache and add test

---

inference/core/version.py
inference/usage_tracking/collector.py
inference/usage_tracking/payload_helpers.py
tests/inference/unit_tests/usage_tracking/test_collector.py

Usage payload was recorded only in first payload. This PR is changing this behavior, resource details are recorded in each usage payload
CI tests are passing; inspected payloads and confirmed resource details are in each usage payload
N/A
N/A

Record resource details in each usage payload

---

inference/usage_tracking/collector.py
tests/inference/unit_tests/usage_tracking/test_collector.py

Do not store `resource_details` as JSON when creating new usage payload
CI tests are passing
N/A
N/A

json.dumps resource_details when adding to usage payload

---

inference/core/__init__.py
inference/core/utils/sqlite_wrapper.py
inference/usage_tracking/sqlite_queue.py
tests/inference/unit_tests/core/utils/test_sqlite_wrapper.py
tests/inference/unit_tests/usage_tracking/test_persistent_queue.py

Abstract sqlite3 wrapper in usage collector sqlite queue; preparation for storing plan details in sqlite cache
Added unit tests covering new functionality
N/A
N/A

Abstract sqlite3 wrapper in usage collector sqlite queue

---

inference/core/workflows/core_steps/transformations/detection_offset/v1.py
tests/workflows/unit_tests/core_steps/transformations/test_detection_offset.py

When using the detection offset block, one could set values larger than the image demensions and would result in over offset and null values. This can also be seen when detections are near the edge of the images. 
This PR fixes the detection offset block to the image demensions provided. 
https://github.com/user-attachments/assets/e243b0e5-3d82-4f0a-91a4-bacbdf6f7eb3
New unit test which tests extremely large offsets.

Fix Detection Offset Bug

---

inference/models/utils.py

Allow modelType `yolov8`, without size specified for instance-seg, classification, and keypoint project types. This is already enabled for object-detection. Sometimes Roboflow Models do not have size specified for yolov8 models -- especially custom trained ones.
Regression tests!
Can go out as part of any release.

Allow model type "yolov8" without size

---

inference/usage_tracking/redis_queue.py

Insert usage payloads into redis and to sorted set atomically
On staging
N/A
N/A

Insert usage payloads into redis and to sorted set atomically

---

.github/workflows/test_package_install_inference_with_extras.yml

Increase timeout to 30 minutes for .github/workflows/test_package_install_inference_with_extras.yml

---

inference/core/version.py
inference/core/workflows/core_steps/formatters/vlm_as_classifier/v1.py
tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_claude.py
tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_gemini.py
tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_openai.py
tests/workflows/integration_tests/execution/test_workflow_with_claude_models.py
tests/workflows/integration_tests/execution/test_workflow_with_gemini_models.py
tests/workflows/integration_tests/execution/test_workflow_with_open_ai_models.py
tests/workflows/unit_tests/core_steps/formatters/test_vlm_as_classifier.py

There was a bug with VLM as Classifier block - details of predictions had "class_name" instead of "class" key which is 
incompatible with other blocks - like detections classes replacement.
This shall be released as hotfix.
* new tests

Fix problem with VLM as classifier block

---

inference/core/workflows/core_steps/classical_cv/sift_comparison/v2.py
inference/core/workflows/core_steps/loader.py
tests/workflows/unit_tests/core_steps/classical_cv/test_sift_comparison_v2.py

This PR simplifies the SIFT Comparison blocks so you no longer need to use the SIFT block separately and can pass the images in directly. This allows us to visualize the outputs like in OpenCV's docs.
The old workflow would have looked like this:
Now it looks like this:
And we can also visualize the matches like this:
I also added the option of switching between the brute-force & FLANN based matchers.
On my local inference server with a variety of inputs and workflows.
No
- I think they should be auto-built but lmk if otherwise.

Updated SIFT Comparison Block

---

inference/core/workflows/core_steps/common/query_language/entities/enums.py
inference/core/workflows/core_steps/common/query_language/operations/detections/base.py
tests/workflows/integration_tests/execution/test_workflow_top_prediction.py

Add functionality to the DetectionsTransformation block to return the top prediction by confidence
in the workflows editor & with unit tests
N/A
N/A

Return top prediction by confidence

---

inference/core/workflows/core_steps/models/foundation/anthropic_claude/v1.py
inference/core/workflows/core_steps/models/foundation/google_gemini/v1.py
inference/core/workflows/core_steps/models/foundation/openai/v2.py
inference/core/workflows/core_steps/models/foundation/segment_anything2/v1.py
inference/core/workflows/core_steps/sinks/roboflow/dataset_upload/v2.py

In this PR:
- Simplify model task_type descriptions by auto hiding/showing the relevant properties
- Add properties `always_visible` and `hidden` to block parameters
- bugfix: TASKS_REQUIRING_CLASSES and TASKS_REQUIRING_OUTPUT_STRUCTURE were swapped
https://github.com/user-attachments/assets/69228301-5dc7-4537-8526-aa6e894c34a6
locally
deploy [frontend PR](https://github.com/roboflow/roboflow/pull/4365)
N/A

Control what properties are visible in the UI by default

---

inference/core/workflows/core_steps/visualizations/blur/v1.py
inference/core/workflows/core_steps/visualizations/pixelate/v1.py

blur and pixelate were not inheriting from ColorableVisualizationManifest / ColorableVisualizationBlock, hence #650 resulted in regression (`predictions` missing from `run` args).
CI passing; adding tests covering regression
N/A
N/A

Switch base class of blur and pixelate to PredictionsVisualizationManifest / PredictionsVisualizationBlock

---

inference/core/workflows/core_steps/analytics/time_in_zone/v1.py
tests/workflows/unit_tests/core_steps/analytics/test_time_in_zone.py

`TimeInZoneBlockV1` is currently keeping timer for objects that fall outside of zone. Add option to reset timer when object is outside of zone.
Added unit tests
N/A
Added description of newly added parameter into block metadata

Add option to reset timer when detection falls outside of zone

---

inference/core/workflows/core_steps/classical_cv/image_preprocessing/v1.py
inference/core/workflows/core_steps/loader.py
tests/workflows/integration_tests/execution/test_workflow_with_image_preprocessing.py

Add a block that supports resizing, flipping, and rotating
UI editor & with tests
n/a
n/a

Image preprocessing block (flip, rotate, resize)

---

inference/core/version.py
inference/core/workflows/core_steps/models/foundation/segment_anything2/v1.py

We had a problem with SAM2 model - sometimes it produces segmentation masks being points or lines. That do not come in line with `sv.Detections(...)` which skip the mask if it contains less than 3 points instead leaving blank. That was colliding with the code that associate detections id (more detections were visible - vs trimmed list in sv.Detections). Added filtering of malformed segmentations early-on
* E2E test

Fix issue with SAM2 producing segmentation masks as points and lines

---

CONTRIBUTING.md
docker/dockerfiles/Dockerfile.onnx.cpu.dev

Added a `Dockerfile.onnx.cpu.dev` file that uses watchdog to listen to code changes and auto restart the inference server
-   [X] Development improvement
Use this dockerfile to dev locally
n/a
should update the developer docs to recommend using this dockerfile when deving locally

Docker auto-reload configuration

---

inference/core/workflows/core_steps/common/query_language/entities/operations.py
inference/core/workflows/core_steps/common/query_language/evaluation_engine/core.py
inference/core/workflows/core_steps/models/foundation/openai/v2.py
tests/workflows/unit_tests/core_steps/control_flow/test_control_flow.py

Add additional UQL operations to support multi-label classification operations. In particular:
- any in (Sequence): Checks if any of the provided classes are in the output predicted_classes
- all in (Sequence): Checks that all of the provided classes are in the output predicted_classes (order doesn't matter)
Also, fixed the multi-label classification response returned by OpenAI. Originally was returning [{"predicted_classes": ...}], updated prompt to return {"predicted_classes": ...} 
with unit tests and in the UI editor
related frontend PR: 
n/a

Multi-Label Classification UQL Operations 

---

inference/core/workflows/core_steps/models/foundation/anthropic_claude/v1.py
inference/core/workflows/core_steps/models/foundation/google_gemini/v1.py
inference/core/workflows/core_steps/models/foundation/openai/v2.py
tests/workflows/integration_tests/execution/test_workflow_with_claude_models.py
tests/workflows/integration_tests/execution/test_workflow_with_gemini_models.py
tests/workflows/integration_tests/execution/test_workflow_with_open_ai_models.py

By not so clever (to say the least 😆) code design we were running into issues with batch-processing of VLM-related blocks.
The issue was with overriding variable that instead being a single prompt - was accumulating values
* E2E tested
* Ci still 🟢 
* fixed and added tests

Fix the problem with VLMs on batch inference

---

inference/core/interfaces/http/http_api.py
inference/core/managers/metrics.py
requirements/requirements.gpu.txt

- Reverting roboflow/inference#717 - CI fails on speed regression tests on GPU
* CI works again

Revert "Bring back Prometheus GPU"

---

requirements/requirements.vino.txt

Open vino ort doesn't have match 1.15.1
builds succesfully here: https://github.com/roboflow/inference/actions/runs/11183240407
tests
no

Relax openvino version

---

inference/core/workflows/execution_engine/v1/compiler/cache.py
inference/core/workflows/execution_engine/v1/compiler/core.py
inference/core/workflows/execution_engine/v1/compiler/syntactic_parser.py
inference/core/workflows/execution_engine/v1/dynamic_blocks/block_assembler.py
tests/workflows/unit_tests/execution_engine/compiler/test_cache.py

In this PR, workflows compilation results cache is introduced to reduce latency of consecutive invocations of the same workflow definition.
* CI still 🟢 
* E2E speed test
Compare the outcome of command: `inference benchmark api-speed` for model inference vs the same model within Workflow with only a single block, `inference-cli` **uses 1 client and call requests sequentially**
Abbreviations:
* **SR** stands for initial @PacificDou Report raising the speed issues with EE
* **+CC** stands for the Compiler Cache extension added in **this** PR
* **EE** and **EE overhead …

Caching compilation results

---

requirements/requirements.cli.txt

As requested in https://github.com/roboflow/inference/issues/738, we are bumping `typer` version
* CI 🟢 

Loose `typer` requirements

---

inference/core/workflows/core_steps/models/foundation/google_vision_ocr/v1.py

Google Vision OCR was using wrong fontawesome classes.
Before:
After:

Fix Google Vision OCR icon

---

inference/core/interfaces/http/http_api.py
inference/core/managers/prometheus.py

Add a few interesting inference metrics to the prometheus endpoint.
For example, per model and total time metrics. 
Testing locally (ongoing)

Adding inference metrics to the prometheus scraper

---

inference/core/managers/prometheus.py

The parallel containers dont have the model_manager object so custom per-model Prometheus scraping implemented in https://github.com/roboflow/inference/pull/750 will not work for them. 
This bugfix disables custom prometheus scraping for parallel dockers.
Tested locally on parallel and non-parallel inference containers.

Disable scraping for containers where model_manager is not defined

---

development/benchmark_scripts/benchmark_owlv2_inference_time.py
inference/models/owlv2/owlv2.py
tests/inference/models_predictions_tests/test_owlv2.py

This change introduces some simple approaches to speeding up inference of an OWLv2 model over the original Huggingface implementation. The original implementation on an L4 GPU took 460ms on each iteration of the new test_owlv2.py file, and the new one takes ~36ms. I wrote a tiny little latency test script at the bottom of test_owlv2.py, not sure if there's a better / more 'standard' way of implementing that functionality, or if I should just take it out.
First, we replace the Huggingface preprocessing pipeline with one that makes full utilization of a GPU if available. This reduced preprocessing time from ~200ms to <10ms. I borrowed this implementation from [my own open source repo here](https://github.com/DirectAI/simple-data-free-model-server).
Second, we run the image backbone in mixed …

Owl v2 speedup

---

inference/core/entities/requests/owlv2.py
inference/models/owlv2/owlv2.py
tests/inference/models_predictions_tests/test_owlv2.py

Does a few things:
1. Adds in negative prompting per class for owlvit
2. Uses multiple examples per class by argmax, instead of meaning them
3. Refactors some of these very heavy methods
Integration tests, and tested extensively via roboflow UI
No
Much of the thought here comes from @isaacrob-roboflow and https://github.com/DirectAI/simple-data-free-model-server

Owlvit model enhancements

---

inference/models/owlv2/owlv2.py

OWLv2 based inference should have class-agnostic NMS after the per-class NMS between the positive and negative samples
Passed integration test

adding class agnostic nms

---

inference/models/owlv2/owlv2.py
tests/inference/models_predictions_tests/test_owlv2.py

Current implementation crashes when there are no found boxes. Add a short circuit to return an empty response in that case, and additional integration tests to make sure this and a few other cases are covered.
(new) integration test

fix case where there are no good matches for the prompt

---

inference/usage_tracking/collector.py
inference/usage_tracking/payload_helpers.py
tests/inference/unit_tests/usage_tracking/test_collector.py

Currently usage is stored in local cache even if api key is not available. In this PR caching usage when api key is not provided is turned off.
Affected tests corrected.
N/A
N/A

Do not store usage in cache when API key is not available

---

inference/core/workflows/execution_engine/v1/executor/execution_data_manager/step_input_assembler.py
tests/workflows/integration_tests/execution/test_workflow_with_two_stage_models_and_flow_control.py
tests/workflows/unit_tests/core_steps/visualizations/test_keypoints.py

We had a bug in the following setup: 
`object detection -> crop -> classification -> [downstream step]`, 
for any downstream block we could not correctly construct empty Batches of inputs whenever nothing was detected by primary model. Turned out to be stupid bug.
* new tests
* old tests still 🟢 

Fixing the bug with two stage workflow and continue-if failing when nothing gets detected by primary model

---

inference/usage_tracking/collector.py
inference/usage_tracking/payload_helpers.py
tests/inference/unit_tests/usage_tracking/test_collector.py

Aggregate usage for streams and photos separately
Test case updated; CI passing
N/A
N/A

Aggregate usage for streams and photos separately

---

development/benchmark_scripts/benchmark_owlv2_inference_time.py
inference/models/owlv2/owlv2.py
tests/inference/models_predictions_tests/test_owlv2.py

Ideally if we've recently seen a set of box prompts, we shouldn't download the associated images or recompute the object query logic.
To avoid doing this, if we receive a request that contains a URL, we assume that the image the URL is pointing to won't change and we just directly treat the URL as a hash instead of downloading the image, loading it via PIL, and hashing that. We also provide a shortcut to directly hash the compressed base64 version of the image if that is provided.
We also directly hash the whole set of training images + boxes so that we can check if we've recently used that exact model. If we have, we don't bother doing any of the query compute etc etc which speeds things up in the case of having many images, even if all those images have embeddings that are cached. …

avoiding downloading images if possible

---

inference/core/interfaces/stream/inference_pipeline.py

I have recently tried to apply some simple changes to the InferencePipeline through inheritance but the way the classmethods are implemented means that non of the changes I apply get picked up.
If I do the following:
```
class Pipeline(InferencePipeline):
def __init__(self, *args, **kwargs):
super().__init__(*args, **kwargs)
on_video_frame = self._on_video_frame
def _on_video_frame(video_frames):
predictions = on_video_frame(video_frames)
return predictions
self._on_video_frame = _on_video_frame
pipeline = Pipeline.init(
model_id=ROBOFLOW_MODEL,
video_reference="rtp://192.168.1.23:1234",
on_prediction=func,
)
print("Pipeline type:", type(pipeline))
```
Note that the pipeline class is the inference class not my own.
This means that in order to add a minor change to the pipeline I would …

Allow easier inheritance of pipeline

---

.release/pypi/inference.cli.setup.py
docs/inference_helpers/inference_cli.md
inference_cli/lib/cloud_adapter.py
requirements/requirements.cli.txt
requirements/requirements.cloud_deploy.txt

Skypilot is a fairly large dependency of `inference-cli` that is not frequently used by most users. In this PR, I am adding it as an optional dependency and I added error messages to guide the user toward installing these dependencies if needed.
Tested locally
n/a
-   [X] Docs updated? What were the changes:

Make skypilot optional for inference-cli

---

requirements/_requirements.txt

There is strange issue with sam2 pip package from the fork we are using: https://github.com/SauravMaheshkar/samv2/blob/main/sam2/utils/download.py
basically making `pytest` our prod dependency - without it, SAM2 will be broken 🤷 
We got it working before clean-up just by the virtue of `pytest-asyncio` wrongly added into `_requirements.txt`. When that was fixed, we end up with SAM2 being impossible to import model - this seems to be impossible to be avoided as the module with `import pytest` is entangled in one of `__init__.py` in a function to download weights.... …

Fix SAM2 dependencies

---

inference/core/env.py
inference/models/owlv2/owlv2.py

Pulls OWLv2 cache size out into an environmental variable to make load testing easier as we don't have to have >1000 unique images in order to do a sane test. Also, bumps OWLv2 model size to large (which ideally will get deployed assuming the load testing works out)
I am not sure where the environmental variables get piped in. I found that I had to set the default in the owlv2 constructor in order for the pytest to use the larger version. If anyone has thoughts on that let me know.
Also, I am setting a max cache size of 100 for models. If people start building VERY large models, on the order of 10000 prompts, this could become a problem.
-   [x] New feature (non-breaking change which …

bumping owlv2 version and putting cache size in env

---

inference/usage_tracking/collector.py

Always include internal envs if set
CI passing
N/A
N/A

Always include internal envs if set

---

inference/models/owlv2/owlv2.py

Remove print statement used in debugging owlv2.

Remove debug print from owlv2

---

inference/core/version.py
requirements/_requirements.txt

`tokenizers` is dependency of our dependenices, not enlisted in our requirements, they introduced "silent" breaking change (seems like the discussions suggest they revert it), but as a result - `inference` is broken to be installed.
We are pinning to last working version, hoping problem will be solved by community soon, in release notes of `0.28.2` we will guide users of older versions how to deal with the problem.
* CI

Fix issue with broken builds after last release of `tokenizers`

---

.github/actions/determine-tags/action.yml
.github/workflows/docker.cpu.yml
.github/workflows/docker.gpu.yml

Update the release logic to support the following cases:
- releases will also push to `latest` if the GitHub release is tagged as the latest release AND the version in version.py matches the tag of the release. The tag of the release is normalized to remove the leading `v`. If both of those aren't true, the container tag will be set to the tag of the github release.
- push to `main` will only tag an image as `main`. This will allow for a bleeding-edge build
- custom tag will prepend the version from `version.py` to the tag, and will ONLY allow pushing the custom tag
- Force push will only update the container tag that matches the value in `version.py`
-   [x] New feature (non-breaking …

Update Docker Tag Logic

---

inference/core/entities/requests/workflows.py
inference/core/roboflow_api.py

Working on updates to our backend API that allow serving "Public" Workflows from our backend that won't require an API Key to pull the spec down so we can have better examples in our README and docs that don't require a Roboflow account.
These changes allow our client & server to pass off the key requirement logic to the API.
Against our staging API & tests still pass.
Needs the change to our backend API deployed to prod first; separate PR for that in our backend repo.
-   [x] Should be auto-documenting via the updated type annotation

Don't Require API Keys for Public Workflows

---

requirements/_requirements.txt

Piexif usage was removed some time ago in https://github.com/roboflow/inference/pull/52.
-   [x] Maintentance
CI tests should be enough.

Remove piexif dependency

---

.dockerignore
inference/models/utils.py

Allows inference of PaliGemma 2 models trained in roboflow
tested locally
LoraBases have been uploaded

Add paligemma2

---

mkdocs.yml

This is a tiny change that removes duplicate initialization of the Kapa widget.
With duplicate initialization no Roboflow logo is displayed on the chat button, and attempts to chat with the agent result in a configuration error message.
⚠️ This worked with `mkdocs serve`, but not with `mike serve`.
⚠️ As mentioned, this worked with `mkdocs serve`, but not with `mike serve`.

Kapa: remove duplicate initialization

---

inference/core/models/classification_base.py

Pass kwargs down the call chain in ClassificationBaseOnnxRoboflowInferenceModel.infer
Tested manually
CI passing
N/A
N/A

Fix confidence not applied when inferring classification models

---

inference/core/workflows/core_steps/models/roboflow/multi_label_classification/v2.py
inference/core/workflows/core_steps/sinks/roboflow/dataset_upload/v1.py

Extend roboflow_api.annotate_image_at_roboflow to pass list of classes if multi-label-classification model was used.
This enables `roboflow_core/roboflow_dataset_upload@v2` block to upload image as well as annotations (list of classes) when multi-label-classification model was inferred on.
CI passing
tested manually
N/A
N/A

Extend roboflow_api.annotate_image_at_roboflow to pass list of classes if multi-label-classification model was used

---

inference/core/workflows/core_steps/common/query_language/entities/enums.py
inference/core/workflows/core_steps/common/query_language/operations/detections/base.py
tests/workflows/integration_tests/execution/test_workflow_top_prediction.py

Select the `first` or `last` prediction using the DetectionsSelection UQL operation. Pairs well with the DetectionsSort operation
locally & with unit tests
n/a
n/a

Additional DetectionsSelection Operations

---

requirements/_requirements.txt
requirements/requirements.cli.txt
requirements/requirements.sdk.http.txt
requirements/requirements.test.unit.txt
tests/workflows/integration_tests/execution/test_workflow_with_sahi.py
tests/workflows/integration_tests/execution/test_workflow_with_video_metadata_processing.py

Supervision has a policy where deprecations are announced 5 releases in advance.
This PR makes the single change required to support supervision up to release `0.30.0` based on the [planned deprecations](https://supervision.roboflow.com/latest/deprecated/). However, we expect to move to `1.0.0` before `0.30.0`.
Changes:
* Updated InferenceSlicer parameter (deprecated in `0.27.0`)
* Bumped lower supervision bound to `0.25.1` (dependency versions, specifically addressing `numpy` version clash)
* Bumped upper version to `0.30.0` (safe to do due to deprecation policy)
Note: this PR uses the corrected variable name `overlap_filter` - I left a mistake in the deprecations doc.
-   [x] New …

Expand supervision support to 0.30.0

---

inference/models/transformers/transformers.py

Working on speeding up Florence2 deployment. There was a bug where LoRA-trained models were about 3x slower at inference time because the LoRA weights were being run independently of the model weights. Merging them in resolved the issue.
Benchmarked speed with a tiny custom script and am assuming existing integration tests cover correctness.

merge lora into base model for 3x speedup

---

inference/core/version.py
inference_cli/lib/workflows/common.py
tests/inference_cli/integration_tests/test_workflows.py
tests/inference_cli/unit_tests/lib/workflows/test_common.py

This is a fix for a problem with image reference not saved in predictions file 
* test added

Add fix for the problem with inference-cli workflows predictions saving

---

inference/core/cache/lru_cache.py
inference/core/workflows/core_steps/models/foundation/clip/v1.py

This adds a least recently used cache to store CLIP text embeddings so they don't need to be recalculated every time. Text embeddings are often used for eg class names which remain constant across runs so this greatly speeds up using CLIP to compare text/image embeddings.
Memory usage should be negligible; 512k for a full cache with the largest CLIP embedding dimensions.
Locally & ensured tests don't break
No
-  No updates needed; internal change to the block

Cache CLIP Text Embeddings in Workflow Block

---

inference/core/workflows/core_steps/fusion/buffer/v1.py
inference/core/workflows/core_steps/loader.py
tests/workflows/unit_tests/core_steps/fusion/test_buffer.py

Introduces a new block that stores a sliding window of the previous things you've passed to it. This is useful when you want to hang on to data for a while to do things with it later.
Some example use-cases:
* Rendering a gif of the past few seconds of video when something happens later on
* Passing outputs of several frames from a keypoint model to an action recognition model
* Smoothing outputs over time by averaging them together
* Visualizing changes over time
Locally & added new tests
No
-   [x] Self-documenting via manifest

Workflows Buffer Block

---

inference/core/workflows/core_steps/flow_control/rate_limiter/v1.py
inference/core/workflows/execution_engine/entities/types.py

The Rate Limiter operates on the system clock by default. But if you're running on async video you can run it at faster than realtime. This means the block fires out of sync with the video (eg if the video is 60 seconds and processes in 3 real world seconds then a rate limiter with a cooldown of 1s only fires 3 times vs 60).
This is often not desirable if you're looking to speed up your processing time while otherwise keeping the behavior the same. For example, sampling a frame for upload once per second shouldn't sample 2x fewer frames from a video if you run it twice as fast.
To fix, we add an optional parameter that lets you synchronize the rate limiter clock to the video rate instead of the wall rate.
Locally on …

Allow using video metadata for rate limiter on recorded video

---

inference/core/workflows/core_steps/loader.py
inference/core/workflows/core_steps/visualizations/grid/v1.py
tests/workflows/unit_tests/core_steps/visualizations/test_grid.py

Accepts an array of images and tiles them into a grid like this:
Works nicely with the new Buffer Block from #894 
Locally & added new test
No
-   [x] Self-documenting via manifest

Workflows Grid Visualization Block

---

inference/core/roboflow_api.py
inference/models/owlv2/owlv2.py
inference/models/utils.py
tests/inference/models_predictions_tests/test_owlv2.py

Adds ability to serialize/deserialize training data for owlv2 models
added tests
new owlv2 endpoint needs to be deployed

Serialized owlv2 model

---

CODEOWNERS

add @probicheaux @EmilyGavrilenko @hansent and @yeldarby as code owners for docs
maintanance
n/a 
n/a 
n/a

add more code owners for docs

---

README.md
docs/index.md
docs/scripts/gen_ref_pages.py
docs/styles.css

This is a temporary update to the docs landing page. We'll replace it with something better soon, but making way for the new "Start" section of the docs I'm going to follow up with.
Also added an option to skip the reference docs generation locally via an environment variable because they slow down the feedback cycle while editing things.
Now looks like this:
Non-functional change; previewed it on my local docs build
No, just docs
-   [x] Docs updated? What were the changes: this is the docs update.

Update Landing Page

---

.github/workflows/check_if_branch_is_mergeable.yml

Extends the mergeable action to support comparing branches from forked repositories.
Key changes:
- Add URL sanitization for branch names to prevent injection attacks
- Update GitHub API comparison format to support fork comparisons
- Add proper exit codes and improved status messages
- Handle behind/diverged states explicitly
Before this change, the action only worked for branches within the same repository.
Now it correctly handles fork comparisons by using the OWNER:REPO:BRANCH format
and sanitizes all inputs to prevent command injection via malicious branch names.

Support forks

---

.github/workflows/docs.yml
.github/workflows/hosted_inference_e2e_test_production.yml
.github/workflows/hosted_inference_e2e_test_staging.yml
.github/workflows/integration_tests_inference_cli_depending_on_inference_x86.yml
.github/workflows/integration_tests_inference_cli_x86.yml
.github/workflows/integration_tests_inference_models.yml
.github/workflows/integration_tests_workflows_x86.yml
.github/workflows/load_test_hosted_inference.yml
.github/workflows/prod_build_and_push_hosted_inference_image.yml
.github/workflows/staging_build_and_push_hosted_inference_image.yml
.github/workflows/static_code_analysis.yml
.github/workflows/test.jetson_4.5.0.yml
.github/workflows/test.jetson_4.6.1.yml
.github/workflows/test.jetson_5.1.1.yml
.github/workflows/test.jetson_6.0.0.yml
.github/workflows/test.nvidia_t4_parallel_server.yml
.github/workflows/unit_tests_inference_cli_x86.yml
.github/workflows/unit_tests_inference_sdk_x86.yml
.github/workflows/unit_tests_inference_x86.yml
.github/workflows/unit_tests_workflows_x86.yml

Fix checkout process for forked repository workflows by removing explicit `ref: ${{ github.head_ref }}` configurations from all GitHub Actions. 
Context:
- When running workflows from forks, the explicit head_ref configuration was causing checkout issues
- actions/checkout@v4 automatically handles the correct ref for both fork and non-fork scenarios
Changes:
- Remove `ref: ${{ github.head_ref }}` from all workflow files (20+ files modified)
- Let actions/checkout@v4 handle the ref selection automatically based on the context
This change simplifies our workflow configurations and fixes checkout issues when running from forked repositories. The checkout action will now automatically select the appropriate ref whether running from a fork or internal branch.

Remove explicit checkout ref

---

inference/core/env.py
inference/core/roboflow_api.py
inference/usage_tracking/config.py
inference/usage_tracking/payload_helpers.py
tests/inference/unit_tests/core/test_roboflow_api.py

This feature let us to inject extra headers to RF API requests.
* New tests

Add env-injectable headers to RF API requests

---

.github/workflows/docs.yml
.gitignore
development/docs/write_cli_docs.py
mkdocs.yml

auto generate command line docs for  CLI using typer command line tool.
This is loosely based on the code from https://github.com/syn54x/mkdocs-typer2
I tried both the existing `mkdocs-typer` and `mkdocs-typer2` pip packages, but couldn't get either to work.  The first one hasn't been updated for 3 years and I couldn't get it to generate anything.  
`mkdocs-typer2` hooked / tried to generate, but failed internally trying to update the html tree with `ParseError: mismatched tag: line 449, column 3`.  Looking at the sourcecode I saw it used the `typer` command line tool to generate markdown and then generate html from it.  I think the error is either in the generated HTML or because of the way its tryin to hook it into our material theme.
So instead I just added a script like the other docs …

auto generate command line docs for  CLI

---

inference/core/workflows/core_steps/models/foundation/google_vision_ocr/v1.py

Fixes a bug caused by Google Vision API responses that contain vertices with 'x' or 'y' coordinates only. Their doc doesn't cover this case, but after some testing, it seems like treating the default as '0' gives the correct bounding boxes.
Tested locally with a workflow that like the following:
```json
{
"version": "1.0",
"inputs": [
{
"type": "WorkflowParameter",
"name": "api_key"
},
{
"type": "InferenceImage",
"name": "image"
}
],
"steps": [
{
"type": "roboflow_core/roboflow_instance_segmentation_model@v1",
"name": "model",
"images": "$inputs.image",
"model_id": "yolov8n-seg-640",
"confidence": 0.1,
"iou_threshold": 0
},
{
"type": "roboflow_core/detections_filter@v1",
"name": "detections_filter",
"predictions": …
```

Fix Google Vision Block bounding box parsing

---

inference/core/roboflow_api.py
inference/core/version.py

Copy internal workflow id to specification before it's cached
CI passing
N/A
N/A

Copy internal workflow id to specification before it's cached

---

inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py

When handling stream through WebRTC we currently expect image to be available. It is possible workflow branch with image generation was not executed - in such case we should send raw image.
CI passing
E2E tested
N/A
N/A

Send raw image over WebRTC if no visualisation is available

---

inference/core/models/roboflow.py

Supporess warnings from ONNX like one below:
```
UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'OpenVINOExecutionProvider, CPUExecutionProvider'
```
ONNX session log severity is set to 3 (ERROR) ((docs)[https://onnxruntime.ai/docs/api/python/api_summary.html])
-   [x] Quality of life
CI passing
N/A
N/A

Suppress ONNX providers warning

---

inference/core/workflows/core_steps/transformations/detection_offset/v1.py
tests/workflows/unit_tests/core_steps/transformations/test_detection_offset.py

Padding bounding boxes by percent rather than pixels is a new feature (implemented in https://github.com/roboflow/inference/pull/956/files) and I don't think was implemented correctly. When talking with potential users, they want padding based on a percentage of the size of the bounding box, not the size of the image. This is done because larger detections need more padding because they are closer to the camera. I don't think padding based on image size is very useful. I'm hoping since this functionality is new enough and was implemented for a specific use case that we can modify it.
Unit tests cover this change fully.
n/a - standard deploy
-   [x] Updated description of input to reflect the use of bounding box percent.

Detection Offset - Use bbox for percent padding

---

inference/core/workflows/core_steps/flow_control/rate_limiter/v1.py

This PR changes the copy of the Rate Limiter block to use the word "run" instead of "fire".
"run" will resonate more with our users. 
- Copy change
This can be tested by ensuring the Workflow manifest contains the new copy.
N/A
-   [x] Docs updated? What were the changes: Auto-documenting via manifest

Change "fire" to "run" in rate limiter description

---

inference_sdk/http/client.py
tests/inference_sdk/unit_tests/http/test_client.py

the /model/registry endpoint usually doesnt require api keys when run locally.  However on dedicated deployments all requests need to pass api key to validate they come from workspace that the dedicated deployment belongs to.
Without this change the benchmark cli tool doesn't work.
-   [c] Bug fix (non-breaking change which fixes an issue)
locally
n/a
n/a

send api key for model registry to make it work on dedicated deployments

---

inference/models/owlv2/owlv2.py
requirements/_requirements.txt

Reverts roboflow/inference#973
Building of docker container fails, please fix:
https://github.com/roboflow/inference/actions/runs/12949841680

Revert "Use precomputed owl embeddings"

---

inference/core/workflows/core_steps/models/foundation/google_vision_ocr/v1.py

[https://vision.googleapis.com/v1/images:annotate](https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate) accepts [AnnotateImageRequest](https://cloud.google.com/vision/docs/reference/rest/v1/AnnotateImageRequest) where [imageContext](https://cloud.google.com/vision/docs/reference/rest/v1/ImageContext) can be passed. We can pass `languageHints` parameter allowing user to narrow down language (if known). All hints must be coming from [list of supported languages](https://cloud.google.com/vision/docs/languages)
CI passing
N/A
N/A

Add optional language_hints input parameter to be passed as imageContext.languageHints

---

inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py

With current implementation of webrtc stream we are attempting to send back image specified within request `stream_output` parameter. If this output is not visual and we have other visual outputs then pipeline would not send anything back to the user. In this change type of output is checked and in case it's not WorkflowImageData, first WorkflowImageData output is sent instead.
CI passing
E2E tested
N/A
N/A

When stream output received in camera streaming payload is not WorkflowImageData, select first available WorkflowImageData output

---

inference/core/workflows/core_steps/classical_cv/size_measurement/v1.py
tests/workflows/unit_tests/core_steps/classical_cv/test_size_measurement.py

size_measurement block stores dimensions as width/height based on angle of the bounding rect. Based on camera angle it's possible to have width/height swapped - if user expects width to be longer than height however due to angle shorter dimension can be returned as width. This change adds extra parameters storing longer and shorter dimensions.
CI passing
N/A
N/A

Add 'longer' and 'shorter' keys to the output of size_measurement block

---

inference/core/workflows/core_steps/transformations/bounding_rect/v1.py

Current implementation of bounding_rect stores results in custom keys in sv.Detections.data. Users chain this block with expectation that results will be seamlessly used by other blocks. This change allows users to visualize results of this block.
This change also enables results of this block to be used by size measurement block.
CI passing
E2E tested
N/A
N/A

When running bounding_rect update mask and xyxy of source sv.Detections so results can be visualized

---

development/docs/write_cli_docs.py

unnecessary print in script to generate cli docs reference
remove print
locally via ` python -m development.docs.write_cli_docs` 
n/a
updates script to generate cli docs

remove print from cli docs generation script

---

tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_dataset_upload.py

We had problem with platform tests, as now one cannot register the multiple annotations for the same image causing the test to crash, even though the system works fine. Changed the test such that it it sends random images (and do not care about asserting responses - we have that covered **in other tests**).
* CI

Fix platform tests

---

inference/core/interfaces/http/http_api.py
inference/core/version.py
requirements/requirements.http.txt

Flush usage_collector on shutdown
Tested on staging
N/A
N/A

Flush usage_collector on shutdown

---

inference/core/entities/responses/workflows.py
inference/core/interfaces/http/http_api.py
inference/core/workflows/errors.py
inference/core/workflows/execution_engine/v1/compiler/syntactic_parser.py
inference/core/workflows/execution_engine/v1/executor/core.py

Add blocks_syntax_errors and outputs_syntax_errors to WorkflowSyntaxError
Add block_id to StepExecutionError
CI passing
Manually E2E tested
N/A
N/A

Include reference to block or output introducing error

---

inference/core/version.py
inference_cli/lib/workflows/video_adapter.py

We need ability to track video processing progress also by the caller (not only using progress sink inside a function to display on the screen).
* e2e
* ci still 🟢 

Add possibility to inject sink function to batch video processing

---

inference_cli/lib/workflows/core.py
inference_cli/lib/workflows/local_image_adapter.py
inference_cli/lib/workflows/remote_image_adapter.py
inference_cli/workflows.py

In this PR I am adding an option to abort processing of images directories with workflows when number of errors exceed threshold - this is important as so far, there was try-catch on separate files to be processed in directory - making it impossible to abort if global problem occurs. This is important for batch processing to be able to stop when to many errors occur.
* CI still green 🟢 
* e2e tests

Add give-up on errors in workflows execution

---

inference/core/workflows/core_steps/transformations/dynamic_zones/v1.py

When using dynamic zones to perform perspective correction it is useful to be able to scale resulting zone up to maintain all details within zone.
This change extends dynamic zone block to allow user to scale the zone up.
Example zone before scaling:
When scaling is applied:
CI passing
E2E tested
N/A
N/A

Add option to scale dynamic zone

---

CODEOWNERS
theme/main.html

Fixes regression from #1011 that caused the hamburger nav on mobile to not be visible on the docs homepage.
Local mkdocs serve
No
-   [x] Docs updated? What were the changes: This them

Fix docs homepage mobile nav

---

inference/core/version.py
inference/models/README.md
inference/models/__init__.py
inference/models/utils.py
inference/models/yolov12/LICENSE.txt
inference/models/yolov12/__init__.py
inference/models/yolov12/yolov12_object_detection.py

Adds yolov12 to inference. Tested predictions with ultralytics CLI from yolov12 repo:
and with our impl:
No aliases yet. That'll be a follow up.
tested locally
No

Add Yolov12 to inference

---

inference/core/interfaces/http/http_api.py

…aded without api_key
add openapi.json to dedicated deployment authorizer whitelist so /docs and redoc can be loaded without api_key
Tested in staging

add openapi.json to whitelist of dedicated deployment authorizer

---

inference/core/env.py
inference/models/owlv2/owlv2.py
tests/inference/models_predictions_tests/test_owlv2.py

Added a singleton manager to handle OWLv2's vision model compilation in background, avoiding the initial 2-minute blocking compilation while maintaining the performance benefits of compiled models.
- Added OWLv2ModelManager class that manages vision model compilation per huggingface_id
- Compilation happens in a daemon thread, allowing immediate model usage
- Uses thread-safe singleton pattern to ensure one compiled model instance per huggingface_id
- Integrated with existing Owlv2Singleton class
- No changes to the model's API or behavior
```
model = OwlV2(model_id=f"owlv2/{OWLV2_VERSION_ID}")
response = model.infer_from_request(request)
```
- Eliminates 2-minute blocking during model initialization
- Maintains compiled model performance benefits
- Thread-safe
- Transparent to existing …

Add Background Compilation for OWLv2 Vision Model

---

inference/core/utils/onnx.py

Running GPU preprocessed inference while another process used the GPU sometimes caused the ONNX model to produce unexpected output. By asking the ONNX session to ensure that its input buffer is synchronized prior to running inference, we resolve this issue. We also cause faster inference. With CPU based preprocessing, my test based on our client's use case runs in 130ms. With GPU, we get 40ms. With synchronization, we get 22ms.
I ran inference while training a neural network in another process. Without synchronization, the model would sometimes produce confidences that …

synchronize inputs to onnx session on GPU

---

inference/core/env.py
inference/core/interfaces/stream_manager/manager_app/app.py
inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py

Prevent pipeline creation if there is insufficient memory available
CI passing
Manually tested on local deployment by setting `STREAM_MANAGER_MAX_RAM_MB=0`
Needs to be tested on dedicated deployment with sane RAM limit
N/A
N/A

Prevent pipeline creation if there is insufficient memory available

---

inference/core/interfaces/camera/video_source.py

- User running into ZeroDivisionErrors when running multiplexed video inputs. This change adds an epsilon to the denominator to prevent zero division
User's Code:
```python
from inference.core.interfaces.stream.inference_pipeline import InferencePipeline
from inference.core.interfaces.stream.sinks import UDPSink
udp_sink = UDPSink.init(ip_address="localhost", port=8080)
InferencePipeline.init(
api_key="***",
model_id="coco/34",
class_agnostic_nms=False,
confidence=0.3,
iou_threshold=0.50,
max_detections=100,
video_reference=[0, 1, 2, 3],
active_learning_enabled = False,
video_source_properties ={"frame_width": 1280, "frame_height": 720},
on_prediction=udp_sink.send_predictions
).start()
```
Error:
```
get_fps_if_tick_happens_now
return (len(fps_monitor.all_timestamps) + 1) / …
```

Catch ZeroDivisionError in video source

---

inference/core/workflows/core_steps/transformations/dynamic_crop/v1.py
tests/workflows/integration_tests/execution/test_workflow_with_keypoints_detections_and_dynamic_crop.py

For each cropped image, also output the detection that goes along with it (including class, mask, keypoints, other metadata). This helps so that you have matching detections in the same dimensionality to work with after the crop.
Locally so far.
Didn't bump the version since it shouldn't be a breaking change but could see an argument that changing the output signature should mean we bump dynamic crop block to v2.
-   [ ] Docs updated? What were the changes: Not yet

Output predictions for Dynamic Crop

---

inference/core/env.py
inference/core/registries/roboflow.py
inference/core/version.py
requirements/_requirements.txt

Add optional models cache authorization. Feature is turned on with MODELS_CACHE_AUTH_ENABLED environmental variable. Authorization result is cached for MODELS_CACHE_AUTH_CACHE_TTL seconds.
CI passing
N/A
N/A

Add optional models cache authorization

---

inference_cli/lib/workflows/video_adapter.py

We had a bug in batch processing leading processes to hang in a situation when there is error in inference thread - then Inference pipeline shuts down all of the internal threads apart from video sources - which are closed only when `.terminate(...)` is called.
This solution is just bug-fix - in new iteration of `InferencePipeline` we need to design it better to handle such cases.
* e2e test against problematic workflow

Add pipeline termination when processing is over

---

inference/core/roboflow_api.py

Fixes #1108 
Updates the local workflow inference file retrieval to use the same hashing file naming as when the file is saved (98d60c4).
Verified that I can now trigger workflows.

Fix local workflow file not found error

---

inference/core/interfaces/http/http_api.py
inference/core/version.py

Versionless models pass non-numeric `version_id` as part of route path, hence are not handled by [legacy routes](https://github.com/roboflow/inference/blob/main/inference/core/interfaces/http/http_api.py#L2208)
CI passing
http://127.0.0.1:9001 manually tested and confirmed to work
N/A
N/A

handle versionless model id through legacy routes

---

docs/fine-tuned/rfdetr.md
mkdocs.yml

This PR expands the RF-DETR documentation with a more detailed description of the model, links to new content, and more context around the code snippet.
This PR also adds the RF-DETR docs to the mkdocs table of contents.
You can test this change by building the documentation and checking the `fine-tuned/rfdetr` page.
N/A
N/A

Update RF-DETR docs

---

inference/core/version.py
inference/usage_tracking/collector.py
requirements/_requirements.txt
requirements/requirements.cli.txt
requirements/requirements.sam.txt

Do not pass default or empty source info
CI passing
N/A
N/A

Do not pass default or empty source info

---

inference/core/interfaces/camera/entities.py
inference/core/interfaces/camera/video_source.py
inference/core/version.py
inference/core/workflows/core_steps/common/query_language/entities/enums.py
inference/core/workflows/core_steps/common/query_language/entities/operations.py
inference/core/workflows/core_steps/common/query_language/operations/core.py
inference/core/workflows/core_steps/common/query_language/operations/frame_metadata/base.py
inference/usage_tracking/__init__.py
inference/usage_tracking/collector.py
tests/conftest.py
tests/inference/unit_tests/core/interfaces/camera/test_video_source.py
tests/inference/unit_tests/core/interfaces/conftest.py
tests/inference/unit_tests/usage_tracking/test_collector.py
tests/workflows/integration_tests/execution/test_workflow_with_property_extraction.py

Extend CV2VideoFrameProducer to return timestamp_created when calling discover_source_properties Extend VideoSource and VideoConsumer to pass frame timestamp related to file creation date within WorkflowImageData.video_metadata
CI passing
New tests introduced
N/A
N/A

Extend PropertyDefinition block to expose ExtractFrameMetadata operation

---

docker/dockerfiles/Dockerfile.onnx.cpu
docker/dockerfiles/Dockerfile.onnx.cpu.dev
docker/dockerfiles/Dockerfile.onnx.cpu.parallel
docker/dockerfiles/Dockerfile.onnx.cpu.slim
docker/dockerfiles/Dockerfile.onnx.cpu.stream_manager
inference/core/version.py
requirements/_requirements.txt

Some issue with `wheel` package - which now apparently must be available before pip install other packages using it.
* build in CI

Fix CPU builds which are failing for no reason :)

---

inference/models/rfdetr/rfdetr.py

Dropping OpenVINO runtime for RF-DETR until we confirm its useful.
Tested locally
No
-   [ ] Docs updated? What were the changes: No

drop openvino

---

inference/core/workflows/core_steps/models/foundation/anthropic_claude/v1.py

Anthropic removed `claude-3-sonnet-20240229` from their API (even though it's still marked as deprecated for another month).
This PR removes the deprecated model version, that errors like this:
```sh
curl -s https://api.anthropic.com/v1/messages \
--header "x-api-key: $ANTHROPIC_API_KEY" \
--header "anthropic-version: 2023-06-01" \
--header "content-type: application/json" \
--data \
'{
"model": "claude-3-sonnet-20240229",
"max_tokens": 1024,
"messages": [
{"role": "user", "content": "Hello, world"}
]
}' | jq .
{
"type": "error",
"error": {
"type": "not_found_error",
"message": "model: claude-3-sonnet-20240229"
}
}
```
The PR also adds the new model versions from Anthropic. More context on:
- https://docs.anthropic.com/en/docs/resources/model-deprecations#model-status
- …

Remove retired Claude version and add new ones

---

inference/core/workflows/core_steps/analytics/overlap/v1.py
inference/core/workflows/core_steps/loader.py
tests/workflows/integration_tests/execution/test_workflow_with_overlap.py
tests/workflows/unit_tests/core_steps/analytics/test_coords_overlap_v1.py

Adds an overlap block filter, which filters out all classes that overlap some other filter class. Ex. person on a bicycle, widget on a pallet, person in a car, etc.
No dependency changes required - this is a very simple, but extremely useful block.
-   X New feature (non-breaking change which adds functionality)
-   X This change requires a documentation update
Both unit and workflow test cases are included, in addition to my own testing.
The block will need to be documented once the PR is approved.
-   [ ] Docs updated? What were the changes: (doc updates TBD once the PR is approved - I need to make sure we're ok with merging this first)

Initial overlap block filter commit

---

docs/foundation/depth_estimation.md
inference/core/entities/requests/inference.py
inference/core/env.py
inference/core/managers/base.py
inference/core/registries/roboflow.py
inference/core/utils/roboflow.py
inference/core/workflows/core_steps/loader.py
inference/core/workflows/core_steps/models/foundation/depth_estimation/v1.py
inference/models/README.md
inference/models/depth_estimation/LICENSE.txt
inference/models/depth_estimation/__init__.py
inference/models/depth_estimation/depthestimation.py
inference/models/transformers/transformers.py
inference/models/utils.py
mkdocs.yml
tests/inference/integration_tests/conftest.py
tests/inference/integration_tests/test_depth_anything.py
tests/inference/integration_tests/test_depth_estimation_block.py
tests/workflows/integration_tests/execution/test_workflow_with_depth_anything.py

Implemented a new Depth Estimation workflow block that leverages Depth Anything V2 model to perform depth estimation on images. This block provides a powerful tool for analyzing spatial relationships and creating depth maps from 2D images.
The implementation includes:
- A robust workflow block manifest with detailed documentation
- Comprehensive error handling and model management
- Clear output definitions for depth maps and normalized depth data
The block is implemented in `inference/core/workflows/core_steps/models/foundation/depth_estimation/v1.py`.
The implementation was tested through:
1. Unit tests for the workflow block manifest and configuration
2. Integration …

Depth estimation workflow block

---

inference/core/env.py
inference/models/owlv2/owlv2.py

In order to speed up client requests (including first request), preload set of huggingface IDs on inference startup.
This option may result in failure for multiple potential reasons, i.e. lack of GPU or RAM - in such case error will be logged out and inference will start without preloaded HF ID's
N/A

Preload hugginface IDs on inference startup

---

inference/core/version.py
inference/models/rfdetr/rfdetr.py

Fixing rf-detr to ignore predictions of background class, to make metrics work in the app
- 
Tested locally
No
-   [ ] Docs updated? What were the changes: No

Fix rf-detr to ignore predictions of background class

---

inference/core/env.py
inference/core/interfaces/http/http_api.py
inference/core/logger.py

Add CORRELATION_ID_LOG_KEY; fix typo for CORRELATION_ID_HEADER
CI passing
started docker like below:
```
docker run \
--rm \
-p 9001:9001 \
-e LOG_LEVEL=INFO \
-e API_LOGGING_ENABLED=True \
--name=hosted_inference \
roboflow/roboflow-inference-server-cpu:test
```
then made request like below:
```
base64 -i /path/to/file.jpg | curl -H "X-Request-ID: test-correlation-id-123" -d @- \
"http://127.0.0.1:9001/chess-pieces-and-chess-board-object-detection/6?api_key=secret"
```
got log like below:
```
INFO:inference:{"event": "Fetching active learning configuration.", "request_id": "test-correlation-id-123", "timestamp": "2025-04-18 08:53.13", "filename": "configuration.py", "func_name": "get_roboflow_project_metadata", "lineno": 121}
``` …

Add CORRELATION_ID_LOG_KEY; fix typo for CORRELATION_ID_HEADER; control logging across modules with single env variable API_LOGGING_ENABLED

---

inference/core/interfaces/stream_manager/manager_app/app.py
inference/core/interfaces/stream_manager/manager_app/entities.py

Fix a few race conditions that causes the server to freeze when a stream pipeline is terminated:
- terminating a pipeline manually during a health check freezed the server
- having a pipeline time out during a health check also freezed it
https://github.com/user-attachments/assets/f33b0654-a4b6-43f4-8ba4-cf88bd2c194b
This PR makes sure that no status checks are run during termination and also that the health check doesn't try to terminate a pipeline that's already closed.
Tested locally decreasing the pipeline timeout to 10s and starting/stoping streams multiple times, and also letting a pipeline timeout and get auto-terminated.
No

Fix video pipeline race conditions

---

inference/core/workflows/core_steps/transformations/byte_tracker/v3.py

Adding keypoint detection to the list of valid byte tracker inputs. Byte tracker appears to be working fine with keypoint data, which has all of the object detection data in it.
-   [ X] New feature (non-breaking change which adds functionality)
Ran unit tests, and tested a workflow with it
N/A
No doc changes

Add keypoint detection to byte tracker inputs

---

inference/core/managers/decorators/fixed_size_cache.py
inference/core/version.py

Following error was observed on serverless deployment:
```
File "/app/inference/core/interfaces/http/http_api.py", line 273, in wrapped_route
return await route(*args, **kwargs)
File "/app/inference/usage_tracking/collector.py", line 723, in async_wrapper
res = await func(*args, **kwargs)
File "/app/inference/core/interfaces/http/http_api.py", line 2512, in legacy_infer_from_request
self.model_manager.add_model(
File "/app/inference/core/managers/decorators/fixed_size_cache.py", line 49, in add_model
to_remove_model_id = self._key_queue.popleft()
IndexError: pop from an empty deque
```
Manually tested
N/A
N/A

WithFixedSizeCache memory pressure - prevent from attempts to remove from epty _key_queue

---

README.md

This PR updates the README to show the `pip install inference-sdk` command more prominently.
I'm new to supervision and inference and wanted to run the example from here:
https://supervision.roboflow.com/latest/how_to/detect_and_annotate/
which has
```
from inference import get_model
```
I overlooked the `pip install inference-sdk` in your README which is very far down and wasn't very prominent. Looking on PyPI I was confused whether I need the `inference` or `inference-sdk` package and with both got cryptic "No solution found ..." errors from `uv add` because of version constraints between supervision, inference and openCV. Is it possible that you simplify and moving forward just offer one instead of two inference packages and consistently in the inference/supervision/all docs recommend …

Show pip install inference-sdk more prominently in README

---

inference/core/workflows/core_steps/common/serializers.py
inference/core/workflows/core_steps/transformations/dynamic_zones/v1.py

The goal is to serve back simplified polygon
Currently, due to the fact that contour is stored as mask, simplification is lost when calling `polygon_to_mask` to store the polygon and then `mask_to_polygons` when serializing.
In order not to lose the simplification of polygon, `sv.Detections["polygon"]` should be used if available.
CI passing
Manually tested
N/A
N/A

When serializing sv.Detections produced by segmentation model, use sv.Detections['polygon'] as vertices for points if available

---

inference/core/active_learning/configuration.py
inference/core/interfaces/camera/camera.py

This small PR resolves the deprecation warnings of `logger.warn`:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

Migrate to `logger.warning` usage

---

inference/__init__.py
inference/core/models/roboflow.py
inference/core/registries/roboflow.py
inference/core/version.py
tests/inference/hosted_platform_tests/test_core_models.py

Handle core models when MODELS_CACHE_AUTH_ENABLED is set
CI passing
E2E tests on staging against serverless passing
N/A
N/A

Handle core models when MODELS_CACHE_AUTH_ENABLED is set

---

tests/inference/hosted_platform_tests/test_roboflow_models.py

serverless throws 404 when model was not found
CI passing
E2E passing
N/A
N/A

serverless throws 404 when model was not found

---

inference/core/models/roboflow.py
inference/usage_tracking/collector.py

We currently have a permanent key in the cache which is set when model validation fails 3 times. We want to make this more flexible by expiring the key every minute instead. Sometimes errors can happen in bursts, and this leads to permanent model blocking in the current code.
Testing in staging

Added 60s cache expiry for invalid models

---

inference/usage_tracking/collector.py

Adding a floor for the recorded execution duration of a frame for usage purposes on Roboflow's hosted serverless platform.
Operational change
Testing in staging and running tests first. Then checking usage tables.

Adding a floor of 100ms for GCP_SERVERLESS

---

inference/core/workflows/core_steps/models/foundation/moondream2/v1.py

Change Moondream2 Workflow `long_description` property from tuple to string. Otherwise it doesn't show up in the workflow editor:
Ran inference locally and pointed the editor to localhost, to validate that the description shows up properly.
No

Fix Moondream2 Workflow long_description. Should be string, not tuple.

---

docs/quickstart/devices.md
inference/core/interfaces/http/http_api.py

- fix `compatibility` spelling in HTTP API comments
- update `devices.md` text to use `compatibility`
- `make check_code_quality` *(fails: flake8 not installed)*
- `pytest tests/inference/unit_tests` *(fails: pytest not installed)*

Fix compatibility typos

---

inference/core/managers/metrics.py
tests/inference/unit_tests/core/managers/test_metrics.py

- ensure `get_system_info` has one return statement
- add tests for `get_system_info`
- `python3 -m pytest tests/inference/unit_tests/core/managers/test_metrics.py -q` *(fails: No module named pytest)*

Fix single return in get_system_info

---

inference/core/workflows/core_steps/transformations/perspective_correction/v1.py
requirements/requirements.transformers.txt

When running perspective correction on video with option to extend perspective polygon, perspective transformation matrix should be recalculated for each frame.
CI passing
N/A
N/A

Recalculate perspective transformation matrix for each frame if extended

---

app_bundles/osx/launcher.c.txt

as part of app bundling code we added a c source file.  its just in the repo for reference (tiny binary compiled from it is also included for the build)
however, this makes the autpomated codeQL scanner unhappy, which fails with error:
```
Exit code was 32 and last log line was: CodeQL detected code written in C/C++ but could not automatically build any of it
```
We can probably change the github repo settings to do manual/advanced config for the code scanning tool, but for right now I think easier to just rename this file so it gets ignored since its just here for reference and resolves the issue that CI is reporting error on main 
n/a
n/a
n/a

Fix CodeQL scan

---

inference/core/interfaces/stream_manager/manager_app/webrtc.py

Silence 'swscaler No accelerated colorspace conversion found from yuv420p to bgr24' warnings
-   [x] QoL
CI passing
Manually tested
When running webrtc pipeline, warnings below are no longer produced:
```log
[swscaler @ 0x118060000] No accelerated colorspace conversion found from yuv420p to bgr24.
```
N/A
N/A

silcence libav swscaler warnings

---

inference/core/workflows/core_steps/formatters/json_parser/v1.py
tests/workflows/integration_tests/execution/test_workflow_json_parser_config.py
tests/workflows/unit_tests/core_steps/formatters/test_json_parser.py

This PR is generated by OpenAI Codex
I don't think it actually resolved the issue that the input selector isn't properly getting converted to the json from that ref, but might be a good starting point to try to fix the issue.  More context on the bug and request for it on roboflow internal slack here: https://roboflow.slack.com/archives/C06BD36S37A/p1746462559704149
- allow JSON Parser to accept raw strings or selectors
- test manifest handling of plain string input
- exercise json_parser block in integration test
- `make style`
- `make check_code_quality` *(fails: flake8 missing)*
- `pytest tests/workflows/unit_tests/core_steps/formatters/test_json_parser.py::test_parsing_manifest_when_raw_json_is_plain_string` *(fails: pytest not installed)*
- `pytest …

Fix JSON parser for direct strings

---

inference/core/interfaces/camera/video_source.py
inference/core/interfaces/stream_manager/manager_app/entities.py

RTMP streaming is currently producing chunky footage, looking like below:
Fixed this by switching default strategy, ensuring proper output stream management when feeding frames and also spared function calls when it can be avoided early. Result. Queue filling strategy should result in dropping oldest frame, and queue consuming strategy should be picking one frame from the queue (and not purge the whole queue) to avoid chunky results on fast workflows but also to ensure pipeline performs well on slow workflows
CI passing
Manually tested:
```python
import cv2 as cv
from inference.core.interfaces.camera.video_source import VideoSource, VideoFrame, BufferFillingStrategy, BufferConsumptionStrategy
rtmp_video_source: VideoSource = …
```

Fix RTMP lack of smoothness

---

inference/core/workflows/core_steps/transformations/dynamic_zones/v1.py

In case when no dynamic zone is found, this block fails with error due to missing output keys in block result. When dynamic zone was not found, return empty result with all keys.
CI passing
N/A
N/A

When dynamic zone was not found, return empty result

---

inference/core/workflows/core_steps/common/deserializers.py
tests/workflows/unit_tests/core_steps/common/test_deserializers.py

Update the image deserializer to check for parent_id property in case it is given. Also add new unit tests for `deserialize_image_kind`.
Locally, using the workflows UI:
https://github.com/user-attachments/assets/e11bd220-69f1-4417-bbc7-56f80f4d4ce9
No

Respect image parent_id property when deserializing

---

inference/core/workflows/execution_engine/entities/base.py

Add fix for the problem with setting default value of `WorkflowParameter` as dict which was not passing validation
* e2e locally

Add fix for the problem with JSON object as default vaule for `WorkflowParameter`

---

inference/core/interfaces/stream_manager/manager_app/app.py

Revert timeout when waiting for response from inference pipeline
Tested manually
N/A
N/A

Revert timeout when waiting for response from inference pipeline

---

docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1

Install libsqlite3-dev before building python3.9 on jetson 4.6.1
CI passing
Test manually by running `docker run -it --rm roboflow/roboflow-inference-server-jetson-4.6.1:latest`
N/A
N/A

Install libsqlite3-dev before building python3.9 on jetson 4.6.1

---

inference/models/depth_estimation/__init__.py
requirements/requirements.transformers.txt

The depth estimator test was breaking bc the depth estimator init was importing smolvlm2, which was broken. Now both things are fixed. Accelerate==0.31 was breaking things. This fix is necessary to make sure florence2 models run successfully in inference after https://github.com/roboflow/roboflow-train/pull/555 was merged.
Built locally and linked actions
no

Bump peft with fixed dependencies

---

inference/core/workflows/core_steps/sinks/onvif_movement/v1.py

Change flip_y_movement default to true
Added/changed some comments and description
I ordered a lower end Reolink E1 Zoom camera to test with the block. While the ONVIF commands worked fine, the camera doesn't have variable speed and at full speed it just kept shooting past the object. I found a way to get it to work by sending it a series of rapid move and stop commands. It's crude, definitely not ideal, but should enable a lot of lower end cameras to work with the block.
-   [x ] New feature (non-breaking change which adds functionality)
I've tested ONVIF capability with 3 camera brands - Foscam, ANPVIZ and Reolink. I haven't been …

Add variable speed simulation

---

inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py

If `None` is sent as selected stream output, pick first available stream output and provide on-stream error message
example workflow:
```json
{
"version": "1.0",
"inputs": [
{
"type": "InferenceImage",
"name": "image"
}
],
"steps": [
{
"type": "roboflow_core/perspective_correction@v1",
"name": "perspective_correction",
"images": "$inputs.image",
"perspective_polygons": [
[
332,
457
],
[
163,
131
],
[
547,
130
],
[
379,
459
]
],
"warp_image": true
}
],
"outputs": [
{
"type": "JsonField",
"name": "perspective_correction",
"coordinates_system": "own",
"selector": "$steps.perspective_correction.*"
}
]
}
```
CI passing
N/A
N/A

When wildcard output is specified, `None` is sent as stream output - pick first video output

---

.github/workflows/integration_tests_inference_experimental_gpu.yml
inference_experimental/inference_exp/__init__.py
inference_experimental/inference_exp/models/common/onnx.py
inference_experimental/tests/integration_tests/models/test_clip_predictions.py
inference_experimental/tests/integration_tests/models/test_perception_encoder_predictions.py

Proper handling of MPS in torch for `rfdetr`
* CI 
* e2e tests on macbook

Apply changes such that MPS is correctly supported for `rfdetr`, yet still remain non-default for MacOS

---

inference/core/interfaces/camera/video_source.py
inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py
inference/core/interfaces/stream_manager/manager_app/webrtc.py
inference/core/version.py

Remove 'Workflow is heavy' message
add latency logging
Use incoming frame time when sending resulting frame back
CI passing
manually tested on localhost and on DD
N/A
N/A

Webrtc latency for heavy workflows

---

docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1
docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1
docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1.stream_manager
docker/dockerfiles/Dockerfile.onnx.jetson.6.0.0
inference/core/version.py

On jetsons we need to force numpy 1.26.4 installation due to inference-cli installation
CI passing
N/A
N/A

Fix/force numpy 1.26.4 on jetson dockers

---

inference/core/workflows/execution_engine/v1/dynamic_blocks/block_scaffolding.py

When a dynamic python block breaks execution, enrich the error message with the proper breaking line number and function name.
Follows the python standard:
```
File "<string>", line 22, in my_bad_func
ZeroDivisionError: division by zero
```
But without filename, since it's just a string.
Locally using a miscoded python block in workflows. And also with a proper working one to ensure valid blocks still work.
Python block:
Current error message:
Improved error message:
none

Add line number and function name information to dynamic block errors

---

.github/actions/determine-tags/action.yml

.github/actions/determine-tags/action.yml was not handling `vaa.bb.cc` correctly (but was handling `vaa.bb.c`) - adjusting regular expression.
CI passing
N/A
N/A

When version number is aa.bb.cc, script was not removing leading 'v'

---

inference/core/managers/base.py

Enhance error handling in ModelManager caching logic by adding try-except blocks to log failures when caching inference and error data. This improves robustness and provides better insights into potential issues during caching operations. We had an issue previously where this Redis instance filled up and it was causing inference to fail. This prevents that from happening. We'd rather have model monitoring be missing some data than inference fail entirely.
[ENT-200](https://linear.app/roboflow/issue/ENT-200/make-model-monitoring-redis-cache-storage-fault-tolerant)
This should be a low level change. Tested locally by running …

Fault tolerant redis calls for model monitoring

---

inference/core/workflows/core_steps/models/foundation/anthropic_claude/v1.py

Update list of models in the Anthropic Claude workflow block.
- add Claude Opus 4.1
- add Claude Opus 4
- add Claude Sonnet 4
- Tested pointing workflows to inference running locally, and running the Anthropic block
- Tested all new models
N/A
N/A

Add Claude Opus 4 and Claude Sonnet 4 models

---

inference/models/owlv2/owlv2.py
tests/inference/unit_tests/models/test_owlv2_max_detections.py

Add support for limiting the number of detections returned by OWLv2 models. The `max_detections` parameter is now properly enforced after NMS by trimming results to the specified limit.
- Added unit test to verify max_detections enforcement after NMS
- Test validates that results are correctly trimmed to specified limit
N/A
N/A

Support max detections for OWLv2 models

---

inference/core/models/classification_base.py
inference/core/models/roboflow.py
inference/models/clip/clip_model.py
inference/models/gaze/gaze.py
inference/models/rfdetr/rfdetr.py
inference/models/sam/segment_anything.py
inference/models/yolact/yolact_instance_segmentation.py
inference/models/yolonas/yolonas_object_detection.py
inference/models/yolov10/yolov10_object_detection.py
inference/models/yolov5/yolov5_instance_segmentation.py
inference/models/yolov5/yolov5_object_detection.py
inference/models/yolov7/yolov7_instance_segmentation.py
inference/models/yolov8/yolov8_instance_segmentation.py
inference/models/yolov8/yolov8_keypoints_detection.py
inference/models/yolov8/yolov8_object_detection.py
inference/models/yolov9/yolov9_object_detection.py
tests/inference/unit_tests/models/test_owlv2_max_detections.py
tests/inference/unit_tests/usage_tracking/test_collector.py
tests/workflows/unit_tests/core_steps/transformations/test_qr_code_generator.py
tests/workflows/unit_tests/core_steps/visualizations/test_icon_alpha.py

In the core of inference, we were exposed on unsafe multi-thread execution of operations against ONNX sessions - which on GPU could lead to CUDA runtime errors. This PR is adding instance-level thread locks on all ONNX sessions of all inference models.
* CI

Add model-instance level thread lock on accessing ONNX session to avoid GPU execution concurrency issues

---

inference/core/interfaces/http/dependencies.py
inference/core/interfaces/http/http_api.py
inference/core/version.py

PR with fix of the bug related to handling requests body in legacy infer endpoint.
* locally
* CI still 🟢 

Fix bug with improper parsing multipart-request causing reading the request body stream twice

---

inference/core/interfaces/http/http_api.py

Serve workflows schema gzipped.
Schema is a ~1.9MB text file. Compressed it'll be ~140KB.
Manually checked the page and compared output sizes with curl: 141kb x 1839kb.
```
iurisilvio@Mac functions % curl "http://localhost:9001/workflows/definition/schema" --compressed > /dev/n
ull
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  141k  100  141k    0     0   977k      0 --:--:-- --:--:-- --:--:--  981k
iurisilvio@Mac functions % curl "http://localhost:9001/workflows/definition/schema" > /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 1839k  100 1839k    0 …
```

Gzip workflows schema

---

inference/core/models/instance_segmentation_base.py

`source` is not recorded when inferring on instance segmentation models. This PR is adjusting instance segmentation infer to include `**kwargs` like in other models.
CI passing
Manually tested
N/A
N/A

Record source when inferring on instance segmentation models

---

docker/dockerfiles/Dockerfile.onnx.cpu
docker/dockerfiles/Dockerfile.onnx.cpu.dev
docker/dockerfiles/Dockerfile.onnx.cpu.parallel
docker/dockerfiles/Dockerfile.onnx.cpu.slim
docker/dockerfiles/Dockerfile.onnx.cpu.stream_manager
docker/dockerfiles/Dockerfile.onnx.gpu
docker/dockerfiles/Dockerfile.onnx.gpu.dev
docker/dockerfiles/Dockerfile.onnx.gpu.parallel
docker/dockerfiles/Dockerfile.onnx.gpu.slim
docker/dockerfiles/Dockerfile.onnx.gpu.stream_manager
docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1
docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1
docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1.stream_manager
docker/dockerfiles/Dockerfile.onnx.jetson.6.0.0
docker/dockerfiles/Dockerfile.onnx.jetson.6.2.0
docker/dockerfiles/Dockerfile.onnx.trt
docker/dockerfiles/Dockerfile.onnx.udp.gpu
docker/dockerfiles/Dockerfile.stream_management_api

bumps base cpu python docker images to python 3.11
gpu images already come with python 3.10
only thing < python 3.10 after this is jetson 4.6 and 5.11 images.  we already install python 3.9 manually in those (they come with 3.8 out of box)...so maybe can change that to 3.10 or 3.11 but will need to also adjust other installed dependencies compiled specifically for 3.9 on there like:
- onnxruntime_gpu-1.16.0-cp39-cp39-linux_aarch64.whl
- zxing_cpp_library_compiled_for_inference_v0.12.1.tar.gz (5.11)
maintanance
WIP
n/a
n/a

bump base cpu images from python3.9 -> 3.11

---

inference/core/entities/requests/moondream2.py
inference/core/workflows/core_steps/models/foundation/moondream2/v1.py

`moondream2` model expects 'prompt' as one of the params, 'text' is not recognized
`Moondream2InferenceRequest` inherits from `DynamicClassBaseInferenceRequest` which defines `text` as part of its interface; adding `prompt`
```json
{
"version": "1.0",
"inputs": [
{
"type": "InferenceImage",
"name": "image"
}
],
"steps": [
{
"type": "roboflow_core/moondream2@v1",
"name": "moondream",
"images": "$inputs.image",
"prompt": "dog"
},
{
"type": "roboflow_core/bounding_box_visualization@v1",
"name": "bounding_box_visualization",
"image": "$inputs.image",
"predictions": "$steps.moondream.predictions"
}
],
"outputs": [
{
"type": "JsonField",
"name": "bounding_box_visualization",
"coordinates_system": "own",
"selector": …
```

Extend Moondream2InferenceRequest to include 'prompt'

---

.github/workflows/build-windows-installer.yml

github runner runs Wondows 2025 as latest windows runner as of Sept 2. which breaks our build as seen here: https://github.com/roboflow/inference/actions/runs/17493688863
This sets the runner to use the previous runner version which will remain supported for another 3 years 
build fix
running build of of branch
n/a
n/a

use Windows-2022 runner for windows build

---

inference/core/interfaces/http/http_api.py

This endpoint should not be require api key
locally
n/a
n/a

don't auth /model/registry endpoint via api_key on serverless

---

inference/core/workflows/core_steps/visualizations/polygon_zone/v1.py

While testing video processing locally, I got an exception on PolygonZoneBlock about an undefined variable.
The exception said:
`File "/Users/digao/dev/inference/inference/core/workflows/core_steps/visualizations/polygon_zone/v1.py", line 124, in run                                                                                         
img=mask,                                                                                                                                                                                                       
^^^^                                                                                                                                                                                                        
UnboundLocalError: cannot access local …

fixing memory leak and variable not associated value on PolygonZoneBlock

---

docs/start/getting-started.md

Fix "Getting Started" docs to display correct Python version requirement. Use the `python_requires` value from the `.release/pypi` release scripts, that are used to created the actual pypi package.
Locally
n/a
-   [x] Docs updated? What were the changes: fix python version in getting started page

Fix "Getting Started" python version requirement

---

inference/core/entities/responses/ocr.py
inference/core/interfaces/http/http_api.py
inference/core/interfaces/http/orjson_utils.py
inference/core/version.py

Yet another fix to 0.57.x release - this time with retaining parent id response
* ci
* e2e test

Retain empty 'parent_id' field in OCR response

---

inference/core/env.py
inference/core/models/roboflow.py
inference/core/version.py
inference/models/rfdetr/rfdetr.py

RFDetr models take up lots of RAM when input resolution is high and when running through ONNX runtime. Limiting RFDetr input resolution to ensure sane RAM usage.
CI passing
Tested manually
N/A
N/A

Limit rfdetr input resolution when loading through onnx

---

inference/core/env.py
inference/core/version.py
inference/models/rfdetr/rfdetr.py

Based on measured vRAM usage:
1280 -> ~3.5G
1440 -> ~5G
1600 -> ~10G
2048 -> ~22G
CI passing
N/A
N/A

Increase default rfdetr resolution limit

---

inference/core/env.py
inference/core/interfaces/http/http_api.py
inference/core/version.py

In [this change](https://github.com/roboflow/inference/pull/1546/commits/8694051d019e4171c8257309b174190df2362b95) the lower bound limit on confidence was removed in order to ensure correct MAP calculation. This has adverse effect of high RAM usage when running model evaluation.
CI passing
N/A
N/A

Prevent accepting 0 as confidence due to resulting high memory requirement
