docs/CNAME
=> Docs CNAME

.github/workflows/test.yml
Changed branch to correct name in github action test.yml
=> Fix Regression Tests

LICENSE
This adds copy noting that each model in `inference/models/` has its own `LICENSE` which may be different from the rest of the code in this repo.
Not needed, copy change.
Not needed, copy change.
-   [x] Docs updated? What were the changes: this is the documentation update.
=> Clarify Licensing

docker/dockerfiles/Dockerfile.onnx.lambda, docker/publish/README.md, inference/core/version.py, inference/models/utils.py
Add new value to registry
Locally
=> Add to registry

.github/workflows/docker.gpu.yml, .github/workflows/docker.jetson.5.1.1.yml, .github/workflows/docker.jetson.yml, .github/workflows/docker.trt.yml, .github/workflows/publish.pypi.yml
Fixed some bugs in the publishing actions that were not caught during local testing.
Tested via hosted github actions on a separate branch. See https://github.com/roboflow/inference/actions to see successful runs of each action from the `fix/actions-fix` branch.
=> Publish Actions Fix

README.md
Added an explainer image for the inference process and the general concepts.
- Added a image and a new section to the docs
=> Added an explainer image for the inference process

inference/core/version.py
Increase the version from 0.7.6 to 0.7.7 after adding gaze detection function.
=> version up

requirements/requirements.gaze.txt
Loosened the requirements for gaze core model.
=> Looser Gaze Requirements

.release/pypi/inference.core.setup.py, README.md, inference/models/clip/clip_model.py, inference/models/sam/segment_anything.py, requirements/requirements.clip.txt, requirements/requirements.sam.txt
Updated requirements for SAM and CLIP to use pypi packages instead of github repos, added both to setup.py as extras, added both to README.
Tested locally and with gh actions.
=> SAM + CLIP Requirements Update

inference/core/utils/image_utils.py
Updated exception logic to accept single channel numpy str
=> Accept Single Channel Numpy Str

.release/pypi/inference.core.setup.py, README.md, inference/core/data_models.py, inference/core/env.py, inference/core/interfaces/udp/udp_stream.py, inference/core/utils/image_utils.py, inference/core/version.py, inference/models/clip/clip_model.py, inference/models/sam/segment_anything.py, requirements/_requirements.txt, requirements/requirements.clip.txt, requirements/requirements.sam.txt
Release includes:
- Optional Byte Track for UDP interface
- Updated SAM and CLIP requirements and added README quickstarts
- Bug fix for single channel numpy strings
=> Release `0.8.1`

.github/workflows/docker.jetson.4.6.1.yml, docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1
Added an image for Jetpack 4.6.1
=> Added an image for Jetpack 4.6.1

docker/dockerfiles/Dockerfile.onnx.jetson.4.5.0, inference/core/data_models.py, inference/core/interfaces/http/http_api.py, inference/core/models/classification_base.py, inference/core/models/instance_segmentation_base.py, inference/core/models/object_detection_base.py, inference/core/models/roboflow.py, inference/core/utils/postprocess.py, inference/core/utils/preprocess.py, inference/core/version.py
Added ability to disable preprocs per request
Automated regression testing
=> Disable Preprocs Per Request

.github/workflows/test.yml, .release/pypi/inference.cpu.setup.py, .release/pypi/inference.gpu.setup.py, .release/pypi/inference.setup.py, Makefile, inference/core/models/instance_segmentation_base.py, inference/core/models/object_detection_base.py, inference/core/models/roboflow.py, inference/core/utils/image_utils.py, inference/core/version.py
Release `0.8.4`
Includes:
- #40 
- #44 
- #45
=> Release 0.8.4

.release/pypi/inference.cpu.setup.py, .release/pypi/inference.gpu.setup.py, .release/pypi/inference.setup.py, inference/core/version.py
Some extras were not propagated to all setup.py files.
=> Fix for Missing Extras

inference/core/models/instance_segmentation_base.py, inference/core/models/object_detection_base.py, inference/core/models/roboflow.py, inference/core/utils/image_utils.py
Multi thread image loading for batch requests
Tested locally and with GH actions
=> Multi-Thread Image Loading

.github/workflows/test.yml, Makefile
Changing regression tests so that they run on a github runner
Tested with this PR
=> Regression Tests on GH Runner

examples/README.md, examples/gaze-detection/README.md, examples/gaze-detection/gaze.py
This PR adds a script with all you need to use the Roboflow Inference gaze detection API.
This change adds an example and does not affect the functionality of the core project.
This project was tested manually by verifying that the gaze direction and points were correcet.
N/A
=> Add gaze detection example

inference/core/version.py
Adds a check for latest version in version.py, which prints a recurring warning if the current version doesn't match.
=> Feature/ Warn user when using an outdated version of the inference server

.github/workflows/docker.device_manager.yml, .github/workflows/test.yml, .gitignore, docker/config/device_manager.py, docker/dockerfiles/Dockerfile.device_manager, docker/dockerfiles/Dockerfile.onnx.lambda, docs/index.md, inference/core/cache/__init__.py, inference/core/cache/base.py, inference/core/cache/memory.py, inference/core/cache/redis.py, inference/core/devices/utils.py, inference/core/env.py, inference/core/interfaces/http/http_api.py, inference/core/logger.py, inference/core/managers/base.py, inference/core/managers/metrics.py, inference/core/managers/pingback.py, inference/core/models/roboflow.py, inference/core/version.py, inference/enterprise/device_manager/command_handler.py, inference/enterprise/device_manager/container_service.py, inference/enterprise/device_manager/device_manager.py, inference/enterprise/device_manager/helpers.py, inference/enterprise/device_manager/metrics_service.py, inference/enterprise/device_manager/version.py, requirements/_requirements.txt, requirements/requirements.device_manager.txt
- Adds the enterprise device manager for remote control and pingback
- Adds redis cache with in-memory to share state
Not tested yet
=> Feature/Device Management v1

inference/core/managers/base.py, inference/enterprise/device_manager/container_service.py
- Removing pingback check
- Remove metrics_enabled check
YOUR_ANSWER
=> Remove metrics_enabled check

.github/workflows/docker.cpu.yml, .github/workflows/docker.device_manager.yml, .github/workflows/docker.gpu.udp.yml, .github/workflows/docker.gpu.yml, .github/workflows/docker.jetson.4.5.0.yml, .github/workflows/docker.jetson.4.6.1.yml, inference/core/__init__.py, inference/core/utils/image_utils.py, inference/core/version.py
Fixed the usage of imread flags in image_utils. Also fixed version file so that GH actions don't fail. Also removed white space from GH workflow yamls.
=> Hot Fix for Imread Flags and GH Actions

.github/workflows/publish.pypi.yml
=> Fix Automated Pypi Deploy

inference/core/models/roboflow.py
Fixed accidental channel swap in visualization code
=> Visualization Channel Swap Bug Fix

inference/core/cache/memory.py
Fixed bug in MemoryCache logic where the expiration cleanup thread was not being started (and contained some bugs after we started running it)
Tested with constant stream of requests while watching htop. Memory holds constant after initial allocation.
=> MemoryCache Expire Logic Bug Fix

docker/dockerfiles/Dockerfile.onnx.cpu, docker/dockerfiles/Dockerfile.onnx.gpu, docker/dockerfiles/Dockerfile.onnx.lambda, docker/dockerfiles/Dockerfile.onnx.trt, docker/dockerfiles/Dockerfile.onnx.udp.gpu, requirements/_requirements.txt
Pillow 10.0.1 contains a security update. This change updates our dependency to include that. 
=> Update Pillow Dependency to <11.0

docker/config/cpu_http.py, docker/config/lambda.py, docker/config/trt_http.py, inference/core/interfaces/http/http_api.py, inference/core/managers/base.py, inference/core/managers/decorators/base.py, inference/core/managers/decorators/fixed_size_cache.py, inference/core/managers/decorators/logger.py
Model manager has a registry and is responsible for getting new models
=> Model manager now is responsible for looking up models in registry

inference/core/version.py
Version bump for release 0.9.3
=> Release 0.9.3 version bump

.github/workflows/test.cpu.yml, .github/workflows/test.jetson_4.5.1.yml, .github/workflows/test.jetson_4.6.1.yml, .github/workflows/test.jetson_5.1.1.yml, .github/workflows/test.nvidia_t4.yml
=> GH Actions Checkout Fix

inference/models/doctr/doctr_model.py
Added dataset_id and version_id to DocTR for pingback
=> Added dataset_id and version_id to DocTR for pingback

inference/models/doctr/doctr_model.py
Fixed the clear cache functionality in new doctr model
=> DocTR Model Clear Cache Fix

docs/quickstart/compatability_matrix.md, mkdocs.yml
This PR creates a stub model compatibility matrix where we can share on what devices each model type works. All of the values are placeholders. I will defer to @paulguerrie to fill out the boxes.
=> Add compatability matrix template

.github/workflows/publish.pypi.yml, Makefile
Fixed the automated pypi deploys
=> Fixed the automated pypi deploys

docs/library/data_models/clip/clip_compare_request.md, docs/library/data_models/clip/clip_image_embedding_request.md, docs/library/data_models/clip/clip_inference_request.md, docs/library/data_models/clip/clip_text_embedding_request.md, docs/library/data_models/inference/classification.md, docs/library/data_models/inference/cv_inference_request.md, docs/library/data_models/inference/inference_request_image.md, docs/library/data_models/inference/instance_segmentation.md, docs/library/data_models/inference/object_detection.md, docs/library/data_models/sam/sam_embedding_request.md, docs/library/data_models/sam/sam_segmentation_request.md
Fixed broken docs links for entities
=> Fixed broken docs links for entities

.github/workflows/test.cpu.yml, .github/workflows/test.jetson_4.5.0.yml, .github/workflows/test.jetson_4.6.1.yml, .github/workflows/test.jetson_5.1.1.yml, .github/workflows/test.nvidia_t4.yml
Update automated tests for more reliable docker builds.
=> Use Simple Docker Commands in Tests

inference/core/managers/base.py, tests/inference/unit_tests/core/managers/test_base.py
Removed missing model exception when attempting to remove a model
Unit and regression tests
=> No Exception Raised By Model Manager Remove Model

docker/dockerfiles/Dockerfile.onnx.lambda, inference/core/models/roboflow.py
Some bug fixes for hosted inference. This enables DocTR to run on ourhosted endpoint.
Tested on staging and with automated regression tests.
=> Hosted Inference Bug Fixes

examples/clip-search-engine/app.py, examples/clip-search-engine/requirements.txt, examples/clip-search-engine/templates/index.html
This PR fixes the CLIP image search example.
-   [X] Docs change (fixing an example)
This change was tested by running the following command on a test dataset, then ensuring the web application works as expected:
```
python3 app.py --dataset_path=data --inference_endpoint=https://infer.roboflow.com --api_key=[key]
```
N/A
N/A
=> Fix CLIP example

inference/core/__init__.py
=> Fix outdated warning with 'inference' upgrade suggestion

inference/core/env.py, inference/core/roboflow_api.py, tests/inference/unit_tests/core/test_roboflow_api.py
Providing true implementation for Active Learning configuration getter.
YOUR_ANSWER
=> Add true implementation for AL configuration getter

docs/quickstart/http_inference.md, inference/core/managers/base.py
Fixed a bug when using numpy as input. Also update docs for numpy requests
Addresses https://github.com/roboflow/inference/issues/155
=> Bug Fix for Numpy Inputs

inference/core/active_learning/README.md
=> Add development documentation of Active Learning

docs/quickstart/http_inference.md
Updated http quickstart docs to include snippets for V2 and V1 routes. Also made clear what was available/not available for each type of route.
=> Updated HTTP Quickstart

docker/dockerfiles/Dockerfile.onnx.cpu, docker/dockerfiles/Dockerfile.onnx.cpu.parallel, docker/dockerfiles/Dockerfile.onnx.cpu.slim, docker/dockerfiles/Dockerfile.onnx.gpu, docker/dockerfiles/Dockerfile.onnx.gpu.parallel, docker/dockerfiles/Dockerfile.onnx.gpu.slim
Upgraded wheel and setuptools based on JFrog vulnerability scans
=> Wheel and Setuptools Upgrade

docker/dockerfiles/Dockerfile.onnx.cpu, docker/dockerfiles/Dockerfile.onnx.cpu.parallel, docker/dockerfiles/Dockerfile.onnx.cpu.slim, docker/dockerfiles/Dockerfile.onnx.gpu, docker/dockerfiles/Dockerfile.onnx.gpu.parallel, docker/dockerfiles/Dockerfile.onnx.gpu.slim
Using multi-stage build so that intermediate layer vulnerabilities get removed in the final image
=> Multi-Stage Builds

.dockerignore, inference/core/interfaces/http/http_api.py, inference/enterprise/parallel/README.md, requirements/_requirements.txt, requirements/requirements.parallel.txt
Reverts roboflow/inference#166
=> Revert "Peter/orjson"

docker/dockerfiles/Dockerfile.onnx.gpu.parallel
Get parallel dockerfile to same base image as the main dockerfile
Locally
No
=> Bump cuda version for parallel

docs/quickstart/explore_models.md, inference/core/models/roboflow.py, inference/core/registries/roboflow.py, inference/models/aliases.py, tests/inference/unit_tests/models/test_aliases.py
With this PR, aliases on popular models from universe are introduced.
Please double check aliases table with:
* https://universe.roboflow.com/microsoft/coco
* https://universe.roboflow.com/microsoft/coco-dataset-vdnr1
* unit tests
* e2e tests in python package and inference server
=> Introduce model aliases

Makefile, inference/core/version.py, inference_cli/lib/container_adapter.py
=> Fix problem with device request not being list but tuple

.github/workflows/test.cpu.yml, Makefile, docs/index.md, inference_cli/README.md, inference_cli/lib/container_adapter.py, inference_cli/main.py, inference_cli/server.py, tests/inference_cli/integration_tests/test_server.py, tests/inference_cli/unit_tests/lib/test_container_adapter.py
Adding `inference server stop` command to kill inference container.
* suite of tests
* e2e running of command
=> Add inference server stop command

docs/theme/main.html, mkdocs.yml
This PR adds ZoomInfo to the Inference documentation.
Adding a script to the documentation.
This change can be tested by checking for the presence of the ZoomInfo script on the site when served locally with `mkdocs serve`.
N/A
N/A
=> Add ZoomInfo integration

docker/config/lambda.py, inference/core/active_learning/configuration.py, inference/core/interfaces/http/http_api.py, inference/core/managers/base.py, inference/core/managers/decorators/fixed_size_cache.py, inference/core/version.py, tests/inference/unit_tests/core/active_learning/test_configuration.py
=> Wrap lambda deployment with AL model manager

docs/foundation/cogvlm.md, docs/inference_sdk/http_client.md, tests/inference_sdk/unit_tests/http/test_client.py
Fix typo in docs/test  from CogLVM to CogVLM
Not tested, docs only
Docs only
-   [X] Docs updated? 
- docs only change
=> fix typo coglvm -> cogvlm

inference/core/managers/active_learning.py, inference/core/version.py
=> Fix issue with AL disable flag

inference/core/cache/__init__.py, inference/core/cache/base.py, inference/core/cache/redis.py, inference/core/interfaces/http/http_api.py, inference/core/logger.py, inference/core/managers/base.py, inference/core/version.py
=> Enable more detailed logging

inference/core/models/roboflow.py, inference/core/registries/roboflow.py, inference/core/version.py, tests/inference/unit_tests/core/interfaces/camera/test_video_source.py, tests/inference/unit_tests/core/interfaces/stream/test_sinks.py, tests/inference/unit_tests/core/registries/test_roboflow.py, tests/inference/unit_tests/enterprise/stream_management/manager/test_inference_pipeline_manager.py
We had problems with caching in redis - some not needed locks and lack of expiry timeout.
YOUR_ANSWER
=> Fix problems with caching

.github/workflows/test.nvidia_t4.yml, Makefile, docker/dockerfiles/Dockerfile.onnx.gpu, tests/inference/integration_tests/speed_regression_test.py
Fixed a bug in the gpu dockerfile which was causing onnxruntime to be installed and supress onnxruntime-gpu
=> Fixed a bug in the gpu dockerfile which was causing onnxruntime to be

inference_cli/cloud.py, inference_cli/lib/__init__.py, inference_cli/lib/cloud_adapter.py, inference_cli/lib/deploy_adapter.py, inference_cli/main.py, requirements/requirements.cli.txt
Adding inference cli deploy container to cloud providers.
Deploy Roboflow Inference to a cloud provider.
If your chosen cloud provider is configured on your terminal, inference 
deploy will automatically use your default credentials. If you have not 
configured your cloud provider, you can do so by following the instructions 
for installing and configuring the cloud provider's CLI tools.
Roboflow inference deploy  will create a new virtual machine 
and deploy the Roboflow Inference container to it.
Usage examples:
inference cloud deploy --provider gcp --compute-type cpu
inference cloud deploy --provider aws --compute-type gpu
inference cloud stop <deployment-name>
inference cloud start <deployment-name>
inference cloud status
inference cloud undeploy <deployment-name>
ssh …
=> Adding inference deploy

docs/inference_helpers/inference_cli.md
Documentation for inference cloud deploy.
Documentation
N/A documentation only
=> Added docs for inference cloud deploy

inference/core/version.py, inference_sdk/http/client.py
=> Deduct API key from message

inference/core/version.py, inference/enterprise/workflows/complier/steps_executors/models.py
=> Fix problem with single-image input to workflows OCR step

inference/core/version.py, inference_sdk/http/client.py
=> Fix problem with API key leaking in errors

inference/core/cache/redis.py
Inference cache sleep bugfix
Staging
x
=> sleep bugfix

inference/core/entities/requests/inference.py
Fixed an error caught by regression tests for the parallel GPU container
Regression tests
=> Fixed a key error with request IDs

inference/core/utils/hash.py, inference/core/version.py, inference/models/yolo_world/yolo_world.py
=> Make yolo-world infer BGR

docker/dockerfiles/Dockerfile.onnx.lambda.slim, docker/publish/onnx_lambda.sh
Build script change to make it possible to create and deploy slim lambda
Load test on staging
Discussed on slack
=> Adjust build scripts to slim lambda build

inference/core/version.py, inference/enterprise/workflows/complier/steps_executors/models.py, tests/inference/unit_tests/enterprise/workflows/compiler/steps_executors/test_models.py
=> Prepare for 0.9.14 release

inference/core/interfaces/stream/inference_pipeline.py, inference/core/interfaces/stream/model_functions.py, tests/inference/unit_tests/enterprise/workflows/entities/test_steps.py
Added ability to run yolo-world models in inference pipelines
Tested locally
=> YOLO-World Inference Pipeline

requirements/_requirements.txt, requirements/requirements.http.txt
Move struct log to core requirements.
=> Struct Log Dependency Fix

docs/quickstart/docker.md
Updates docker docs to include instruction for windows networking.
n/a
=> Update the Docker documentation to include note on windows networking

inference/models/README.md, inference/models/cogvlm/LICENSE.txt, inference/models/gaze/LICENSE_l2cs.txt, inference/models/gaze/LICENSE_mediapipe.txt, inference/models/yolo_world/LICENSE.txt, inference/models/yolonas/LICENSE.txt, inference/models/yolov9/LICENSE.txt
More clearly lists & links to the various licenses for supported models.
Non-functional change; just a documentation update.
No deploy necessary.
-   [x] Docs updated? What were the changes: the changes in this PR are the documentation update.
=> License Cleanup

inference_cli/server.py, requirements/requirements.cli.txt
Switching to opencv-python-headless addresses the libGL.so.1 error encountered in headless environments by eliminating the dependency on GUI-related libraries that OpenCV's standard version requires. The headless variant of OpenCV is specifically compiled without these graphical components, making it ideal for server or Docker environments where graphical interfaces are absent. This solution directly tackles the issue by removing the need for the missing libraries, rather than attempting to add unnecessary graphical support to a headless setup. It ensures that applications utilizing OpenCV for image processing or computer vision tasks can operate smoothly without encountering errors related to graphics libraries, thus maintaining functionality while adhering to the constraints of the …
=> Updated requirements.cli.txt to resolve bug #315

docs/foundation/grounding_dino.md, inference/core/entities/requests/groundingdino.py, inference/core/utils/image_utils.py, inference/models/grounding_dino/grounding_dino.py
- Allows users to pass custom `box_threshold` and `text_threshold` params to Grounding DINO core model.
- Update docs to reflect `box_threshold` and `text_threshold` params.
- Fixes error by filtering out detections where text similarity is lower than `text_threshold` and Grounding DINO returns `None` for class ID.
- Fixes images passed to Grounding DINO model being loaded as RBG instead of BGR.
- Adds NMS to Grounding DINO, optionally using class agnostic NMS via `CLASS_AGNOSTIC_NMS` env var.
-   ✅  Bug fix (non-breaking change which fixes an issue)
-   ✅  New feature (non-breaking change which adds functionality)
-   ✅  This change requires a documentation update
- Tested Grounding DINO inference API with and without new `box_threshold` and …
=> Grounding DINO enhancements and bugfixes

inference/core/version.py
=> Bump version

inference/core/version.py, inference/enterprise/workflows/entities/steps.py
Close #344 
-   [ ] in-code docs update
N/A
N/A
N/A
=> Update description for workflows steps

inference_cli/lib/benchmark/api_speed.py, inference_cli/lib/benchmark/results_gathering.py
Close #350
-  [x] New feature (non-breaking change which adds functionality)
Executed benchmark:
```
python -m inference_cli.main benchmark api-speed (...)
```
N/A
N/A
=> Add error status code to benchmark output

tests/inference/integration_tests/batch_regression_test.py, tests/inference/integration_tests/clip_test.py, tests/inference/integration_tests/doctr_test.py, tests/inference/integration_tests/gaze_test.py, tests/inference/integration_tests/populate_expected_responses_batch.py, tests/inference/integration_tests/regression_test.py, tests/inference/integration_tests/sam_test.py, tests/inference/integration_tests/speed_regression_test.py, tests/inference/models_predictions_tests/test_yolo_world.py, tests/inference/unit_tests/core/utils/test_postprocess.py
Add more test cases to increase coverage for `post_process_polygons`
N/A
N/A
N/A
=> Add more test cases to cover tests/inference/unit_tests/core/utils/test_postprocess.py::post_process_polygons

inference/models/gaze/gaze.py
Bugfix for gaze detection (batch request)
Tested locally
If possible, we should push docker images to docker hub ASAP, and update our vfa server.
=> Bugfix for gaze detection (batch request)

inference_cli/lib/benchmark/api_speed.py, inference_cli/lib/benchmark/results_gathering.py
Improve benchmark output
fix exception handling
benchmark test was executed in condition where fix could be tested.
N/A
N/A
=> Improve benchmark output; fix exception handling

requirements/requirements.cli.txt
Updated SkyPilot to make the installation faster.
Tested building locally, as well as tried the inference cloud deploy commands work with the updated skypilot version.
=> Upped skypilot version

inference/core/version.py, requirements/requirements.groundingdino.txt
Lock and upgrade Grounding DINO version to incorporate the changes in https://github.com/roboflow/GroundingDINO
-   ✅  Bug fix (non-breaking change which fixes an issue)
-   ✅  New feature (non-breaking change which adds functionality)
=> Lock Grounding DINO package version to 0.2.0

inference/core/version.py, inference/core/workflows/core_steps/fusion/detections_consensus.py, inference/core/workflows/core_steps/models/foundation/clip_comparison.py, inference/core/workflows/core_steps/models/foundation/yolo_world.py
Fixing small bugs detected before deploying to hosted prod.
* tested stability on staging as usual
* manually verified that change is compliant with new UI
We are deploying changes in hosted platform and in UI at the same time
=> Apply fixes before deployment into hosted platform

inference/core/version.py
=> Bump version for releases

inference/core/version.py, inference/core/workflows/core_steps/models/foundation/yolo_world.py
1. bump version to v0.11.3
2. fix format warning
=> bump version to v0.11.3

inference/core/version.py
New release of `inference` with changes from `main`
* Regression tests on:
* Jetson 4.5 - ⚪ skipped, no hardware
* Jetson 4.6 - 🟢  [run](https://github.com/roboflow/inference/actions/runs/9415262078)
* Jetson 5.1 - ⚪ skipped, no hardware, runner died
* T4 - 🟢  [run](https://github.com/roboflow/inference/actions/runs/9415269257)
* e2e tests on hosted platform: 🟢 
=> Release `v0.12.0`

CODEOWNERS
Add myself to codeowners
Meta-change
n/a
n/a
n/a
=> Add peter to codeowners

docs/fine-tuned/yolov10.md, docs/fine-tuned/yolov9.md, docs/workflows/about.md, docs/workflows/create_and_run.md, docs/yolov8.md, mkdocs.yml
This PR adds a YOLOv10 documentation page and removes unused pages.
- Documentation change
N/A
N/A
N/A
=> Workflow documentation additions, add YOLOv10 docs

docs/fine-tuned/yolov10.md, docs/quickstart/run_model_on_rtsp_webcam.md
Changed Yolov9 with Yolov10 on the documentation page.
=> Fixing yolov10 documentation

docs/quickstart/run_model_on_rtsp_webcam.md
replaces sv.BoxAnnotator() with sv.LabelAnnotator() and sv.BoundingBoxAnnotator() for the run_model_on_rstp_webcam example
=> Supervision updates for Predict on a Video, Webcam or RTSP Stream Page

inference/models/aliases.py, inference_sdk/http/utils/aliases.py
Add aliases for a bunch of paligemma pretrains I uploaded.
locally
n/a
=> Add paligemma aliases for newly uploaded models

docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1.stream_manager
There was an issue with build for one of docker image, applied fix that helped for other jetson5.1 build
YOUR_ANSWER
* Applied fix that was tested for other build
* 
=> Fix issue with stream manager docker build

inference/core/workflows/execution_engine/compiler/steps_initialiser.py, tests/workflows/unit_tests/execution_engine/compiler/test_steps_initialiser.py
Show block name in error message thrown by steps_initialiser
Unit tests
N/A
N/A
=> Show block name in error message thrown by steps_initialiser

CODEOWNERS
adding myself to codeowners to allow PR review approvals to merge
repo permissions
n/a
=> add hansent to codeowners

.github/workflows/load_test_hosted_inference.yml, .github/workflows/test.nvidia_t4.yml, .github/workflows/test.nvidia_t4_parallel_server.yml
Adding GHA to simplify load tests / e2e tests for hosted API
* by running actions
=> Add GH actions for load tests of hosted inference and add docker logs on failure of integration tests

.github/workflows/load_test_hosted_inference.yml
Fixing problem with input definitions for GHA
* run of action
=> Fix load tests inputs

.github/workflows/hosted_inference_e2e_test_production.yml, .github/workflows/hosted_inference_e2e_test_staging.yml, .github/workflows/integration_tests_inference_server_x86.yml, requirements/requirements.test.integration.txt, requirements/requirements.test.unit.txt, tests/inference/hosted_platform_tests/conftest.py, tests/inference/hosted_platform_tests/test_core_models.py, tests/inference/hosted_platform_tests/test_roboflow_models.py, tests/inference/hosted_platform_tests/test_workflows.py
With this PR we automate E2E tests of hosted inference.
* running tests
=> E2E tests for inference @ hosted platform

.github/workflows/hosted_inference_e2e_test_production.yml, .github/workflows/hosted_inference_e2e_test_staging.yml, .github/workflows/prod_build_and_push_hosted_inference_image.yml, .github/workflows/staging_build_and_push_hosted_inference_image.yml, tests/inference/hosted_platform_tests/conftest.py
There was small issue with dependencies not installed for GHA - fixed
* running action
=> Fix the problem with e2e tests

inference/core/interfaces/stream/sinks.py, inference_cli/lib/infer_adapter.py, pytest.ini, tests/workflows/integration_tests/execution/stub_plugins/dimensionality_manipulation_plugin/tile_detections_batch.py, tests/workflows/integration_tests/execution/stub_plugins/dimensionality_manipulation_plugin/tile_detections_non_batch.py
Reverts roboflow/inference#528
=> Revert "Fail tests on supervision warnings"

.github/workflows/load_test_hosted_inference.yml, inference_cli/benchmark.py, inference_cli/lib/benchmark/api_speed.py, inference_cli/lib/benchmark_adapter.py
Extend inference-cli to enable user to perform load test on workflows
Through CI
N/A
N/A
=> Add workflow benchmark

inference/core/workflows/core_steps/loader.py, inference/core/workflows/core_steps/models/foundation/cogvlm.py, inference/core/workflows/core_steps/models/foundation/lmm.py, inference/core/workflows/core_steps/models/foundation/openai.py, tests/workflows/unit_tests/core_steps/models/foundation/test_cogvlm.py, tests/workflows/unit_tests/core_steps/models/foundation/test_openai.py
In this PR:
- Created the OpenAI and CogVLM block
- Wrote tests from the new blocks
- Mark the LMM block as deprecated
locally, and tested CogVLM on Maxwell's remote GPU
=> Separate the LMM block into OpenAI and CogVLM

inference/core/version.py, inference/core/workflows/core_steps/transformations/perspective_correction.py
Allow zone defined as input parameter to be passed to perspective_correction
$inputs.static_zone was passed to perspective correction block
```python
from inference.core.managers.base import ModelManager
from inference.core.registries.roboflow import RoboflowModelRegistry
from inference.core.roboflow_api import get_workflow_specification
from inference.core.workflows.core_steps.common.entities import StepExecutionMode
from inference.core.workflows.execution_engine.core import ExecutionEngine
from inference.models.utils import ROBOFLOW_MODEL_TYPES
workflow_id = "my-workflow-id"
workspace_id = "my-workspace"
api_key = "secret"
workflow_specification = get_workflow_specification( …
```
=> Allow zone defined as input parameter to be passed to perspective_correction

docs/server_configuration/environmental_variables.md, inference/core/models/roboflow.py, mkdocs.yml
Address #369
-   [x] documentation update
N/A
N/A
-   [x] Minor change in docs - added environmental variables section and specified `ONNXRUNTIME_EXECUTION_PROVIDERS` in there
=> Add documentation for ONNXRUNTIME_EXECUTION_PROVIDERS

inference/core/workflows/core_steps/models/foundation/lmm/v1.py, inference/core/workflows/core_steps/models/foundation/lmm_classifier/v1.py, inference/core/workflows/core_steps/models/foundation/openai/v1.py
Add a `private` property to the OpenAI fields. Will be used to hide in the UI and to strip property when sharing workflows
Ran unit tests
Nope
=> Workflow private block properties

.github/workflows/test_package_install_inference_gpu_with_extras.yml, .github/workflows/test_package_install_inference_with_extras.yml, .release/pypi/inference.core.setup.py, .release/pypi/inference.cpu.setup.py, .release/pypi/inference.gpu.setup.py, .release/pypi/inference.setup.py, docs/foundation/paligemma.md, docs/models.md
Adds new extras install which install pytorch and other necessary dependencies for florence2, paligemma, and other transformers packages
Locally
New extras wheel to be built
=> Add transformers extras

.github/workflows/test_package_install_inference_gpu_with_extras.yml, .github/workflows/test_package_install_inference_with_extras.yml, .release/pypi/inference.core.setup.py, .release/pypi/inference.cpu.setup.py, .release/pypi/inference.gpu.setup.py, .release/pypi/inference.setup.py, docs/foundation/paligemma.md, docs/models.md
Reverts roboflow/inference#575
=> Revert "Add transformers extras"

inference/core/workflows/core_steps/formatters/property_definition/v1.py, inference/core/workflows/core_steps/models/foundation/segment_anything2/v1.py
- Updated the description and search metadata for the Sam2 and Property Extraction blocks 
-   [X] Usability 
locally
nope
n/a
=> Workflow block search metadata

inference/core/entities/requests/workflows.py, inference/core/workflows/execution_engine/core.py, inference/core/workflows/execution_engine/entities/engine.py, inference/core/workflows/execution_engine/v1/core.py, inference/usage_tracking/collector.py
Add optional internal `is_preview` property to `/workflows/run` request
Record is_preview=True when running workflow preview in Roboflow app.
CI
N/A
N/A
=> Track preview workflows

inference/usage_tracking/collector.py
Fallback API key extraction for UsageCollector
CI
N/A
N/A
=> Fallback API key extraction for UsageCollector

tests/inference/hosted_platform_tests/test_roboflow_models.py
There was minor bug in assertions for integration tests regarding adding `inference_id` to CLS model response
* tests itself passed
=> Fix integration tests

inference/core/utils/sqlite_wrapper.py, inference/usage_tracking/sqlite_queue.py, tests/inference/unit_tests/core/utils/test_sqlite_wrapper.py, tests/inference/unit_tests/usage_tracking/test_persistent_queue.py
Add support for DELETE in sqlite wrapper
Added new unit tests to cover new functionality, all relevant unit tests are passing
N/A
N/A
=> Add support for DELETE in sqlite wrapper

inference/usage_tracking/collector.py, inference/usage_tracking/payload_helpers.py, inference/usage_tracking/redis_queue.py, inference/usage_tracking/utils.py, tests/inference/unit_tests/usage_tracking/test_collector.py
Do not merge payloads containing distinct exec_session_id when processing streams
Test added, tests are passing
N/A
N/A
=> Keep distinct exec sessions for inf pipeline usage

.github/workflows/docs.yml, .github/workflows/test_package_install_inference_gpu_with_extras.yml, development/docs/workflows_gallery_builder.py, docs/workflows/create_and_run.md, docs/workflows/gallery_index.md, tests/workflows/integration_tests/execution/test_workflow_detection_plus_classification.py, tests/workflows/integration_tests/execution/test_workflow_with_active_learning_sink.py, tests/workflows/integration_tests/execution/test_workflow_with_camera_focus.py, tests/workflows/integration_tests/execution/test_workflow_with_clip.py, tests/workflows/integration_tests/execution/test_workflow_with_contours_detection.py, tests/workflows/integration_tests/execution/test_workflow_with_counting_pixels_with_dominant_color.py, tests/workflows/integration_tests/execution/test_workflow_with_detection_plus_ocr.py, tests/workflows/integration_tests/execution/test_workflow_with_detections_classes_replacement_by_specialised_classification.py, tests/workflows/integration_tests/execution/test_workflow_with_detections_consensus_block.py, tests/workflows/integration_tests/execution/test_workflow_with_dominant_color.py, tests/workflows/integration_tests/execution/test_workflow_with_filtering.py, tests/workflows/integration_tests/execution/test_workflow_with_flow_control.py, tests/workflows/integration_tests/execution/test_workflow_with_model_running_on_absolute_static_crop.py, tests/workflows/integration_tests/execution/test_workflow_with_property_extraction.py, tests/workflows/integration_tests/execution/test_workflow_with_sahi.py, tests/workflows/integration_tests/execution/test_workflow_with_sam2.py, tests/workflows/integration_tests/execution/test_workflow_with_sift.py, tests/workflows/integration_tests/execution/test_workflow_with_single_model.py, tests/workflows/integration_tests/execution/test_workflow_with_sorting.py, tests/workflows/integration_tests/execution/test_workflow_with_stitch_for_dynamic_crop.py, tests/workflows/integration_tests/execution/workflows_gallery_collector/decorators.py
Update that uses new extension of backend to render preview iframes for docs examples
* e2e - outcomes of script
=> Add runnable examples to workflows docs

requirements/requirements.pali.flash_attn.txt, requirements/requirements.transformers.txt
Fix trying to install xformers (only needed for paligemma)
locally, tests
no
=> Move xformers to paligemma code

inference/core/workflows/core_steps/loader.py, inference/core/workflows/core_steps/visualizations/line_zone/v1.py, tests/workflows/unit_tests/core_steps/visualizations/test_line_counter_zone.py
Add block for visualizing line counter zone
Unit tests added
N/A
N/A
=> Add line counter visualization block

docs/enterprise/active-learning/active_learning.md, docs/enterprise/active-learning/classes_based.md, docs/enterprise/active-learning/close_to_threshold_sampling.md, docs/enterprise/active-learning/detection_number.md, docs/enterprise/active-learning/random_sampling.md, docs/foundation/clip.md, docs/index.md, docs/inference_helpers/inference_sdk.md, docs/models/from_local_weights.md, docs/server_configuration/environmental_variables.md, docs/using_inference/inference_pipeline.md, docs/using_inference/native_python_api.md, docs/workflows/create_workflow_block.md, docs/workflows/custom_python_code_blocks.md, docs/workflows/workflows_execution_engine.md, inference/core/interfaces/stream/inference_pipeline.py, tests/workflows/unit_tests/core_steps/classical_cv/test_sift_comparison_v2.py
Fixed SEO issues with docs raised by @capjamesg 
* E2E verified
=> Fix docs links

.github/workflows/hosted_inference_e2e_test_production.yml, .github/workflows/hosted_inference_e2e_test_staging.yml
Added secrets to run VLM tests during e2e hosted platform tests
* CI 🟢 
=> Add secrets to integration tests

development/docs/workflows_gallery_builder.py
We need to add query param to the iframe to display workflows in "old" style
* E2E test
=> Fix workflows gallery previews

inference/core/version.py, inference/core/workflows/core_steps/analytics/line_counter/v1.py, inference/core/workflows/core_steps/visualizations/line_zone/v1.py, tests/workflows/unit_tests/core_steps/visualizations/test_line_counter_zone.py
Update names and metadata for several line counter & line counter visualization properties
locally
n/a
n/a
=> Line counter improvements

.github/workflows/integration_tests_inference_server_x86.yml, setup.py
Dev env enhancement
* CI still 🟢 
=> Add `transformers` extra to dev setup py

docs/fine-tuned/yolonas.md, docs/fine-tuned/yolov10.md, docs/fine-tuned/yolov5.md, docs/fine-tuned/yolov7.md, docs/fine-tuned/yolov8.md, docs/fine-tuned/yolov9.md, docs/index.md, docs/quickstart/licensing.md
=> Fix license link in docs

inference/core/workflows/core_steps/loader.py
Fixing issue with export of block in loader
* CI still 🟢 
=> Add path deviation block

CONTRIBUTING.md, docs/workflows/create_workflow_block.md
In this PR we improve contribution guides:
* main contribution - to contain information on what to expect from our CI that currently fails on external contributions + how to test locally without issues
* Workflows blocks creation guide - to provide self-contained and complete step-by-step description of env setup for smooth development
* only updates in docs, not in the code
=> Improvements in contribution guides

inference/core/interfaces/http/http_api.py, inference/core/managers/metrics.py
Reverts roboflow/inference#717 - breaking CI build
=> Revert "Add Prometheus CPU/GPU custom metrics and latency"

inference/core/interfaces/http/http_api.py, inference/core/managers/metrics.py, requirements/requirements.gpu.txt
- Effectively bringing back roboflow/inference#717 and fixing CI build
* CI works again
=> Bring back Prometheus GPU

docs/quickstart/aliases.md, inference/core/version.py, requirements/requirements.cpu.txt, requirements/requirements.gpu.txt, requirements/requirements.vino.txt
Increase minimum onnx version for IR 9 support for yolov11
Add yolov11 coco models to aliases page
locally, will test with automated tests
no
=> yolov11 improvements

tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_google_ocr.py
Fixing test as we are double-compressing image and small regions may not be detected as in case of our python package test
* fixing CI to be 🟢 
=> Fix platform tests

inference/core/version.py, inference_sdk/http/utils/aliases.py
Yolov11 aliases need to be added to sdk as well
Tested locally
Deployed to hosted and tested with a workflow
Will need to redeploy hosted
=> Add yolov11 aliases to sdk

.github/workflows/docker.cpu.slim.yml, .github/workflows/docker.cpu.yml, .github/workflows/integration_tests_inference_server_x86.yml, tests/inference/hosted_platform_tests/test_workflows.py, tests/inference/integration_tests/test_workflow_endpoints.py
Fixing assertion error in tests
Reverting changes from #700 and #740 - cc: @alexnorell 
* CI green locally 
=> Fix integration tests before release

README.md, docs/index.md, inference_cli/README.md
Commit 4423a0dc05d6d41b37314d3e1847b8c5d9c8a19c renamed the license file. This PR adjusts sources to changes.
Documentation
=> Update license reference

inference/core/interfaces/http/http_api.py
Quickfix for docker stats
* CI green
* E2E tests on staging
=> Remove metrics endpoint

development/workflows_examples/video_analysis/aggregating_objects_passing_data.py, inference/core/workflows/core_steps/formatters/property_definition/v1.py, inference/core/workflows/core_steps/sinks/email_notification/v1.py
Fix to make it possible to attach binary files into e-mail notifications
* e2e test
* CI still 🟢 
=> Apply fixes to allow for binary attachments in e-mail block

inference/core/interfaces/http/http_api.py, inference/usage_tracking/collector.py
Passes whether usage is billable to usage collector. 
Passes automated tests and on staging hosted API -- sent requests w/ and w/o countinference param.
None
=> Pass countinference to usage collector

inference/usage_tracking/collector.py
=> Include resource_details.billable in workflows usage

.github/workflows/test_package_install_inference_gpu.yml
Remove debug step from 'Test package install - inference-gpu'
CI passing
N/A
N/A
=> Remove debug step from 'Test package install - inference-gpu'

inference/models/transformers/transformers.py, inference/models/utils.py
App saves file in .tar.gz format, plus adds new dataset type "text-image-pairs"
tested thouroughly on staging
no
=> Serve florence2 models created by in app train

requirements/requirements.cli.txt
Security patch.
* CI green 🟢 
* e2e test of dependency resolution
=> Enforce vulnerability-free `crypthography` version

inference/core/version.py
Release branch 0.26.0
* standard testing prior release
=> Release `0.26.0`

inference/core/entities/requests/inference.py, inference/core/version.py
Add usage_billable to BaseRequest
CI passing
N/A
N/A
=> Add usage_billable to BaseRequest

inference/models/yolo_world/yolo_world.py
Remove reset from YOLO settings
CI passing
N/A
N/A
=> Remove reset from YOLO settings

inference/models/transformers/transformers.py
Catch subprocess called error and make sure we dont redownload florence2 base models
tested locally, ci
no
=> Florence 2 quick fixes

docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1.stream_manager, requirements/_requirements.txt, requirements/requirements.cli.txt, requirements/requirements.hosted.txt, requirements/requirements.jetson.txt, requirements/requirements.parallel.txt, requirements/requirements.sdk.http.txt
PR attempting to fix issues with dependencies
YOUR_ANSWER
=> Attempt to fix builds

inference/core/workflows/core_steps/visualizations/label/v1.py, tests/workflows/integration_tests/execution/test_workflow_with_label_visualization.py
Effectively fixing label visualization issue when empty detections provided
* CI still 🟢 
* new tests
=> Fix label visualization once again

inference/usage_tracking/collector.py
Set hosted to True when running on dedicated deployment
CI passing
N/A
N/A
=> Set hosted to True when running on dedicated deployment

inference/core/version.py
In preparation for release fixing https://github.com/roboflow/inference/issues/834
YOUR_ANSWER
=> Bump version to 0.28.1

inference/core/entities/responses/workflows.py, inference/core/workflows/execution_engine/v1/compiler/syntactic_parser.py
Reverting changes made in last PR w.r.t. schema entity - wanted to avoid warning, but made it wrong way
* CI
* e2e tested
=> Fix issue with workflows schema endpoint

.github/workflows/check_if_branch_is_mergeable.yml
Add workflow to check mergeable state executed on pull request. This is to enable testing on #846 
CI passing
N/A
N/A
=> Add workflow to check mergeable state executed on pull request

.github/workflows/check_if_branch_is_mergeable.yml
Make check_if_branch_is_mergeable.yml to succeed if merging to main
CI passing
N/A
N/A
=> Make check_if_branch_is_mergeable.yml to succeed if merging to main

requirements/requirements.yolo_world.txt
Pin Ultralytics version
Context: https://github.com/ultralytics/ultralytics/issues/18027
Security improvement.
Tested via automated tests.
=> Pin ultralytics version

inference/core/version.py
Release 0.29.2
Release
CI passing
e2e tests triggered
N/A
N/A
=> Release 0.29.2

requirements/_requirements.txt, requirements/requirements.test.unit.txt
Acting upon this issue: https://github.com/roboflow/inference/issues/860
* CI
=> Unpin `httpx`

.github/workflows/docs.yml
Fix docs builder CI
CI passing
N/A
N/A
=> Fix docs builder CI

inference/core/interfaces/stream_manager/manager_app/webrtc.py
Add poison pill to connectionstatechange in webrtc
e2e tested
N/A
N/A
=> Add poison pill to connectionstatechange in webrtc

inference/core/version.py
Increase version number to 0.30.0
N/A
CI Passing
N/A
N/A
=> Increase version number to 0.30.0

inference/core/version.py
We had an `__init__.py` bug again... 
* CI
=> Fix inference 0.30.0 release

tests/workflows/unit_tests/core_steps/test_init_files.py
Add test to detect blocks with missing __init__.py
CI passing
N/A
=> Add test to detect blocks with missing __init__.py

inference/core/workflows/core_steps/sinks/roboflow/custom_metadata/v1.py, inference/core/workflows/core_steps/sinks/slack/notification/v1.py
Update the block copy for the slack notification block. 
-   [X] Content 
locally
n/a
n/a
=> Update block copy

inference/core/entities/requests/gaze.py, inference/core/env.py, tests/workflows/integration_tests/execution/conftest.py, tests/workflows/integration_tests/execution/test_workflow_with_gaze.py, tests/workflows/unit_tests/core_steps/models/foundation/test_gaze.py, tests/workflows/unit_tests/core_steps/sampling/test_identify_changes.py, tests/workflows/unit_tests/core_steps/sampling/test_identify_outliers.py
There is flakyness in the block for outlier detection.
Since this is new block not breaking the ecosystem we are letting it in to the release, but the block needs to be fixed: https://github.com/roboflow/inference/issues/901
* CI
=> Skip additional test

inference/usage_tracking/collector.py
Correction to usage collector payload creation
N/A
N/A
N/A
=> Fix usage collector fps

development/docs/build_block_docs.py
Include a link to source code on individual block gallery / refference pages and improve the way it generates docs for blocks that have multiple versions
loom with overview of changes here:  https://www.loom.com/share/58dcf69fe5f84a548faea40d03b69bdf
documentation update
locally via running `build_block_docs.py` script and `mkdocs serve`
docs changes 
yes docs only
=> better version handling in generated block pages

inference/core/workflows/core_steps/loader.py, inference/core/workflows/core_steps/models/foundation/llama_vision/v1.py, tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/test_workflow_for_classification.py, tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v2/test_workflow_for_classification.py, tests/workflows/unit_tests/core_steps/sampling/test_identify_changes.py, tests/workflows/unit_tests/core_steps/sampling/test_identify_outliers.py
Initial quick fixes for LLAMA contribution to make CI pass
* CI
=> Fix/onboarding llama 3.2

.github/workflows/test_package_install_inference.yml, .github/workflows/test_package_install_inference_cli.yml, .github/workflows/test_package_install_inference_gpu.yml, .github/workflows/test_package_install_inference_gpu_with_extras.yml, .github/workflows/test_package_install_inference_sdk.yml, .github/workflows/test_package_install_inference_with_extras.yml, inference/core/workflows/core_steps/models/foundation/llama_vision/v1.py, inference/core/workflows/prototypes/block.py, tests/inference/unit_tests/core/test_roboflow_api.py, tests/workflows/integration_tests/execution/test_workflow_with_llama_vision.py, tests/workflows/unit_tests/core_steps/models/foundation/test_llama_3_2_vision.py, tests/workflows/unit_tests/execution_engine/executor/test_runtime_input_validator.py
Proving missing tests for LLama model
* new tests
* CI still 🟢 
=> Tests for LLama Vision 3.2

inference/usage_tracking/collector.py
Usage should be sent after execution of measured method is complete.
non-breaking change, CI passing
N/A
N/A
=> Send telemetry after execution of decorated method

inference/core/version.py
Release 0.33.0
N/A
N/A
N/A
N/A
=> Release 0.33.0

inference/core/models/classification_base.py, inference/models/__init__.py, inference/models/resnet/LICENSE.txt, inference/models/resnet/__init__.py, inference/models/resnet/resnet_classification.py, inference/models/utils.py
Added support for necessary classes and parameters for ResNet model family for classification.
N/A
Tested with a deploy on staging and a custom inference test.
N/A
-   [ ] Docs updated? What were the changes: N/A
=> Added ResNet Classification Model Support

inference/core/interfaces/http/http_api.py
Pass is_preview if available when handling workflow request
CI passing
N/A
N/A
=> Pass is_preview if available when handling workflow request

inference/core/entities/requests/workflows.py, inference/core/interfaces/http/http_api.py
Handle optional workflow_id if passed as part of request to /workflows/run
CI passing
tested manually E2E
N/A
N/A
=> Handle optional workflow_id if passed as part of request to /workflows/run

inference/core/version.py, tests/workflows/integration_tests/execution/test_workflow_with_stability_ai_generation.py
Add Stability-AI image generation workflow to workflows gallery
CI passing
New secret is expected to be passed through envs - WORKFLOWS_TEST_STABILITY_AI_KEY
N/A
=> Add Stability-AI image generation workflow to workflows gallery

.github/workflows/docs.yml
missing \ broke documentation build action
failed build:
https://github.com/roboflow/inference/actions/runs/12833771273/job/35789574182
no, will run as github action 
n/a 
n/a
=> fix requirement command in doc build workflow

docs/index.md
Needs quotes or it doesn't actually include the file.
Locally
Just docs
-   [x] Docs updated? What were the changes: This is the docs change
=> Docs: Fix Typo

inference/core/interfaces/http/http_api.py, inference/core/interfaces/stream/sinks.py, inference/core/workflows/execution_engine/v1/core.py, inference/usage_tracking/collector.py
Add logging when workflow ID is known and internal workflow ID was not passed
CI passing
N/A
N/A
=> Add logging when workflow ID is known and internal workflow ID was not passed

inference/core/interfaces/http/http_api.py, inference/core/interfaces/stream_manager/manager_app/entities.py, inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py, inference/core/version.py
Show guidance on preview if user needs to configure visual outputs in workflow
CI passing
E2E tested
N/A
N/A
=> Handle wildcard outputs in webrct

inference/core/interfaces/http/http_api.py
Handle models obtained through new getWeights endpoint
CI passing
tested on dedicated deployment
N/A
N/A
=> Simplify dedicated deployments authorizer middleware to rely on workspace ID match

requirements/_requirements.txt
New release of `aiortc` is breaking builds - fixing by pinning
* CI
=> HotFix for `aiortc` release breaking the build

inference/core/interfaces/http/http_api.py
block details was introduced to WorkflowSyntaxError, handle this exception before WorkflowDefinitionError is handled in http_api
CI passing; integration tests passing
N/A
N/A
=> Handle WorkflowSyntaxError separately from WorkflowDefinitionError

.github/workflows/check_model_licenses.yml, inference/models/README.md, inference/models/florence2/LICENSE.txt, inference/models/owlv2/LICENSE.txt, inference/models/paligemma/LICENSE.code.txt, inference/models/paligemma/LICENSE.weights.txt, inference/models/transformers/LICENSE.txt, inference/models/trocr/LICENSE.txt, inference/models/yolo_world/COPYRIGHT.txt, inference/models/yolov11/LICENSE.txt
Noticed our README had gotten out of date and some of the models in the `models` directory didn't have their LICENSE files included so cleaned those up and added a GitHub action that will enforce all new models include a license file and are added to the table.
Used the `act` CLI to test the action on the repo locally.
No deploy needed.
-   [x] Docs updated? What were the changes: This is the docs change.
=> Clean Up Model Licenses

inference/core/workflows/execution_engine/v1/executor/core.py
There is an error in pydantic error validation
* CI
=> Apply fix for pydnatic validation of error message

inference/core/interfaces/http/http_api.py
Fix e2e tests
CI passing
E2E tests passing
Tested manually
N/A
N/A
=> Fix e2e tests

README.md, docs/resources.md, docs/start/getting-started.md, docs/video-tutorials.md, docs/workflows/about.md, mkdocs.yml
Trevor provided some good feedback on the recent docs updates. This PR actions it.
With local `mkdocs serve`
Non-functional change, just docs
-   [x] Docs updated? What were the changes: This is the docs update
=> Action Docs Feedback

inference_cli/lib/roboflow_cloud/batch_processing/api_operations.py, inference_cli/lib/roboflow_cloud/batch_processing/core.py, inference_cli/lib/roboflow_cloud/batch_processing/entities.py
In this PR I am adding a change such that users can specify webhook URL to get notifications from Batch Processing.
* E2E tested
=> Add changes to make it possible to register WebHooks

inference/core/workflows/core_steps/common/query_language/entities/enums.py, inference/core/workflows/core_steps/common/query_language/operations/images/base.py, tests/workflows/integration_tests/execution/test_workflow_with_property_extraction.py
Aspect ratio operation  to ExtractImageProperty
Added an integration test
N/A
N/A
=> Aspect ratio operation

docs/workflows/execution_engine_changelog.md, inference/core/workflows/execution_engine/v1/core.py, tests/inference/integration_tests/test_workflow_endpoints.py
=> Update Workflows Changelog

.github/workflows/test.nvidia_t4.yml, inference/core/utils/onnx.py, requirements/requirements.transformers.txt, tests/common.py, tests/inference/integration_tests/batch_regression_test.py, tests/inference/integration_tests/qwen_test.py, tests/inference/integration_tests/regression_test.py, tests/inference/models_predictions_tests/test_vit.py, tests/inference/models_predictions_tests/test_yolonas.py, tests/inference/models_predictions_tests/test_yolov10.py, tests/inference/models_predictions_tests/test_yolov5.py, tests/inference/models_predictions_tests/test_yolov7.py, tests/inference/models_predictions_tests/test_yolov8.py
The way on how we were making assertions made integration tests CI to require core dependencies.
Tried to fix the issue
CI
=> Fix problem with assertions

.github/workflows/test.nvidia_t4_parallel_server.yml, inference_cli/cloud.py, tests/inference/hosted_platform_tests/test_workflows.py, tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/test_workflow_for_classification.py, tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/test_workflow_for_keypoints_detection.py, tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v2/test_workflow_for_classification.py, tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v2/test_workflow_for_keypoints_detection.py, tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_detection_and_crop.py, tests/inference/models_predictions_tests/conftest.py, tests/inference/models_predictions_tests/test_sam2.py, tests/inference/models_predictions_tests/test_vit.py, tests/inference/models_predictions_tests/test_yolo_world.py, tests/inference/models_predictions_tests/test_yolonas.py, tests/inference/models_predictions_tests/test_yolov10.py, tests/inference/models_predictions_tests/test_yolov5.py, tests/inference/models_predictions_tests/test_yolov7.py, tests/inference/models_predictions_tests/test_yolov8.py
=> Fix broken CI

.github/workflows/test.nvidia_t4_parallel_server.yml, inference/core/utils/onnx.py
=> Fix broken parallel GPU CI

inference/core/entities/responses/inference.py, inference/core/models/classification_base.py, inference/core/version.py, tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/test_workflow_for_classification.py, tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v2/test_workflow_for_classification.py, tests/workflows/integration_tests/execution/test_workflow_detection_plus_classification.py, tests/workflows/integration_tests/execution/test_workflow_inference_id_response.py, tests/workflows/integration_tests/execution/test_workflow_with_active_learning_sink.py, tests/workflows/integration_tests/execution/test_workflow_with_custom_expression_built_for_detections_with_specialised_classification.py, tests/workflows/integration_tests/execution/test_workflow_with_detections_classes_replacement_by_specialised_classification.py, tests/workflows/integration_tests/execution/test_workflow_with_property_extraction.py, tests/workflows/integration_tests/execution/test_workflow_with_two_stage_models_and_flow_control.py
Apply confidence when inferring on classification models
N/A
N/A
=> Apply confidence when inferring on classification models

inference/core/models/roboflow.py
Handle environment and classes embedded directly within getWeights payload
CI passing
E2E tested
N/A
N/A
=> Handle environment and classes embedded directly within getWeights payload

inference/core/env.py, inference/models/owlv2/owlv2.py, tests/inference/models_predictions_tests/test_owlv2.py
Reverts roboflow/inference#1026
Change breaks https://github.com/roboflow/inference/actions/runs/13454962647/job/37596877759
=> Revert "Add Background Compilation for OWLv2 Vision Model"

inference/core/env.py, inference/core/version.py, inference/models/__init__.py, inference/usage_tracking/config.py
This change is required to securely authorize usage reporting
CI
=> Add ability to inject metrics collector URL

inference/core/models/classification_base.py, inference/core/models/object_detection_base.py, inference/core/models/roboflow.py, inference/core/utils/preprocess.py, inference/models/yolact/yolact_instance_segmentation.py
=> Fix / do not check if torch is in dir()

inference/core/workflows/core_steps/loader.py, inference/core/workflows/core_steps/transformations/camera_calibration/v1.py, tests/workflows/integration_tests/execution/test_workflow_with_camera_calibration.py
Add block allowing user to remove frame distortions
CI passing
N/A
N/A
=> Camera calibration block

inference/core/version.py
Release 0.40.0
-   [x] Release
CI passing
E2E tests passing
Regression tests passing
N/A
N/A
=> Release 0.40.0

docs/guides/compare-models.md, docs/guides/count-things.md, docs/guides/detect-small-objects.md, docs/guides/hello-world.md, mkdocs.yml
Adds 3 quickstart guides:
* Hello World
* Compare Models
* Detect Small Objects (SAHI)
Just docs; ran through them a bunch of times on prod.
Just docs. (Detached mode still waiting on PR review in core app; basing this on the `loginless-builder` branch.)
-   [x] Docs updated? What were the changes: These are the docs updates.
=> First 3 Quickstart Guides

examples/camera-calibration/README.md, examples/camera-calibration/camera-coeffs.py, inference/core/version.py
Add utility to help with performing camera calibration
CI passing
N/A
README provided
=> Add camera calibration util

docs/workflows/batch_processing/about.md, inference/core/version.py, inference_cli/lib/roboflow_cloud/batch_processing/api_operations.py, inference_cli/lib/roboflow_cloud/batch_processing/core.py, inference_cli/lib/roboflow_cloud/batch_processing/entities.py, inference_cli/lib/roboflow_cloud/common.py, inference_cli/lib/roboflow_cloud/data_staging/api_operations.py, inference_cli/lib/roboflow_cloud/data_staging/entities.py, mkdocs.yml
Migration to new batch processing
* E2E against staging API
=> Migrate to new batch processing with CLI tool

.gitignore, inference/core/workflows/core_steps/fusion/detections_classes_replacement/v1.py, tests/workflows/unit_tests/core_steps/fusion/test_detections_classes_replacement.py
Fix 'Could not resolve class id for prediction' error when classification_predictions with empty 'predictions' was passed detections_classes_replacement
```python
import argparse
from getpass import getpass
from inference.core.managers.base import ModelManager
from inference.core.registries.roboflow import RoboflowModelRegistry
from inference.core.roboflow_api import get_workflow_specification
from inference.core.workflows.core_steps.common.entities import StepExecutionMode
from inference.core.workflows.execution_engine.core import ExecutionEngine
from inference.models.utils import ROBOFLOW_MODEL_TYPES
from inference.core.env import API_KEY
def parse_args() -> argparse.Namespace:
parser = argparse.ArgumentParser(
description="Run …
```
=> Fix 'Could not resolve class id for prediction'

inference/usage_tracking/decorator_helpers.py
Fix test_workflow_endpoints.py
N/A
N/A
N/A
=> Fix test_workflow_endpoints.py

docs/workflows/batch_processing/about.md, docs/workflows/batch_processing/integration.md, mkdocs.yml
Adding description of new features of BP + fixing minor issues.
* locally rendered the site
=> Update batch processing docs

inference/core/cache/model_artifacts.py, inference/core/managers/base.py, inference/core/managers/decorators/base.py, inference/core/managers/decorators/fixed_size_cache.py, inference/core/models/base.py, inference/core/models/roboflow.py
Reverts roboflow/inference#1071 due to failing tests:
https://github.com/roboflow/inference/actions/runs/13863657143/job/38797802159
=> Revert "Make LRU model cache cleanup from disk optional via environment variable"

inference/core/workflows/core_steps/fusion/detections_classes_replacement/v1.py, tests/inference/hosted_platform_tests/conftest.py
Fix E2E tests for detections_classes_replacement block
CI passing
N/A
N/A
=> Fix E2E tests for detections_classes_replacement block

tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/test_workflow_for_classification.py, tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v2/test_workflow_for_classification.py
Fix E2E tests assertions for tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/test_workflow_for_classification.py::test_multi_label_classification_workflow
N/A
N/A
=> Update E2E test assertions for test_multi_label_classification_workflow

tests/inference/models_predictions_tests/test_florence2.py
=> Adjust florence2 test

inference_cli/lib/cloud_adapter.py, requirements/requirements.cloud_deploy.txt
The inference cli cloud deploy was not working. This PR fixes that, and also upgrades skypilot.
=> Added missing function call to load sky

inference/core/workflows/execution_engine/introspection/schema_parser.py, tests/inference/models_predictions_tests/test_rfdetr_latency.py
There was slight, but breaking change in new `pydantic` making OpenAPI specs to look different for generic types.
* test are 🟢 again
=> Fix issue with BC on OpenAPI spec in `pydantic`

.github/workflows/probe_google_colab.yml, development/google_colab_ci/verify_colab_env.py
Fixing problem with lack of gcloud command.
* in GHA run
=> Add gcloud setup to CI

tests/inference/unit_tests/usage_tracking/test_collect_func_params.py
Cover collect_func_params with test
-   [x] Adding tests
CI passing
N/A
N/A
=> Cover collect_func_params with test

inference/core/env.py, inference/core/version.py, inference/models/utils.py
Blacklisting option for QWEN model
* CI
=> Add env variable to block QWEN

inference/core/workflows/core_steps/common/query_language/entities/enums.py, inference/core/workflows/core_steps/common/query_language/operations/frame_metadata/base.py, tests/workflows/integration_tests/execution/test_workflow_with_property_extraction.py
Add seconds_since_start to PropertyDefinition extract_frame_metadata
CI passing
test extended
N/A
N/A
=> Add seconds_since_start to PropertyDefinition extract_frame_metadata

docs/workflows/batch_processing/about.md, docs/workflows/batch_processing/api_reference.md, docs/workflows/batch_processing/batch_processing_swagger.json, docs/workflows/batch_processing/data_staging_swagger.json, mkdocs.yml
Docs update - swagger with API docs for batch processing and data staging.
* just a docs update
=> Add Swagger for Batch Processing and Data Staging services

docs/workflows/batch_processing/about.md, docs/workflows/batch_processing/api_reference.md, docs/workflows/batch_processing/data_staging_swagger.json
Yet another update of BP docs:
* video with overview
* update of swagger with missing endpoint
* descriptions of batches types
-   [s] New feature (non-breaking change which adds functionality)
* just docs update
=> Batch Processing docs update

inference/core/version.py
Bump a version before release.
* not needed
=> Bump version to `0.46.2`

docs/scripts/gen_ref_pages.py
We had this empty pages in docs, now we don't
* e2e generated docs and verified manually
=> Remove modules without any doscrtings from docs

docker/dockerfiles/Dockerfile.onnx.cpu, docker/dockerfiles/Dockerfile.onnx.cpu.dev, docker/dockerfiles/Dockerfile.onnx.cpu.parallel, docker/dockerfiles/Dockerfile.onnx.cpu.slim, docker/dockerfiles/Dockerfile.onnx.cpu.stream_manager, docker/dockerfiles/Dockerfile.stream_management_api, requirements/_requirements.txt
=> Loose wheel back

inference/core/version.py
Bump version for deployment
YOUR_ANSWER
No
-   [ ] Docs updated? What were the changes: No
=> version bump

docs/workflows/batch_processing/known_issues.md, mkdocs.yml
Docs update about BP issues
* CI green
=> Add docs about known issues with batch processing

inference_cli/lib/benchmark/api_speed.py
Assume no execution_time on error
CI passing
N/A
N/A
=> Assume no execution_time on error

CODEOWNERS, inference/core/version.py
minor version bump to publish package and docker images with bugfix for florence on windows
minor version bump
n/a
n/a
n/a
=> bump version 0.46.5

inference/models/utils.py
Fixing issue with import on main.
* CI
=> Fix broken depth estimation import

tests/inference/integration_tests/test_depth_estimation_block.py
Small fix for deoth-estimator tests.
* CI
=> Remove unused import from depth-estimation test module

inference/core/workflows/core_steps/models/foundation/openai/v2.py
Add support for the latest gpt-4 model versions: gpt-4.1, gpt-4.1-mini and gpt-4.1-nano.
Run inference locally and tested on a workflow all model versions agains all task types.
no
=> Update list of supported OpenAI models

inference/core/env.py, inference/core/roboflow_api.py
Add INTERNAL_WEIGHTS_URL_SUFFIX
CI passing
N/A
N/A
=> Add INTERNAL_WEIGHTS_URL_SUFFIX

docs/workflows/batch_processing/data_staging_swagger.json, inference_cli/lib/roboflow_cloud/data_staging/api_operations.py
Removing left-over after alpha-release of data staging.
* CI
* removal of unused code
=> Remove stale data staging export

inference/core/cache/lru_cache.py, inference/core/managers/decorators/fixed_size_cache.py
1. Add gc
2. Prevent flapping by removing multiple models not just 1
Tested on staging.
=> Improvements to GC for GPU memory 

inference/core/interfaces/http/http_api.py, inference/core/interfaces/stream/stream.py, inference/core/logger.py, inference/core/managers/pingback.py
improve gcp logging
CI passing
tested on staging
N/A
N/A
=> Add correlation ID to stack traces when running on GCP

inference/core/managers/base.py, inference/core/managers/decorators/fixed_size_cache.py, inference/core/roboflow_api.py
Add authorized cache to WithFixedSizeCache model manager and to ModelManager
Tested locally and on staging
MODELS_CACHE_AUTH_ENABLED must be set to `True` in order to enable this feature
N/A
=> Add authorized cache to WithFixedSizeCache model manager and to ModelManager

inference/core/logger.py
Enforce JSON oriented logs
* e2e
* ci
=> Add fully JSON-oriented logger with proper stacktrace formatting

inference/core/workflows/core_steps/transformations/dynamic_zones/v1.py
Fix dynamic zones reduction
CI passing
N/A
N/A
=> Fix dynamic zones reduction

inference/core/version.py, inference/core/workflows/core_steps/transformations/perspective_correction/v1.py, tests/workflows/unit_tests/core_steps/transformations/test_perspective_correction.py
Add `ALL` as extra option accepted by `extend_perspective_polygon_by_detections_anchor` in perspective correction block
Add corrections to perspective zone extension
CI passing
New tests added
N/A
N/A
=> Add contour extension option to perspective converter

inference/core/workflows/core_steps/transformations/perspective_correction/v1.py
Fix detections anchor for 'ALL' position
CI passing
manually tested
N/A
N/A
=> Fix detections anchor for 'ALL' position

.github/workflows/codeflash.yml, .github/workflows/integration_tests_workflows_x86.yml
Fixing bug in conditions to prevent running CI from forks
* e2e (after merge)
=> Fix condition in if statement

inference/core/workflows/core_steps/common/serializers.py, inference/core/workflows/core_steps/transformations/dynamic_zones/v1.py, tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_detection_and_crop.py
Handle the case when vertices reduction algorithm results in too many vertices
CI passing
N/A
N/A
=> Handle the case when vertices reduction algorithm results in too many vertices

inference/__init__.py, inference/core/workflows/core_steps/visualizations/keypoint/v1.py
Pass custom edges mapping to KeypointVisualizationBlockV1
CI passing
N/A
N/A
=> Pass custom edges mapping to KeypointVisualizationBlockV1

inference/core/interfaces/http/http_api.py, inference/core/managers/base.py, inference/core/managers/decorators/base.py, inference/core/managers/decorators/fixed_size_cache.py, inference/core/managers/decorators/locked_load.py, inference/core/managers/decorators/logger.py, inference/core/managers/stub_loader.py, inference/core/version.py, inference/core/workflows/core_steps/common/utils.py, inference/enterprise/parallel/dispatch_manager.py
Pass endpoint type to model manager add_model
CI passing
E2E passing
N/A
N/A
=> Pass endpoint type to model manager add_model

inference/core/workflows/core_steps/models/foundation/google_gemini/v1.py, tests/workflows/integration_tests/execution/test_workflow_with_gemini_models.py
Resubmitting https://github.com/roboflow/inference/pull/1278 from abelriboulot account
=> Fixing CLA for gemini models stuff

inference/core/version.py, inference_sdk/http/utils/executors.py
Also do back-off on the inference SDK for 504 status code.
Tested in staging.
=> Added retry to 504 status

docs/workflows/modes_of_running.md, docs/workflows/workflows_compiler.md
Fixes a small typo in the docs
Not needed, non-functional change to the docs
No, just docs change
-   [x] Docs updated? What were the changes: This PR is them
=> Fix documentation typo

requirements/requirements.cli.txt
- ensure there's only one rich dependency by removing the old requirement
-   [ ] This change is a documentation update
GH Actions
Normal release
-   [ ] Docs updated? What were the changes: not needed
fix #1082
=> Fix stale rich requirement

AGENTS.md
Adds [an AGENTS.md file](https://openai.com/index/introducing-codex/#:~:text=Codex%20can%20be%20guided%20by%20AGENTS.md%20files) for agentic workflows like OpenAI Codex to use to orient themselves.
Not needed, non-functional
Only documentation update
-   [x] Docs updated? What were the changes: this is them
=> Add AGENTS.md guide

docs/workflows/about.md, docs/workflows/blocks_connections.md, docs/workflows/create_and_run.md, docs/workflows/custom_python_code_blocks.md, docs/workflows/modes_of_running.md, docs/workflows/understanding.md, docs/workflows/video_processing/overview.md
Updates the wording of the Workflows documentation to flow more naturally.
Not needed, non-functional
Only documentation update
-   [x] Docs updated? What were the changes: this is them
=> Improve Workflows docs writing

inference/usage_tracking/payload_helpers.py
Comment in payload helpers
-   [x] documentation
N/A
N/A
N/A
=> Comment in payload helpers

development/codex/README.md, development/codex/setup.sh
Adds documentation of how to configure your OpenAI Codex environment for use with this repo.
Non-functional change, just documentation
No
-   [x] Docs updated? What were the changes: This is the documentation update
=> Document Codex Environment Config

.github/workflows/build-osx-bundle.yml, .github/workflows/build-windows-installer.yml, .release/pypi/inference.cli.setup.py, .release/pypi/inference.core.setup.py, .release/pypi/inference.cpu.setup.py, .release/pypi/inference.gpu.setup.py, .release/pypi/inference.sdk.setup.py, .release/pypi/inference.setup.py, app_bundles/osx/build.py, app_bundles/osx/hooks/hook-inference.models.py, app_bundles/osx/inference-app.spec, app_bundles/osx/requirements.txt, app_bundles/osx/run_inference.py, app_bundles/windows/build.py, app_bundles/windows/hooks/hook-inference.models.py, app_bundles/windows/inference.spec, app_bundles/windows/requirements.txt, app_bundles/windows/run_inference.py, docs/install/index.md, docs/install/mac.md, docs/install/windows.md, inference/core/version.py
Several adjustments were needed to make the builds work directly from this repo
everything works now via automated builds on inference repo:
- builds off of code in branch the action is triggered on
- code signing for osx and windows so the OS trusts the binary and users don't get any scary dialogs and don't have to do anything except double click
- action can be manually triggered (and custom version number specified for filenames/config files separate from python package version for testing or if we need to manually make a build from a specific branch for some reason)
- builds for both osx and windows will trigger on release and automatically upload build artifacts to github release with the tag/version for that release (and app versions/filenames reflect the inference release version). …
=> App Bundle fixes for inference repo build

inference/core/workflows/core_steps/classical_cv/size_measurement/v1.py
Accept static reference polygon as input in size measurement block
CI passing
tested manually
N/A
N/A
=> Accept static reference polygon as input in size measurement block

tests/inference/models_predictions_tests/test_owlv2.py
=> Fix OwlV2 test

inference/models/owlv2/owlv2.py
Fix owlv2 loading for torch 27. Loading code is safe since these files are created by roboflow api (trusted)
locally
n/a
=> Fix owlvit for torch 27

.github/workflows/integration_tests_inference_cli_depending_on_inference_x86.yml, .github/workflows/integration_tests_inference_cli_x86.yml, .github/workflows/integration_tests_inference_models.yml, .github/workflows/integration_tests_workflows_x86.yml, .github/workflows/unit_tests_inference_cli_x86.yml, .github/workflows/unit_tests_inference_sdk_x86.yml, .github/workflows/unit_tests_inference_x86.yml, .github/workflows/unit_tests_workflows_x86.yml, docs/foundation/perception_encoder.md, inference/core/env.py, inference/models/README.md, inference/models/__init__.py, inference/models/perception_encoder/LICENSE, inference/models/perception_encoder/__init__.py, inference/models/perception_encoder/perception_encoder.py, requirements/requirements.transformers.txt, tests/inference/models_predictions_tests/test_perception_encoder.py
Add perception encoder. Tested on mps and on my t4 machine and everything works.
Locally and new predictions tests.
No
=> feat: add PerceptionEncoder model implementation with tests

docs/install/jetson.md
Added an overview section to the Jetson installation documentation that explains what Jetson devices are and lists the prerequisites needed before installation. This improves the documentation by providing context for new users who may not be familiar with Jetson devices and ensures they have all prerequisites in place before attempting installation.
List any dependencies that are required for this change: None
Used just a preview on the .md file on vs code!
Documentation changes only - no deployment considerations.
Added "NVIDIA Jetson Overview" section with a brief explanation and link to official documentation
Added "Prerequisites" section detailing JetPack version requirements
Added links …
=> version1 overview

app_bundles/osx/inference-app.spec, app_bundles/windows/inference.spec
Bug fix for issue reported here: https://github.com/roboflow/inference/issues/1322
did of a build of each and confirmed local builder is working as expected
n/a
n/a
=> include editor.html in app bundle builds

inference/core/workflows/execution_engine/v1/executor/output_constructor.py, inference/models/smolvlm/__init__.py
This change only adds logs such that we can observer what is wrong.
* CI
=> Add serialisation error logs

inference/core/workflows/core_steps/common/serializers.py, inference/models/smolvlm/__init__.py, tests/workflows/unit_tests/core_steps/common/test_serializers.py
This is PR that fixes the problem with one-dim segmentations (at least to the extend - comments state where the other problems are).
* CI
* new tests
=> Add fix for empty segmentations

.github/workflows/integration_tests_inference_cli_depending_on_inference_x86.yml, .github/workflows/integration_tests_inference_cli_x86.yml, .github/workflows/integration_tests_inference_models.yml, .github/workflows/integration_tests_workflows_x86.yml, .github/workflows/unit_tests_inference_cli_x86.yml, .github/workflows/unit_tests_inference_sdk_x86.yml, .github/workflows/unit_tests_inference_x86.yml, .github/workflows/unit_tests_workflows_x86.yml, docker/dockerfiles/Dockerfile.onnx.gpu, tests/inference/integration_tests/test_perception_encoder.py
=> Try to fix gpu build

inference/core/interfaces/http/http_api.py, inference/core/managers/base.py, inference/core/managers/decorators/base.py, inference/core/managers/decorators/fixed_size_cache.py, inference/core/models/roboflow.py, inference/core/registries/base.py, inference/core/registries/roboflow.py, inference/core/roboflow_api.py
Code review of `feat/pass-countinference-to-serverless-getweights`
-   [x] Code review
CI passing
N/A
N/A
=> Review `feat/pass-countinference-to-serverless-getweights`

requirements/requirements.transformers.txt
Update to support new train containers
Tested locally
=> Bump PEFT ~0.15

inference/core/workflows/core_steps/sinks/onvif_movement/v1.py
Dumb error - a missing indent was preventing the block from working correctly with a tracker.
-   [X ] Bug fix (non-breaking change which fixes an issue)
Tested on 2 cameras and with a workflow that keeps track of the tracking ids
N/A
=> Fix indentation

examples/webrtc/README.md, examples/webrtc/webcam.py, inference/core/interfaces/camera/video_source.py, inference/core/interfaces/stream_manager/manager_app/entities.py, inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py, inference/core/interfaces/stream_manager/manager_app/webrtc.py
Add webrtc data channel
CI passing
N/A
N/A
=> Add webrtc data channel

inference_experimental/README.md, inference_experimental/inference_exp/models/auto_loaders/core.py
* Added changes to improve README clarity
* Fixed bug with concurrency on symlinks creation (locked that part of code with FS lock)
* e2e
* CI
=> Improve README in terms of installation instructions and clarity

inference_experimental/README.md, inference_experimental/inference_exp/models/auto_loaders/auto_negotiation.py
Mainly changes in readme plus some minor fixes in code (typos and lowercasing backend to be more resilient)
* CI
* e2e
=> Improve readme to nicely list registered models

inference/models/rfdetr/rfdetr.py
Fix CUDA not propagating to Execution Provdiers
Locally
No
=> Fix rfdetr eps

.github/workflows/integration_tests_inference_experimental_cpu.yml, .github/workflows/integration_tests_inference_experimental_gpu.yml, .github/workflows/test.nvidia_t4.yml
Updates to Roboflow-GPU-VM-Runner broke our CI, fixing in this PR
CI passing
N/A
N/A
=> fixes due to updates to Roboflow-GPU-VM-Runner

inference_experimental/uv.lock
Run uv sync to fix inference-exp CI
CI passing
N/A
N/A
=> Run uv sync to fix inference-exp CI

.github/workflows/publish.pypi.inference_exp.yml
Inference exp pypi publisher ci improvements
CI passing
N/A
N/A
=> Inference exp pypi publisher ci improvements

inference_experimental/tests/integration_tests/models/test_clip_predictions.py
=> Fix test_clip_onnx_image_prediction_for_numpy

requirements/requirements.transformers.txt
bump accelerate dependency version
dependency / maintenance
unit / integration tests
n/a
n/a
=> bump accelerate version to > 1 < 2

inference/core/managers/decorators/locked_load.py, inference/core/managers/decorators/logger.py, inference/core/models/roboflow.py, inference/core/registries/roboflow.py, inference/core/roboflow_api.py, inference/models/owlv2/owlv2.py, inference/models/transformers/transformers.py
countinference was not passed for instant models
N/A
N/A
=> Pass countinference to get model artifacts

requirements/_requirements.txt
=> Update aiortc dependency

inference/core/entities/responses/ocr.py, inference/core/interfaces/http/http_api.py, inference/core/version.py, inference/core/workflows/core_steps/common/utils.py, inference/core/workflows/core_steps/models/foundation/easy_ocr/v1.py, inference/core/workflows/core_steps/models/foundation/ocr/v1.py, inference/models/doctr/doctr_model.py, inference/models/easy_ocr/easy_ocr.py, inference_sdk/http/client.py, inference_sdk/http/utils/aliases.py
Fixing issues with OCR pr spotted before release
* e2e
* CI
=> Fix ocr changes

inference/core/version.py, inference/core/workflows/core_steps/models/foundation/easy_ocr/v1.py, inference_sdk/http/client.py
Adding another bugfix for easy-ocr remote execution.
* manual test
* CI
=> Add bugfix for easyocr

inference_experimental/inference_exp/models/yolov8/yolov8_key_points_detection_trt.py, inference_experimental/pyproject.toml, inference_experimental/uv.lock
Fixing mising init param for TRT implementation of yolov8-pose in inference-exp
* e2e tested
=> Fix issue with inference-exp Yolov8-pose TRT implementation

inference/core/interfaces/http/http_api.py
Allows the parameter to disable model monitoring to also be included in legacy requests
ENT-392
Staging
N/A
N/A
=> Add disable model monitoring on legacy requests
